// Code generated by ent, DO NOT EDIT.

package room

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldIsStartingRoom holds the string denoting the isstartingroom field in the database.
	FieldIsStartingRoom = "is_starting_room"
	// FieldExits holds the string denoting the exits field in the database.
	FieldExits = "exits"
	// FieldAtmosphere holds the string denoting the atmosphere field in the database.
	FieldAtmosphere = "atmosphere"
	// EdgeCharacters holds the string denoting the characters edge name in mutations.
	EdgeCharacters = "characters"
	// EdgeEquipment holds the string denoting the equipment edge name in mutations.
	EdgeEquipment = "equipment"
	// Table holds the table name of the room in the database.
	Table = "rooms"
	// CharactersTable is the table that holds the characters relation/edge.
	CharactersTable = "characters"
	// CharactersInverseTable is the table name for the Character entity.
	// It exists in this package in order to avoid circular dependency with the "character" package.
	CharactersInverseTable = "characters"
	// CharactersColumn is the table column denoting the characters relation/edge.
	CharactersColumn = "room_characters"
	// EquipmentTable is the table that holds the equipment relation/edge.
	EquipmentTable = "equipment"
	// EquipmentInverseTable is the table name for the Equipment entity.
	// It exists in this package in order to avoid circular dependency with the "equipment" package.
	EquipmentInverseTable = "equipment"
	// EquipmentColumn is the table column denoting the equipment relation/edge.
	EquipmentColumn = "room_equipment"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldIsStartingRoom,
	FieldExits,
	FieldAtmosphere,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsStartingRoom holds the default value on creation for the "isStartingRoom" field.
	DefaultIsStartingRoom bool
)

// Atmosphere defines the type for the "atmosphere" enum field.
type Atmosphere string

// AtmosphereAir is the default value of the Atmosphere enum.
const DefaultAtmosphere = AtmosphereAir

// Atmosphere values.
const (
	AtmosphereAir   Atmosphere = "air"
	AtmosphereWater Atmosphere = "water"
	AtmosphereWind  Atmosphere = "wind"
)

func (a Atmosphere) String() string {
	return string(a)
}

// AtmosphereValidator is a validator for the "atmosphere" field enum values. It is called by the builders before save.
func AtmosphereValidator(a Atmosphere) error {
	switch a {
	case AtmosphereAir, AtmosphereWater, AtmosphereWind:
		return nil
	default:
		return fmt.Errorf("room: invalid enum value for atmosphere field: %q", a)
	}
}

// OrderOption defines the ordering options for the Room queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByIsStartingRoom orders the results by the isStartingRoom field.
func ByIsStartingRoom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsStartingRoom, opts...).ToFunc()
}

// ByAtmosphere orders the results by the atmosphere field.
func ByAtmosphere(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAtmosphere, opts...).ToFunc()
}

// ByCharactersCount orders the results by characters count.
func ByCharactersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCharactersStep(), opts...)
	}
}

// ByCharacters orders the results by characters terms.
func ByCharacters(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCharactersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEquipmentCount orders the results by equipment count.
func ByEquipmentCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEquipmentStep(), opts...)
	}
}

// ByEquipment orders the results by equipment terms.
func ByEquipment(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEquipmentStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCharactersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CharactersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CharactersTable, CharactersColumn),
	)
}
func newEquipmentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EquipmentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EquipmentTable, EquipmentColumn),
	)
}
