// Code generated by ent, DO NOT EDIT.

package effecthook

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the effecthook type in the database.
	Label = "effect_hook"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWorldID holds the string denoting the world_id field in the database.
	FieldWorldID = "world_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEvent holds the string denoting the event field in the database.
	FieldEvent = "event"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldCondition holds the string denoting the condition field in the database.
	FieldCondition = "condition"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// EdgeWorld holds the string denoting the world edge name in mutations.
	EdgeWorld = "world"
	// EdgeEffect holds the string denoting the effect edge name in mutations.
	EdgeEffect = "effect"
	// EdgeNpcTemplate holds the string denoting the npc_template edge name in mutations.
	EdgeNpcTemplate = "npc_template"
	// Table holds the table name of the effecthook in the database.
	Table = "effect_hooks"
	// WorldTable is the table that holds the world relation/edge. The primary key declared below.
	WorldTable = "world_effect_hooks"
	// WorldInverseTable is the table name for the World entity.
	// It exists in this package in order to avoid circular dependency with the "world" package.
	WorldInverseTable = "worlds"
	// EffectTable is the table that holds the effect relation/edge.
	EffectTable = "effect_hooks"
	// EffectInverseTable is the table name for the Effect entity.
	// It exists in this package in order to avoid circular dependency with the "effect" package.
	EffectInverseTable = "effects"
	// EffectColumn is the table column denoting the effect relation/edge.
	EffectColumn = "effect_hooks"
	// NpcTemplateTable is the table that holds the npc_template relation/edge.
	NpcTemplateTable = "effect_hooks"
	// NpcTemplateInverseTable is the table name for the NPCTemplate entity.
	// It exists in this package in order to avoid circular dependency with the "npctemplate" package.
	NpcTemplateInverseTable = "npc_templates"
	// NpcTemplateColumn is the table column denoting the npc_template relation/edge.
	NpcTemplateColumn = "npc_template_hooks"
)

// Columns holds all SQL columns for effecthook fields.
var Columns = []string{
	FieldID,
	FieldWorldID,
	FieldName,
	FieldEvent,
	FieldTarget,
	FieldCondition,
	FieldEnabled,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "effect_hooks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"effect_hooks",
	"npc_template_hooks",
}

var (
	// WorldPrimaryKey and WorldColumn2 are the table columns denoting the
	// primary key for the world relation (M2M).
	WorldPrimaryKey = []string{"world_id", "effect_hook_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultWorldID holds the default value on creation for the "world_id" field.
	DefaultWorldID string
	// DefaultTarget holds the default value on creation for the "target" field.
	DefaultTarget string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the EffectHook queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByWorldID orders the results by the world_id field.
func ByWorldID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEvent orders the results by the event field.
func ByEvent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEvent, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByCondition orders the results by the condition field.
func ByCondition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCondition, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByWorldCount orders the results by world count.
func ByWorldCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWorldStep(), opts...)
	}
}

// ByWorld orders the results by world terms.
func ByWorld(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorldStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEffectField orders the results by effect field.
func ByEffectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEffectStep(), sql.OrderByField(field, opts...))
	}
}

// ByNpcTemplateField orders the results by npc_template field.
func ByNpcTemplateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNpcTemplateStep(), sql.OrderByField(field, opts...))
	}
}
func newWorldStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorldInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, WorldTable, WorldPrimaryKey...),
	)
}
func newEffectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EffectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EffectTable, EffectColumn),
	)
}
func newNpcTemplateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NpcTemplateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, NpcTemplateTable, NpcTemplateColumn),
	)
}
