// Code generated by ent, DO NOT EDIT.

package characterability

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the characterability type in the database.
	Label = "character_ability"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSlot holds the string denoting the slot field in the database.
	FieldSlot = "slot"
	// EdgeCharacter holds the string denoting the character edge name in mutations.
	EdgeCharacter = "character"
	// EdgeAbility holds the string denoting the ability edge name in mutations.
	EdgeAbility = "ability"
	// Table holds the table name of the characterability in the database.
	Table = "character_abilities"
	// CharacterTable is the table that holds the character relation/edge.
	CharacterTable = "character_abilities"
	// CharacterInverseTable is the table name for the Character entity.
	// It exists in this package in order to avoid circular dependency with the "character" package.
	CharacterInverseTable = "characters"
	// CharacterColumn is the table column denoting the character relation/edge.
	CharacterColumn = "character_abilities"
	// AbilityTable is the table that holds the ability relation/edge.
	AbilityTable = "character_abilities"
	// AbilityInverseTable is the table name for the Ability entity.
	// It exists in this package in order to avoid circular dependency with the "ability" package.
	AbilityInverseTable = "abilities"
	// AbilityColumn is the table column denoting the ability relation/edge.
	AbilityColumn = "ability_characters"
)

// Columns holds all SQL columns for characterability fields.
var Columns = []string{
	FieldID,
	FieldSlot,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "character_abilities"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ability_characters",
	"character_abilities",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the CharacterAbility queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySlot orders the results by the slot field.
func BySlot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlot, opts...).ToFunc()
}

// ByCharacterField orders the results by character field.
func ByCharacterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCharacterStep(), sql.OrderByField(field, opts...))
	}
}

// ByAbilityField orders the results by ability field.
func ByAbilityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAbilityStep(), sql.OrderByField(field, opts...))
	}
}
func newCharacterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CharacterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CharacterTable, CharacterColumn),
	)
}
func newAbilityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AbilityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AbilityTable, AbilityColumn),
	)
}
