// Code generated by ent, DO NOT EDIT.

package npcskill

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the npcskill type in the database.
	Label = "npc_skill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSlot holds the string denoting the slot field in the database.
	FieldSlot = "slot"
	// EdgeNpcTemplate holds the string denoting the npc_template edge name in mutations.
	EdgeNpcTemplate = "npc_template"
	// EdgeSkill holds the string denoting the skill edge name in mutations.
	EdgeSkill = "skill"
	// Table holds the table name of the npcskill in the database.
	Table = "npc_skills"
	// NpcTemplateTable is the table that holds the npc_template relation/edge. The primary key declared below.
	NpcTemplateTable = "npc_template_npc_skills"
	// NpcTemplateInverseTable is the table name for the NPCTemplate entity.
	// It exists in this package in order to avoid circular dependency with the "npctemplate" package.
	NpcTemplateInverseTable = "npc_templates"
	// SkillTable is the table that holds the skill relation/edge. The primary key declared below.
	SkillTable = "skill_npc_skills"
	// SkillInverseTable is the table name for the Skill entity.
	// It exists in this package in order to avoid circular dependency with the "skill" package.
	SkillInverseTable = "skills"
)

// Columns holds all SQL columns for npcskill fields.
var Columns = []string{
	FieldID,
	FieldSlot,
}

var (
	// NpcTemplatePrimaryKey and NpcTemplateColumn2 are the table columns denoting the
	// primary key for the npc_template relation (M2M).
	NpcTemplatePrimaryKey = []string{"npc_template_id", "npc_skill_id"}
	// SkillPrimaryKey and SkillColumn2 are the table columns denoting the
	// primary key for the skill relation (M2M).
	SkillPrimaryKey = []string{"skill_id", "npc_skill_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the NPCSkill queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySlot orders the results by the slot field.
func BySlot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlot, opts...).ToFunc()
}

// ByNpcTemplateCount orders the results by npc_template count.
func ByNpcTemplateCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNpcTemplateStep(), opts...)
	}
}

// ByNpcTemplate orders the results by npc_template terms.
func ByNpcTemplate(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNpcTemplateStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySkillCount orders the results by skill count.
func BySkillCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSkillStep(), opts...)
	}
}

// BySkill orders the results by skill terms.
func BySkill(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSkillStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newNpcTemplateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NpcTemplateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, NpcTemplateTable, NpcTemplatePrimaryKey...),
	)
}
func newSkillStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SkillInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, SkillTable, SkillPrimaryKey...),
	)
}
