// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AbilitiesColumns holds the columns for the "abilities" table.
	AbilitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString},
		{Name: "ability_type", Type: field.TypeString},
		{Name: "cost", Type: field.TypeInt, Default: 0},
		{Name: "cooldown", Type: field.TypeInt, Default: 0},
		{Name: "requirements", Type: field.TypeString, Nullable: true},
		{Name: "effect_type", Type: field.TypeString, Default: ""},
		{Name: "effect_value", Type: field.TypeInt, Default: 0},
		{Name: "effect_duration", Type: field.TypeInt, Default: 0},
		{Name: "scaling_stat", Type: field.TypeString, Nullable: true},
		{Name: "scaling_percent_per_point", Type: field.TypeFloat64, Default: 0},
		{Name: "mana_cost", Type: field.TypeInt, Default: 0},
		{Name: "stamina_cost", Type: field.TypeInt, Default: 0},
		{Name: "hp_cost", Type: field.TypeInt, Default: 0},
		{Name: "slug", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "required_tag", Type: field.TypeString, Nullable: true},
		{Name: "ability_class", Type: field.TypeString, Default: "active"},
		{Name: "proc_chance", Type: field.TypeFloat64, Default: 0},
		{Name: "proc_event", Type: field.TypeString, Nullable: true},
		{Name: "cooldown_seconds", Type: field.TypeInt, Default: 0},
		{Name: "faction_abilities", Type: field.TypeInt, Nullable: true},
	}
	// AbilitiesTable holds the schema information for the "abilities" table.
	AbilitiesTable = &schema.Table{
		Name:       "abilities",
		Columns:    AbilitiesColumns,
		PrimaryKey: []*schema.Column{AbilitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "abilities_factions_abilities",
				Columns:    []*schema.Column{AbilitiesColumns[21]},
				RefColumns: []*schema.Column{FactionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// AbilityEffectsColumns holds the columns for the "ability_effects" table.
	AbilityEffectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "effect_type", Type: field.TypeString},
		{Name: "damage_subtype", Type: field.TypeString, Default: ""},
		{Name: "target", Type: field.TypeString, Default: "enemy"},
		{Name: "value", Type: field.TypeInt, Default: 0},
		{Name: "duration", Type: field.TypeInt, Default: 0},
		{Name: "scaling_stat", Type: field.TypeString, Nullable: true},
		{Name: "scaling_ratio", Type: field.TypeFloat64, Default: 0},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "ability_effects", Type: field.TypeInt, Nullable: true},
	}
	// AbilityEffectsTable holds the schema information for the "ability_effects" table.
	AbilityEffectsTable = &schema.Table{
		Name:       "ability_effects",
		Columns:    AbilityEffectsColumns,
		PrimaryKey: []*schema.Column{AbilityEffectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ability_effects_abilities_effects",
				Columns:    []*schema.Column{AbilityEffectsColumns[9]},
				RefColumns: []*schema.Column{AbilitiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// AchievementsColumns holds the columns for the "achievements" table.
	AchievementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "icon", Type: field.TypeString, Nullable: true},
		{Name: "xp_reward", Type: field.TypeInt, Default: 0},
		{Name: "criteria", Type: field.TypeString, Nullable: true},
	}
	// AchievementsTable holds the schema information for the "achievements" table.
	AchievementsTable = &schema.Table{
		Name:       "achievements",
		Columns:    AchievementsColumns,
		PrimaryKey: []*schema.Column{AchievementsColumns[0]},
	}
	// CharactersColumns holds the columns for the "characters" table.
	CharactersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "password", Type: field.TypeString, Nullable: true},
		{Name: "is_npc", Type: field.TypeBool, Default: false},
		{Name: "starting_room_id", Type: field.TypeInt},
		{Name: "respawn_room_id", Type: field.TypeInt, Default: 5},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
		{Name: "is_immortal", Type: field.TypeBool, Default: false},
		{Name: "is_instance", Type: field.TypeBool, Default: false},
		{Name: "instance_number", Type: field.TypeInt, Default: 0},
		{Name: "npc_skill_id", Type: field.TypeString, Nullable: true},
		{Name: "npc_skill_cooldown", Type: field.TypeInt, Default: 0},
		{Name: "hitpoints", Type: field.TypeInt, Default: 100},
		{Name: "max_hitpoints", Type: field.TypeInt, Default: 100},
		{Name: "stamina", Type: field.TypeInt, Default: 50},
		{Name: "max_stamina", Type: field.TypeInt, Default: 50},
		{Name: "mana", Type: field.TypeInt, Default: 25},
		{Name: "max_mana", Type: field.TypeInt, Default: 25},
		{Name: "race", Type: field.TypeString, Default: "human"},
		{Name: "class", Type: field.TypeString, Default: "adventurer"},
		{Name: "specialty", Type: field.TypeString, Nullable: true},
		{Name: "level", Type: field.TypeInt, Default: 1},
		{Name: "xp", Type: field.TypeInt, Default: 0},
		{Name: "died_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_seen_at", Type: field.TypeTime, Nullable: true},
		{Name: "constitution", Type: field.TypeInt, Default: 10},
		{Name: "gender", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "strength", Type: field.TypeInt, Default: 10},
		{Name: "dexterity", Type: field.TypeInt, Default: 10},
		{Name: "intelligence", Type: field.TypeInt, Default: 10},
		{Name: "wisdom", Type: field.TypeInt, Default: 10},
		{Name: "skill_blades", Type: field.TypeInt, Default: 0},
		{Name: "skill_staves", Type: field.TypeInt, Default: 0},
		{Name: "skill_knives", Type: field.TypeInt, Default: 0},
		{Name: "skill_martial", Type: field.TypeInt, Default: 0},
		{Name: "skill_brawling", Type: field.TypeInt, Default: 0},
		{Name: "skill_tech", Type: field.TypeInt, Default: 0},
		{Name: "skill_light_armor", Type: field.TypeInt, Default: 0},
		{Name: "skill_cloth_armor", Type: field.TypeInt, Default: 0},
		{Name: "skill_heavy_armor", Type: field.TypeInt, Default: 0},
		{Name: "current_room_id", Type: field.TypeInt},
		{Name: "npc_template_id", Type: field.TypeString, Nullable: true},
		{Name: "room_characters", Type: field.TypeInt, Nullable: true},
		{Name: "user_characters", Type: field.TypeInt, Nullable: true},
	}
	// CharactersTable holds the schema information for the "characters" table.
	CharactersTable = &schema.Table{
		Name:       "characters",
		Columns:    CharactersColumns,
		PrimaryKey: []*schema.Column{CharactersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "characters_rooms_room",
				Columns:    []*schema.Column{CharactersColumns[41]},
				RefColumns: []*schema.Column{RoomsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "characters_npc_templates_npcTemplate",
				Columns:    []*schema.Column{CharactersColumns[42]},
				RefColumns: []*schema.Column{NpcTemplatesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "characters_rooms_characters",
				Columns:    []*schema.Column{CharactersColumns[43]},
				RefColumns: []*schema.Column{RoomsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "characters_users_characters",
				Columns:    []*schema.Column{CharactersColumns[44]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CharacterAbilitiesColumns holds the columns for the "character_abilities" table.
	CharacterAbilitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "slot", Type: field.TypeInt},
		{Name: "ability_characters", Type: field.TypeInt, Nullable: true},
		{Name: "character_abilities", Type: field.TypeInt, Nullable: true},
	}
	// CharacterAbilitiesTable holds the schema information for the "character_abilities" table.
	CharacterAbilitiesTable = &schema.Table{
		Name:       "character_abilities",
		Columns:    CharacterAbilitiesColumns,
		PrimaryKey: []*schema.Column{CharacterAbilitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "character_abilities_abilities_characters",
				Columns:    []*schema.Column{CharacterAbilitiesColumns[2]},
				RefColumns: []*schema.Column{AbilitiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "character_abilities_characters_abilities",
				Columns:    []*schema.Column{CharacterAbilitiesColumns[3]},
				RefColumns: []*schema.Column{CharactersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CharacterCompetenciesColumns holds the columns for the "character_competencies" table.
	CharacterCompetenciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "xp", Type: field.TypeInt, Default: 0},
		{Name: "level", Type: field.TypeInt, Default: 0},
		{Name: "character_competencies", Type: field.TypeInt},
		{Name: "competency_category_character_competencies", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(64)"}},
	}
	// CharacterCompetenciesTable holds the schema information for the "character_competencies" table.
	CharacterCompetenciesTable = &schema.Table{
		Name:       "character_competencies",
		Columns:    CharacterCompetenciesColumns,
		PrimaryKey: []*schema.Column{CharacterCompetenciesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "character_competencies_characters_competencies",
				Columns:    []*schema.Column{CharacterCompetenciesColumns[3]},
				RefColumns: []*schema.Column{CharactersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "character_competencies_competency_categories_character_competencies",
				Columns:    []*schema.Column{CharacterCompetenciesColumns[4]},
				RefColumns: []*schema.Column{CompetencyCategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CharacterFactionsColumns holds the columns for the "character_factions" table.
	CharacterFactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "reputation", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "joined_at", Type: field.TypeTime},
		{Name: "character_faction_memberships", Type: field.TypeInt, Nullable: true},
		{Name: "faction_character_factions", Type: field.TypeInt, Nullable: true},
	}
	// CharacterFactionsTable holds the schema information for the "character_factions" table.
	CharacterFactionsTable = &schema.Table{
		Name:       "character_factions",
		Columns:    CharacterFactionsColumns,
		PrimaryKey: []*schema.Column{CharacterFactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "character_factions_characters_faction_memberships",
				Columns:    []*schema.Column{CharacterFactionsColumns[4]},
				RefColumns: []*schema.Column{CharactersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "character_factions_factions_character_factions",
				Columns:    []*schema.Column{CharacterFactionsColumns[5]},
				RefColumns: []*schema.Column{FactionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CharacterTagsColumns holds the columns for the "character_tags" table.
	CharacterTagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tag", Type: field.TypeString},
		{Name: "source", Type: field.TypeString, Default: "system"},
		{Name: "earned_at", Type: field.TypeTime},
		{Name: "character_tags", Type: field.TypeInt, Nullable: true},
	}
	// CharacterTagsTable holds the schema information for the "character_tags" table.
	CharacterTagsTable = &schema.Table{
		Name:       "character_tags",
		Columns:    CharacterTagsColumns,
		PrimaryKey: []*schema.Column{CharacterTagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "character_tags_characters_tags",
				Columns:    []*schema.Column{CharacterTagsColumns[4]},
				RefColumns: []*schema.Column{CharactersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CompetencyCategoriesColumns holds the columns for the "competency_categories" table.
	CompetencyCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"postgres": "varchar(64)"}},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "xp_multiplier", Type: field.TypeFloat64, Default: 0.2},
	}
	// CompetencyCategoriesTable holds the schema information for the "competency_categories" table.
	CompetencyCategoriesTable = &schema.Table{
		Name:       "competency_categories",
		Columns:    CompetencyCategoriesColumns,
		PrimaryKey: []*schema.Column{CompetencyCategoriesColumns[0]},
	}
	// CompetencyLevelThresholdsColumns holds the columns for the "competency_level_thresholds" table.
	CompetencyLevelThresholdsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"postgres": "varchar(128)"}},
		{Name: "level", Type: field.TypeInt},
		{Name: "xp_required", Type: field.TypeInt},
		{Name: "damage_multiplier", Type: field.TypeFloat64, Default: 1},
		{Name: "defense_multiplier", Type: field.TypeFloat64, Default: 1},
		{Name: "competency_category_thresholds", Type: field.TypeString, SchemaType: map[string]string{"postgres": "varchar(64)"}},
	}
	// CompetencyLevelThresholdsTable holds the schema information for the "competency_level_thresholds" table.
	CompetencyLevelThresholdsTable = &schema.Table{
		Name:       "competency_level_thresholds",
		Columns:    CompetencyLevelThresholdsColumns,
		PrimaryKey: []*schema.Column{CompetencyLevelThresholdsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "competency_level_thresholds_competency_categories_thresholds",
				Columns:    []*schema.Column{CompetencyLevelThresholdsColumns[5]},
				RefColumns: []*schema.Column{CompetencyCategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DamageLogsColumns holds the columns for the "damage_logs" table.
	DamageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "attacker_id", Type: field.TypeInt},
		{Name: "target_id", Type: field.TypeInt},
		{Name: "damage", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
	}
	// DamageLogsTable holds the schema information for the "damage_logs" table.
	DamageLogsTable = &schema.Table{
		Name:       "damage_logs",
		Columns:    DamageLogsColumns,
		PrimaryKey: []*schema.Column{DamageLogsColumns[0]},
	}
	// EquipmentColumns holds the columns for the "equipment" table.
	EquipmentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "slot", Type: field.TypeString},
		{Name: "level", Type: field.TypeInt, Default: 1},
		{Name: "weight", Type: field.TypeInt, Default: 0},
		{Name: "is_equipped", Type: field.TypeBool, Default: false},
		{Name: "is_immovable", Type: field.TypeBool, Default: false},
		{Name: "color", Type: field.TypeString, Default: ""},
		{Name: "is_visible", Type: field.TypeBool, Default: true},
		{Name: "item_type", Type: field.TypeString, Default: "misc"},
		{Name: "owner_id", Type: field.TypeInt, Nullable: true},
		{Name: "effect_type", Type: field.TypeString, Default: ""},
		{Name: "effect_value", Type: field.TypeInt, Default: 0},
		{Name: "effect_duration", Type: field.TypeInt, Default: 0},
		{Name: "healing", Type: field.TypeInt, Default: 0},
		{Name: "effect", Type: field.TypeString, Default: ""},
		{Name: "is_container", Type: field.TypeBool, Default: false},
		{Name: "container_capacity", Type: field.TypeInt, Default: 0},
		{Name: "is_locked", Type: field.TypeBool, Default: false},
		{Name: "key_item_id", Type: field.TypeString, Nullable: true},
		{Name: "contained_items", Type: field.TypeString, Default: ""},
		{Name: "reveal_condition", Type: field.TypeString, Default: ""},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "armor_rating", Type: field.TypeInt, Default: 0},
		{Name: "armor_type", Type: field.TypeString, Default: ""},
		{Name: "stats", Type: field.TypeJSON},
		{Name: "rarity", Type: field.TypeString, Default: "common"},
		{Name: "skill_requirement", Type: field.TypeString, Default: ""},
		{Name: "skill_requirement_level", Type: field.TypeInt, Default: 0},
		{Name: "damage_dice_count", Type: field.TypeInt, Default: 0},
		{Name: "damage_dice_sides", Type: field.TypeInt, Default: 0},
		{Name: "damage_bonus", Type: field.TypeInt, Default: 0},
		{Name: "damage_type", Type: field.TypeString, Default: ""},
		{Name: "weapon_type", Type: field.TypeString, Default: ""},
		{Name: "is_two_handed", Type: field.TypeBool, Default: false},
		{Name: "equipment_template_id", Type: field.TypeString, Nullable: true},
		{Name: "room_equipment", Type: field.TypeInt, Nullable: true},
	}
	// EquipmentTable holds the schema information for the "equipment" table.
	EquipmentTable = &schema.Table{
		Name:       "equipment",
		Columns:    EquipmentColumns,
		PrimaryKey: []*schema.Column{EquipmentColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "equipment_equipment_templates_equipment",
				Columns:    []*schema.Column{EquipmentColumns[36]},
				RefColumns: []*schema.Column{EquipmentTemplatesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "equipment_rooms_equipment",
				Columns:    []*schema.Column{EquipmentColumns[37]},
				RefColumns: []*schema.Column{RoomsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// EquipmentTemplatesColumns holds the columns for the "equipment_templates" table.
	EquipmentTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "slot", Type: field.TypeString},
		{Name: "level", Type: field.TypeInt, Default: 1},
		{Name: "weight", Type: field.TypeInt, Default: 0},
		{Name: "item_type", Type: field.TypeString, Default: "misc"},
		{Name: "stats", Type: field.TypeJSON, Nullable: true},
		{Name: "color", Type: field.TypeString, Default: ""},
		{Name: "is_visible", Type: field.TypeBool, Default: true},
		{Name: "is_immovable", Type: field.TypeBool, Default: false},
		{Name: "effect_type", Type: field.TypeString, Default: ""},
		{Name: "effect_value", Type: field.TypeInt, Default: 0},
		{Name: "effect_duration", Type: field.TypeInt, Default: 0},
		{Name: "is_container", Type: field.TypeBool, Default: false},
		{Name: "container_capacity", Type: field.TypeInt, Default: 0},
		{Name: "is_locked", Type: field.TypeBool, Default: false},
		{Name: "key_item_id", Type: field.TypeString, Nullable: true},
		{Name: "reveal_condition", Type: field.TypeString, Default: ""},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "armor_rating", Type: field.TypeInt, Default: 0},
		{Name: "armor_type", Type: field.TypeString, Default: ""},
		{Name: "rarity", Type: field.TypeString, Default: "common"},
		{Name: "skill_requirement", Type: field.TypeString, Default: ""},
		{Name: "skill_requirement_level", Type: field.TypeInt, Default: 0},
		{Name: "damage_dice_count", Type: field.TypeInt, Default: 0},
		{Name: "damage_dice_sides", Type: field.TypeInt, Default: 0},
		{Name: "damage_bonus", Type: field.TypeInt, Default: 0},
		{Name: "damage_type", Type: field.TypeString, Default: ""},
		{Name: "weapon_type", Type: field.TypeString, Default: ""},
		{Name: "is_two_handed", Type: field.TypeBool, Default: false},
	}
	// EquipmentTemplatesTable holds the schema information for the "equipment_templates" table.
	EquipmentTemplatesTable = &schema.Table{
		Name:       "equipment_templates",
		Columns:    EquipmentTemplatesColumns,
		PrimaryKey: []*schema.Column{EquipmentTemplatesColumns[0]},
	}
	// FactionsColumns holds the columns for the "factions" table.
	FactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "faction_category_factions", Type: field.TypeInt, Nullable: true},
	}
	// FactionsTable holds the schema information for the "factions" table.
	FactionsTable = &schema.Table{
		Name:       "factions",
		Columns:    FactionsColumns,
		PrimaryKey: []*schema.Column{FactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "factions_faction_categories_factions",
				Columns:    []*schema.Column{FactionsColumns[4]},
				RefColumns: []*schema.Column{FactionCategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// FactionCategoriesColumns holds the columns for the "faction_categories" table.
	FactionCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "max_memberships", Type: field.TypeInt, Default: 1},
		{Name: "auto_join", Type: field.TypeBool, Default: false},
	}
	// FactionCategoriesTable holds the schema information for the "faction_categories" table.
	FactionCategoriesTable = &schema.Table{
		Name:       "faction_categories",
		Columns:    FactionCategoriesColumns,
		PrimaryKey: []*schema.Column{FactionCategoriesColumns[0]},
	}
	// FactionRequiredTagsColumns holds the columns for the "faction_required_tags" table.
	FactionRequiredTagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "required_tag", Type: field.TypeString},
		{Name: "faction_required_tags", Type: field.TypeInt, Nullable: true},
	}
	// FactionRequiredTagsTable holds the schema information for the "faction_required_tags" table.
	FactionRequiredTagsTable = &schema.Table{
		Name:       "faction_required_tags",
		Columns:    FactionRequiredTagsColumns,
		PrimaryKey: []*schema.Column{FactionRequiredTagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "faction_required_tags_factions_required_tags",
				Columns:    []*schema.Column{FactionRequiredTagsColumns[2]},
				RefColumns: []*schema.Column{FactionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// GameConfigsColumns holds the columns for the "game_configs" table.
	GameConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString},
	}
	// GameConfigsTable holds the schema information for the "game_configs" table.
	GameConfigsTable = &schema.Table{
		Name:       "game_configs",
		Columns:    GameConfigsColumns,
		PrimaryKey: []*schema.Column{GameConfigsColumns[0]},
	}
	// GendersColumns holds the columns for the "genders" table.
	GendersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "subject_pronoun", Type: field.TypeString},
		{Name: "object_pronoun", Type: field.TypeString},
		{Name: "possessive_pronoun", Type: field.TypeString},
	}
	// GendersTable holds the schema information for the "genders" table.
	GendersTable = &schema.Table{
		Name:       "genders",
		Columns:    GendersColumns,
		PrimaryKey: []*schema.Column{GendersColumns[0]},
	}
	// NpcAbilitiesColumns holds the columns for the "npc_abilities" table.
	NpcAbilitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "slot", Type: field.TypeInt},
	}
	// NpcAbilitiesTable holds the schema information for the "npc_abilities" table.
	NpcAbilitiesTable = &schema.Table{
		Name:       "npc_abilities",
		Columns:    NpcAbilitiesColumns,
		PrimaryKey: []*schema.Column{NpcAbilitiesColumns[0]},
	}
	// NpcTemplatesColumns holds the columns for the "npc_templates" table.
	NpcTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "race", Type: field.TypeString},
		{Name: "disposition", Type: field.TypeEnum, Enums: []string{"hostile", "friendly", "neutral"}, Default: "neutral"},
		{Name: "level", Type: field.TypeInt, Default: 1},
		{Name: "xp_value", Type: field.TypeInt, Default: 0},
		{Name: "skills", Type: field.TypeJSON},
		{Name: "trades_with", Type: field.TypeJSON},
		{Name: "greeting", Type: field.TypeString, Size: 2147483647},
		{Name: "respawn_rooms", Type: field.TypeJSON, Nullable: true},
		{Name: "respawn_cooldown", Type: field.TypeInt, Nullable: true, Default: 60},
	}
	// NpcTemplatesTable holds the schema information for the "npc_templates" table.
	NpcTemplatesTable = &schema.Table{
		Name:       "npc_templates",
		Columns:    NpcTemplatesColumns,
		PrimaryKey: []*schema.Column{NpcTemplatesColumns[0]},
	}
	// RacesColumns holds the columns for the "races" table.
	RacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "stat_modifiers", Type: field.TypeString, Nullable: true},
		{Name: "skill_grants", Type: field.TypeString, Nullable: true},
		{Name: "equipment_slots", Type: field.TypeJSON},
		{Name: "is_playable", Type: field.TypeBool, Default: true},
		{Name: "color", Type: field.TypeString, Nullable: true},
	}
	// RacesTable holds the schema information for the "races" table.
	RacesTable = &schema.Table{
		Name:       "races",
		Columns:    RacesColumns,
		PrimaryKey: []*schema.Column{RacesColumns[0]},
	}
	// RoomsColumns holds the columns for the "rooms" table.
	RoomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "is_starting_room", Type: field.TypeBool, Default: false},
		{Name: "is_root_room", Type: field.TypeBool, Default: false},
		{Name: "exits", Type: field.TypeJSON},
		{Name: "atmosphere", Type: field.TypeEnum, Enums: []string{"air", "water", "wind"}, Default: "air"},
		{Name: "posx", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "posy", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "posz", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "version", Type: field.TypeInt, Default: 1},
	}
	// RoomsTable holds the schema information for the "rooms" table.
	RoomsTable = &schema.Table{
		Name:       "rooms",
		Columns:    RoomsColumns,
		PrimaryKey: []*schema.Column{RoomsColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "color", Type: field.TypeString, Nullable: true},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
		{Name: "god_mode", Type: field.TypeBool, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// AbilityNpcAbilitiesColumns holds the columns for the "ability_npc_abilities" table.
	AbilityNpcAbilitiesColumns = []*schema.Column{
		{Name: "ability_id", Type: field.TypeInt},
		{Name: "npc_ability_id", Type: field.TypeInt},
	}
	// AbilityNpcAbilitiesTable holds the schema information for the "ability_npc_abilities" table.
	AbilityNpcAbilitiesTable = &schema.Table{
		Name:       "ability_npc_abilities",
		Columns:    AbilityNpcAbilitiesColumns,
		PrimaryKey: []*schema.Column{AbilityNpcAbilitiesColumns[0], AbilityNpcAbilitiesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ability_npc_abilities_ability_id",
				Columns:    []*schema.Column{AbilityNpcAbilitiesColumns[0]},
				RefColumns: []*schema.Column{AbilitiesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "ability_npc_abilities_npc_ability_id",
				Columns:    []*schema.Column{AbilityNpcAbilitiesColumns[1]},
				RefColumns: []*schema.Column{NpcAbilitiesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// NpcTemplateNpcAbilitiesColumns holds the columns for the "npc_template_npc_abilities" table.
	NpcTemplateNpcAbilitiesColumns = []*schema.Column{
		{Name: "npc_template_id", Type: field.TypeString},
		{Name: "npc_ability_id", Type: field.TypeInt},
	}
	// NpcTemplateNpcAbilitiesTable holds the schema information for the "npc_template_npc_abilities" table.
	NpcTemplateNpcAbilitiesTable = &schema.Table{
		Name:       "npc_template_npc_abilities",
		Columns:    NpcTemplateNpcAbilitiesColumns,
		PrimaryKey: []*schema.Column{NpcTemplateNpcAbilitiesColumns[0], NpcTemplateNpcAbilitiesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "npc_template_npc_abilities_npc_template_id",
				Columns:    []*schema.Column{NpcTemplateNpcAbilitiesColumns[0]},
				RefColumns: []*schema.Column{NpcTemplatesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "npc_template_npc_abilities_npc_ability_id",
				Columns:    []*schema.Column{NpcTemplateNpcAbilitiesColumns[1]},
				RefColumns: []*schema.Column{NpcAbilitiesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TagRacesColumns holds the columns for the "tag_races" table.
	TagRacesColumns = []*schema.Column{
		{Name: "tag_id", Type: field.TypeInt},
		{Name: "race_id", Type: field.TypeInt},
	}
	// TagRacesTable holds the schema information for the "tag_races" table.
	TagRacesTable = &schema.Table{
		Name:       "tag_races",
		Columns:    TagRacesColumns,
		PrimaryKey: []*schema.Column{TagRacesColumns[0], TagRacesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_races_tag_id",
				Columns:    []*schema.Column{TagRacesColumns[0]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tag_races_race_id",
				Columns:    []*schema.Column{TagRacesColumns[1]},
				RefColumns: []*schema.Column{RacesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AbilitiesTable,
		AbilityEffectsTable,
		AchievementsTable,
		CharactersTable,
		CharacterAbilitiesTable,
		CharacterCompetenciesTable,
		CharacterFactionsTable,
		CharacterTagsTable,
		CompetencyCategoriesTable,
		CompetencyLevelThresholdsTable,
		DamageLogsTable,
		EquipmentTable,
		EquipmentTemplatesTable,
		FactionsTable,
		FactionCategoriesTable,
		FactionRequiredTagsTable,
		GameConfigsTable,
		GendersTable,
		NpcAbilitiesTable,
		NpcTemplatesTable,
		RacesTable,
		RoomsTable,
		TagsTable,
		UsersTable,
		AbilityNpcAbilitiesTable,
		NpcTemplateNpcAbilitiesTable,
		TagRacesTable,
	}
)

func init() {
	AbilitiesTable.ForeignKeys[0].RefTable = FactionsTable
	AbilityEffectsTable.ForeignKeys[0].RefTable = AbilitiesTable
	CharactersTable.ForeignKeys[0].RefTable = RoomsTable
	CharactersTable.ForeignKeys[1].RefTable = NpcTemplatesTable
	CharactersTable.ForeignKeys[2].RefTable = RoomsTable
	CharactersTable.ForeignKeys[3].RefTable = UsersTable
	CharacterAbilitiesTable.ForeignKeys[0].RefTable = AbilitiesTable
	CharacterAbilitiesTable.ForeignKeys[1].RefTable = CharactersTable
	CharacterCompetenciesTable.ForeignKeys[0].RefTable = CharactersTable
	CharacterCompetenciesTable.ForeignKeys[1].RefTable = CompetencyCategoriesTable
	CharacterFactionsTable.ForeignKeys[0].RefTable = CharactersTable
	CharacterFactionsTable.ForeignKeys[1].RefTable = FactionsTable
	CharacterTagsTable.ForeignKeys[0].RefTable = CharactersTable
	CompetencyLevelThresholdsTable.ForeignKeys[0].RefTable = CompetencyCategoriesTable
	EquipmentTable.ForeignKeys[0].RefTable = EquipmentTemplatesTable
	EquipmentTable.ForeignKeys[1].RefTable = RoomsTable
	FactionsTable.ForeignKeys[0].RefTable = FactionCategoriesTable
	FactionRequiredTagsTable.ForeignKeys[0].RefTable = FactionsTable
	AbilityNpcAbilitiesTable.ForeignKeys[0].RefTable = AbilitiesTable
	AbilityNpcAbilitiesTable.ForeignKeys[1].RefTable = NpcAbilitiesTable
	NpcTemplateNpcAbilitiesTable.ForeignKeys[0].RefTable = NpcTemplatesTable
	NpcTemplateNpcAbilitiesTable.ForeignKeys[1].RefTable = NpcAbilitiesTable
	TagRacesTable.ForeignKeys[0].RefTable = TagsTable
	TagRacesTable.ForeignKeys[1].RefTable = RacesTable
}
