// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"herbst/db/ability"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Ability is the model entity for the Ability schema.
type Ability struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// AbilityType holds the value of the "ability_type" field.
	AbilityType string `json:"ability_type,omitempty"`
	// Cost holds the value of the "cost" field.
	Cost int `json:"cost,omitempty"`
	// Cooldown holds the value of the "cooldown" field.
	Cooldown int `json:"cooldown,omitempty"`
	// Requirements holds the value of the "requirements" field.
	Requirements string `json:"requirements,omitempty"`
	// ManaCost holds the value of the "mana_cost" field.
	ManaCost int `json:"mana_cost,omitempty"`
	// StaminaCost holds the value of the "stamina_cost" field.
	StaminaCost int `json:"stamina_cost,omitempty"`
	// HpCost holds the value of the "hp_cost" field.
	HpCost int `json:"hp_cost,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AbilityQuery when eager-loading is set.
	Edges        AbilityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AbilityEdges holds the relations/edges for other nodes in the graph.
type AbilityEdges struct {
	// Characters holds the value of the characters edge.
	Characters []*Character `json:"characters,omitempty"`
	// Effects holds the value of the effects edge.
	Effects []*AbilityEffect `json:"effects,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CharactersOrErr returns the Characters value or an error if the edge
// was not loaded in eager-loading.
func (e AbilityEdges) CharactersOrErr() ([]*Character, error) {
	if e.loadedTypes[0] {
		return e.Characters, nil
	}
	return nil, &NotLoadedError{edge: "characters"}
}

// EffectsOrErr returns the Effects value or an error if the edge
// was not loaded in eager-loading.
func (e AbilityEdges) EffectsOrErr() ([]*AbilityEffect, error) {
	if e.loadedTypes[1] {
		return e.Effects, nil
	}
	return nil, &NotLoadedError{edge: "effects"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ability) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ability.FieldID, ability.FieldCost, ability.FieldCooldown, ability.FieldManaCost, ability.FieldStaminaCost, ability.FieldHpCost:
			values[i] = new(sql.NullInt64)
		case ability.FieldName, ability.FieldDescription, ability.FieldAbilityType, ability.FieldRequirements:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ability fields.
func (_m *Ability) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ability.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ability.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case ability.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case ability.FieldAbilityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ability_type", values[i])
			} else if value.Valid {
				_m.AbilityType = value.String
			}
		case ability.FieldCost:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cost", values[i])
			} else if value.Valid {
				_m.Cost = int(value.Int64)
			}
		case ability.FieldCooldown:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cooldown", values[i])
			} else if value.Valid {
				_m.Cooldown = int(value.Int64)
			}
		case ability.FieldRequirements:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requirements", values[i])
			} else if value.Valid {
				_m.Requirements = value.String
			}
		case ability.FieldManaCost:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mana_cost", values[i])
			} else if value.Valid {
				_m.ManaCost = int(value.Int64)
			}
		case ability.FieldStaminaCost:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stamina_cost", values[i])
			} else if value.Valid {
				_m.StaminaCost = int(value.Int64)
			}
		case ability.FieldHpCost:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hp_cost", values[i])
			} else if value.Valid {
				_m.HpCost = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ability.
// This includes values selected through modifiers, order, etc.
func (_m *Ability) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCharacters queries the "characters" edge of the Ability entity.
func (_m *Ability) QueryCharacters() *CharacterQuery {
	return NewAbilityClient(_m.config).QueryCharacters(_m)
}

// QueryEffects queries the "effects" edge of the Ability entity.
func (_m *Ability) QueryEffects() *AbilityEffectQuery {
	return NewAbilityClient(_m.config).QueryEffects(_m)
}

// Update returns a builder for updating this Ability.
// Note that you need to call Ability.Unwrap() before calling this method if this Ability
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ability) Update() *AbilityUpdateOne {
	return NewAbilityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ability entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ability) Unwrap() *Ability {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: Ability is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ability) String() string {
	var builder strings.Builder
	builder.WriteString("Ability(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("ability_type=")
	builder.WriteString(_m.AbilityType)
	builder.WriteString(", ")
	builder.WriteString("cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cost))
	builder.WriteString(", ")
	builder.WriteString("cooldown=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cooldown))
	builder.WriteString(", ")
	builder.WriteString("requirements=")
	builder.WriteString(_m.Requirements)
	builder.WriteString(", ")
	builder.WriteString("mana_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManaCost))
	builder.WriteString(", ")
	builder.WriteString("stamina_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.StaminaCost))
	builder.WriteString(", ")
	builder.WriteString("hp_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.HpCost))
	builder.WriteByte(')')
	return builder.String()
}

// Abilities is a parsable slice of Ability.
type Abilities []*Ability
