// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"herbst/db/character"
	"herbst/db/skill"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SkillCreate is the builder for creating a Skill entity.
type SkillCreate struct {
	config
	mutation *SkillMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *SkillCreate) SetName(v string) *SkillCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SkillCreate) SetDescription(v string) *SkillCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetSkillType sets the "skill_type" field.
func (_c *SkillCreate) SetSkillType(v string) *SkillCreate {
	_c.mutation.SetSkillType(v)
	return _c
}

// SetCost sets the "cost" field.
func (_c *SkillCreate) SetCost(v int) *SkillCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetCooldown sets the "cooldown" field.
func (_c *SkillCreate) SetCooldown(v int) *SkillCreate {
	_c.mutation.SetCooldown(v)
	return _c
}

// SetRequirements sets the "requirements" field.
func (_c *SkillCreate) SetRequirements(v string) *SkillCreate {
	_c.mutation.SetRequirements(v)
	return _c
}

// SetNillableRequirements sets the "requirements" field if the given value is not nil.
func (_c *SkillCreate) SetNillableRequirements(v *string) *SkillCreate {
	if v != nil {
		_c.SetRequirements(*v)
	}
	return _c
}

// SetEffectType sets the "effect_type" field.
func (_c *SkillCreate) SetEffectType(v string) *SkillCreate {
	_c.mutation.SetEffectType(v)
	return _c
}

// SetEffectValue sets the "effect_value" field.
func (_c *SkillCreate) SetEffectValue(v int) *SkillCreate {
	_c.mutation.SetEffectValue(v)
	return _c
}

// SetEffectDuration sets the "effect_duration" field.
func (_c *SkillCreate) SetEffectDuration(v int) *SkillCreate {
	_c.mutation.SetEffectDuration(v)
	return _c
}

// SetScalingStat sets the "scaling_stat" field.
func (_c *SkillCreate) SetScalingStat(v string) *SkillCreate {
	_c.mutation.SetScalingStat(v)
	return _c
}

// SetNillableScalingStat sets the "scaling_stat" field if the given value is not nil.
func (_c *SkillCreate) SetNillableScalingStat(v *string) *SkillCreate {
	if v != nil {
		_c.SetScalingStat(*v)
	}
	return _c
}

// SetScalingPercentPerPoint sets the "scaling_percent_per_point" field.
func (_c *SkillCreate) SetScalingPercentPerPoint(v float64) *SkillCreate {
	_c.mutation.SetScalingPercentPerPoint(v)
	return _c
}

// SetManaCost sets the "mana_cost" field.
func (_c *SkillCreate) SetManaCost(v int) *SkillCreate {
	_c.mutation.SetManaCost(v)
	return _c
}

// SetStaminaCost sets the "stamina_cost" field.
func (_c *SkillCreate) SetStaminaCost(v int) *SkillCreate {
	_c.mutation.SetStaminaCost(v)
	return _c
}

// SetHpCost sets the "hp_cost" field.
func (_c *SkillCreate) SetHpCost(v int) *SkillCreate {
	_c.mutation.SetHpCost(v)
	return _c
}

// AddCharacterIDs adds the "characters" edge to the Character entity by IDs.
func (_c *SkillCreate) AddCharacterIDs(ids ...int) *SkillCreate {
	_c.mutation.AddCharacterIDs(ids...)
	return _c
}

// AddCharacters adds the "characters" edges to the Character entity.
func (_c *SkillCreate) AddCharacters(v ...*Character) *SkillCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCharacterIDs(ids...)
}

// Mutation returns the SkillMutation object of the builder.
func (_c *SkillCreate) Mutation() *SkillMutation {
	return _c.mutation
}

// Save creates the Skill in the database.
func (_c *SkillCreate) Save(ctx context.Context) (*Skill, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SkillCreate) SaveX(ctx context.Context) *Skill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SkillCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SkillCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SkillCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`db: missing required field "Skill.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`db: missing required field "Skill.description"`)}
	}
	if _, ok := _c.mutation.SkillType(); !ok {
		return &ValidationError{Name: "skill_type", err: errors.New(`db: missing required field "Skill.skill_type"`)}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`db: missing required field "Skill.cost"`)}
	}
	if _, ok := _c.mutation.Cooldown(); !ok {
		return &ValidationError{Name: "cooldown", err: errors.New(`db: missing required field "Skill.cooldown"`)}
	}
	if _, ok := _c.mutation.EffectType(); !ok {
		return &ValidationError{Name: "effect_type", err: errors.New(`db: missing required field "Skill.effect_type"`)}
	}
	if _, ok := _c.mutation.EffectValue(); !ok {
		return &ValidationError{Name: "effect_value", err: errors.New(`db: missing required field "Skill.effect_value"`)}
	}
	if _, ok := _c.mutation.EffectDuration(); !ok {
		return &ValidationError{Name: "effect_duration", err: errors.New(`db: missing required field "Skill.effect_duration"`)}
	}
	if _, ok := _c.mutation.ScalingPercentPerPoint(); !ok {
		return &ValidationError{Name: "scaling_percent_per_point", err: errors.New(`db: missing required field "Skill.scaling_percent_per_point"`)}
	}
	if _, ok := _c.mutation.ManaCost(); !ok {
		return &ValidationError{Name: "mana_cost", err: errors.New(`db: missing required field "Skill.mana_cost"`)}
	}
	if _, ok := _c.mutation.StaminaCost(); !ok {
		return &ValidationError{Name: "stamina_cost", err: errors.New(`db: missing required field "Skill.stamina_cost"`)}
	}
	if _, ok := _c.mutation.HpCost(); !ok {
		return &ValidationError{Name: "hp_cost", err: errors.New(`db: missing required field "Skill.hp_cost"`)}
	}
	return nil
}

func (_c *SkillCreate) sqlSave(ctx context.Context) (*Skill, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SkillCreate) createSpec() (*Skill, *sqlgraph.CreateSpec) {
	var (
		_node = &Skill{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(skill.Table, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(skill.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.SkillType(); ok {
		_spec.SetField(skill.FieldSkillType, field.TypeString, value)
		_node.SkillType = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(skill.FieldCost, field.TypeInt, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.Cooldown(); ok {
		_spec.SetField(skill.FieldCooldown, field.TypeInt, value)
		_node.Cooldown = value
	}
	if value, ok := _c.mutation.Requirements(); ok {
		_spec.SetField(skill.FieldRequirements, field.TypeString, value)
		_node.Requirements = value
	}
	if value, ok := _c.mutation.EffectType(); ok {
		_spec.SetField(skill.FieldEffectType, field.TypeString, value)
		_node.EffectType = value
	}
	if value, ok := _c.mutation.EffectValue(); ok {
		_spec.SetField(skill.FieldEffectValue, field.TypeInt, value)
		_node.EffectValue = value
	}
	if value, ok := _c.mutation.EffectDuration(); ok {
		_spec.SetField(skill.FieldEffectDuration, field.TypeInt, value)
		_node.EffectDuration = value
	}
	if value, ok := _c.mutation.ScalingStat(); ok {
		_spec.SetField(skill.FieldScalingStat, field.TypeString, value)
		_node.ScalingStat = value
	}
	if value, ok := _c.mutation.ScalingPercentPerPoint(); ok {
		_spec.SetField(skill.FieldScalingPercentPerPoint, field.TypeFloat64, value)
		_node.ScalingPercentPerPoint = value
	}
	if value, ok := _c.mutation.ManaCost(); ok {
		_spec.SetField(skill.FieldManaCost, field.TypeInt, value)
		_node.ManaCost = value
	}
	if value, ok := _c.mutation.StaminaCost(); ok {
		_spec.SetField(skill.FieldStaminaCost, field.TypeInt, value)
		_node.StaminaCost = value
	}
	if value, ok := _c.mutation.HpCost(); ok {
		_spec.SetField(skill.FieldHpCost, field.TypeInt, value)
		_node.HpCost = value
	}
	if nodes := _c.mutation.CharactersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.CharactersTable,
			Columns: []string{skill.CharactersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SkillCreateBulk is the builder for creating many Skill entities in bulk.
type SkillCreateBulk struct {
	config
	err      error
	builders []*SkillCreate
}

// Save creates the Skill entities in the database.
func (_c *SkillCreateBulk) Save(ctx context.Context) ([]*Skill, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Skill, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SkillMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SkillCreateBulk) SaveX(ctx context.Context) []*Skill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SkillCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SkillCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
