// Code generated by ent, DO NOT EDIT.

package skill

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the skill type in the database.
	Label = "skill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSkillType holds the string denoting the skill_type field in the database.
	FieldSkillType = "skill_type"
	// FieldCost holds the string denoting the cost field in the database.
	FieldCost = "cost"
	// FieldCooldown holds the string denoting the cooldown field in the database.
	FieldCooldown = "cooldown"
	// FieldRequirements holds the string denoting the requirements field in the database.
	FieldRequirements = "requirements"
	// FieldEffectType holds the string denoting the effect_type field in the database.
	FieldEffectType = "effect_type"
	// FieldEffectValue holds the string denoting the effect_value field in the database.
	FieldEffectValue = "effect_value"
	// FieldEffectDuration holds the string denoting the effect_duration field in the database.
	FieldEffectDuration = "effect_duration"
	// FieldManaCost holds the string denoting the mana_cost field in the database.
	FieldManaCost = "mana_cost"
	// FieldStaminaCost holds the string denoting the stamina_cost field in the database.
	FieldStaminaCost = "stamina_cost"
	// EdgeCharacters holds the string denoting the characters edge name in mutations.
	EdgeCharacters = "characters"
	// Table holds the table name of the skill in the database.
	Table = "skills"
	// CharactersTable is the table that holds the characters relation/edge.
	CharactersTable = "character_skills"
	// CharactersInverseTable is the table name for the CharacterSkill entity.
	// It exists in this package in order to avoid circular dependency with the "characterskill" package.
	CharactersInverseTable = "character_skills"
	// CharactersColumn is the table column denoting the characters relation/edge.
	CharactersColumn = "skill_characters"
)

// Columns holds all SQL columns for skill fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldSkillType,
	FieldCost,
	FieldCooldown,
	FieldRequirements,
	FieldEffectType,
	FieldEffectValue,
	FieldEffectDuration,
	FieldManaCost,
	FieldStaminaCost,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCost holds the default value on creation for the "cost" field.
	DefaultCost int
	// DefaultCooldown holds the default value on creation for the "cooldown" field.
	DefaultCooldown int
	// DefaultEffectType holds the default value on creation for the "effect_type" field.
	DefaultEffectType string
	// DefaultEffectValue holds the default value on creation for the "effect_value" field.
	DefaultEffectValue int
	// DefaultEffectDuration holds the default value on creation for the "effect_duration" field.
	DefaultEffectDuration int
	// DefaultManaCost holds the default value on creation for the "mana_cost" field.
	DefaultManaCost int
	// DefaultStaminaCost holds the default value on creation for the "stamina_cost" field.
	DefaultStaminaCost int
)

// OrderOption defines the ordering options for the Skill queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySkillType orders the results by the skill_type field.
func BySkillType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillType, opts...).ToFunc()
}

// ByCost orders the results by the cost field.
func ByCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCost, opts...).ToFunc()
}

// ByCooldown orders the results by the cooldown field.
func ByCooldown(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldown, opts...).ToFunc()
}

// ByRequirements orders the results by the requirements field.
func ByRequirements(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequirements, opts...).ToFunc()
}

// ByEffectType orders the results by the effect_type field.
func ByEffectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectType, opts...).ToFunc()
}

// ByEffectValue orders the results by the effect_value field.
func ByEffectValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectValue, opts...).ToFunc()
}

// ByEffectDuration orders the results by the effect_duration field.
func ByEffectDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectDuration, opts...).ToFunc()
}

// ByManaCost orders the results by the mana_cost field.
func ByManaCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManaCost, opts...).ToFunc()
}

// ByStaminaCost orders the results by the stamina_cost field.
func ByStaminaCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStaminaCost, opts...).ToFunc()
}

// ByCharactersCount orders the results by characters count.
func ByCharactersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCharactersStep(), opts...)
	}
}

// ByCharacters orders the results by characters terms.
func ByCharacters(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCharactersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCharactersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CharactersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CharactersTable, CharactersColumn),
	)
}
