// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"herbst-server/db/character"
	"herbst-server/db/predicate"
	"herbst-server/db/room"
	"herbst-server/db/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CharacterUpdate is the builder for updating Character entities.
type CharacterUpdate struct {
	config
	hooks    []Hook
	mutation *CharacterMutation
}

// Where appends a list predicates to the CharacterUpdate builder.
func (_u *CharacterUpdate) Where(ps ...predicate.Character) *CharacterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CharacterUpdate) SetName(v string) *CharacterUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableName(v *string) *CharacterUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *CharacterUpdate) SetPassword(v string) *CharacterUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillablePassword(v *string) *CharacterUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *CharacterUpdate) ClearPassword() *CharacterUpdate {
	_u.mutation.ClearPassword()
	return _u
}

// SetIsNPC sets the "isNPC" field.
func (_u *CharacterUpdate) SetIsNPC(v bool) *CharacterUpdate {
	_u.mutation.SetIsNPC(v)
	return _u
}

// SetNillableIsNPC sets the "isNPC" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableIsNPC(v *bool) *CharacterUpdate {
	if v != nil {
		_u.SetIsNPC(*v)
	}
	return _u
}

// SetCurrentRoomId sets the "currentRoomId" field.
func (_u *CharacterUpdate) SetCurrentRoomId(v int) *CharacterUpdate {
	_u.mutation.SetCurrentRoomId(v)
	return _u
}

// SetNillableCurrentRoomId sets the "currentRoomId" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableCurrentRoomId(v *int) *CharacterUpdate {
	if v != nil {
		_u.SetCurrentRoomId(*v)
	}
	return _u
}

// SetStartingRoomId sets the "startingRoomId" field.
func (_u *CharacterUpdate) SetStartingRoomId(v int) *CharacterUpdate {
	_u.mutation.ResetStartingRoomId()
	_u.mutation.SetStartingRoomId(v)
	return _u
}

// SetNillableStartingRoomId sets the "startingRoomId" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableStartingRoomId(v *int) *CharacterUpdate {
	if v != nil {
		_u.SetStartingRoomId(*v)
	}
	return _u
}

// AddStartingRoomId adds value to the "startingRoomId" field.
func (_u *CharacterUpdate) AddStartingRoomId(v int) *CharacterUpdate {
	_u.mutation.AddStartingRoomId(v)
	return _u
}

// SetIsAdmin sets the "is_admin" field.
func (_u *CharacterUpdate) SetIsAdmin(v bool) *CharacterUpdate {
	_u.mutation.SetIsAdmin(v)
	return _u
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableIsAdmin(v *bool) *CharacterUpdate {
	if v != nil {
		_u.SetIsAdmin(*v)
	}
	return _u
}

// SetHitpoints sets the "hitpoints" field.
func (_u *CharacterUpdate) SetHitpoints(v int) *CharacterUpdate {
	_u.mutation.ResetHitpoints()
	_u.mutation.SetHitpoints(v)
	return _u
}

// SetNillableHitpoints sets the "hitpoints" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableHitpoints(v *int) *CharacterUpdate {
	if v != nil {
		_u.SetHitpoints(*v)
	}
	return _u
}

// AddHitpoints adds value to the "hitpoints" field.
func (_u *CharacterUpdate) AddHitpoints(v int) *CharacterUpdate {
	_u.mutation.AddHitpoints(v)
	return _u
}

// SetMaxHitpoints sets the "max_hitpoints" field.
func (_u *CharacterUpdate) SetMaxHitpoints(v int) *CharacterUpdate {
	_u.mutation.ResetMaxHitpoints()
	_u.mutation.SetMaxHitpoints(v)
	return _u
}

// SetNillableMaxHitpoints sets the "max_hitpoints" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableMaxHitpoints(v *int) *CharacterUpdate {
	if v != nil {
		_u.SetMaxHitpoints(*v)
	}
	return _u
}

// AddMaxHitpoints adds value to the "max_hitpoints" field.
func (_u *CharacterUpdate) AddMaxHitpoints(v int) *CharacterUpdate {
	_u.mutation.AddMaxHitpoints(v)
	return _u
}

// SetStamina sets the "stamina" field.
func (_u *CharacterUpdate) SetStamina(v int) *CharacterUpdate {
	_u.mutation.ResetStamina()
	_u.mutation.SetStamina(v)
	return _u
}

// SetNillableStamina sets the "stamina" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableStamina(v *int) *CharacterUpdate {
	if v != nil {
		_u.SetStamina(*v)
	}
	return _u
}

// AddStamina adds value to the "stamina" field.
func (_u *CharacterUpdate) AddStamina(v int) *CharacterUpdate {
	_u.mutation.AddStamina(v)
	return _u
}

// SetMaxStamina sets the "max_stamina" field.
func (_u *CharacterUpdate) SetMaxStamina(v int) *CharacterUpdate {
	_u.mutation.ResetMaxStamina()
	_u.mutation.SetMaxStamina(v)
	return _u
}

// SetNillableMaxStamina sets the "max_stamina" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableMaxStamina(v *int) *CharacterUpdate {
	if v != nil {
		_u.SetMaxStamina(*v)
	}
	return _u
}

// AddMaxStamina adds value to the "max_stamina" field.
func (_u *CharacterUpdate) AddMaxStamina(v int) *CharacterUpdate {
	_u.mutation.AddMaxStamina(v)
	return _u
}

// SetMana sets the "mana" field.
func (_u *CharacterUpdate) SetMana(v int) *CharacterUpdate {
	_u.mutation.ResetMana()
	_u.mutation.SetMana(v)
	return _u
}

// SetNillableMana sets the "mana" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableMana(v *int) *CharacterUpdate {
	if v != nil {
		_u.SetMana(*v)
	}
	return _u
}

// AddMana adds value to the "mana" field.
func (_u *CharacterUpdate) AddMana(v int) *CharacterUpdate {
	_u.mutation.AddMana(v)
	return _u
}

// SetMaxMana sets the "max_mana" field.
func (_u *CharacterUpdate) SetMaxMana(v int) *CharacterUpdate {
	_u.mutation.ResetMaxMana()
	_u.mutation.SetMaxMana(v)
	return _u
}

// SetNillableMaxMana sets the "max_mana" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableMaxMana(v *int) *CharacterUpdate {
	if v != nil {
		_u.SetMaxMana(*v)
	}
	return _u
}

// AddMaxMana adds value to the "max_mana" field.
func (_u *CharacterUpdate) AddMaxMana(v int) *CharacterUpdate {
	_u.mutation.AddMaxMana(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *CharacterUpdate) SetUserID(id int) *CharacterUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *CharacterUpdate) SetNillableUserID(id *int) *CharacterUpdate {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CharacterUpdate) SetUser(v *User) *CharacterUpdate {
	return _u.SetUserID(v.ID)
}

// SetRoomID sets the "room" edge to the Room entity by ID.
func (_u *CharacterUpdate) SetRoomID(id int) *CharacterUpdate {
	_u.mutation.SetRoomID(id)
	return _u
}

// SetRoom sets the "room" edge to the Room entity.
func (_u *CharacterUpdate) SetRoom(v *Room) *CharacterUpdate {
	return _u.SetRoomID(v.ID)
}

// Mutation returns the CharacterMutation object of the builder.
func (_u *CharacterUpdate) Mutation() *CharacterMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CharacterUpdate) ClearUser() *CharacterUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearRoom clears the "room" edge to the Room entity.
func (_u *CharacterUpdate) ClearRoom() *CharacterUpdate {
	_u.mutation.ClearRoom()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CharacterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CharacterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CharacterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CharacterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CharacterUpdate) check() error {
	if _u.mutation.RoomCleared() && len(_u.mutation.RoomIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "Character.room"`)
	}
	return nil
}

func (_u *CharacterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(character.Table, character.Columns, sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(character.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(character.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(character.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.IsNPC(); ok {
		_spec.SetField(character.FieldIsNPC, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartingRoomId(); ok {
		_spec.SetField(character.FieldStartingRoomId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartingRoomId(); ok {
		_spec.AddField(character.FieldStartingRoomId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsAdmin(); ok {
		_spec.SetField(character.FieldIsAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Hitpoints(); ok {
		_spec.SetField(character.FieldHitpoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHitpoints(); ok {
		_spec.AddField(character.FieldHitpoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxHitpoints(); ok {
		_spec.SetField(character.FieldMaxHitpoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxHitpoints(); ok {
		_spec.AddField(character.FieldMaxHitpoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Stamina(); ok {
		_spec.SetField(character.FieldStamina, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStamina(); ok {
		_spec.AddField(character.FieldStamina, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxStamina(); ok {
		_spec.SetField(character.FieldMaxStamina, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxStamina(); ok {
		_spec.AddField(character.FieldMaxStamina, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Mana(); ok {
		_spec.SetField(character.FieldMana, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMana(); ok {
		_spec.AddField(character.FieldMana, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxMana(); ok {
		_spec.SetField(character.FieldMaxMana, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxMana(); ok {
		_spec.AddField(character.FieldMaxMana, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   character.UserTable,
			Columns: []string{character.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   character.UserTable,
			Columns: []string{character.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   character.RoomTable,
			Columns: []string{character.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   character.RoomTable,
			Columns: []string{character.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{character.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CharacterUpdateOne is the builder for updating a single Character entity.
type CharacterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CharacterMutation
}

// SetName sets the "name" field.
func (_u *CharacterUpdateOne) SetName(v string) *CharacterUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableName(v *string) *CharacterUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *CharacterUpdateOne) SetPassword(v string) *CharacterUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillablePassword(v *string) *CharacterUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *CharacterUpdateOne) ClearPassword() *CharacterUpdateOne {
	_u.mutation.ClearPassword()
	return _u
}

// SetIsNPC sets the "isNPC" field.
func (_u *CharacterUpdateOne) SetIsNPC(v bool) *CharacterUpdateOne {
	_u.mutation.SetIsNPC(v)
	return _u
}

// SetNillableIsNPC sets the "isNPC" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableIsNPC(v *bool) *CharacterUpdateOne {
	if v != nil {
		_u.SetIsNPC(*v)
	}
	return _u
}

// SetCurrentRoomId sets the "currentRoomId" field.
func (_u *CharacterUpdateOne) SetCurrentRoomId(v int) *CharacterUpdateOne {
	_u.mutation.SetCurrentRoomId(v)
	return _u
}

// SetNillableCurrentRoomId sets the "currentRoomId" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableCurrentRoomId(v *int) *CharacterUpdateOne {
	if v != nil {
		_u.SetCurrentRoomId(*v)
	}
	return _u
}

// SetStartingRoomId sets the "startingRoomId" field.
func (_u *CharacterUpdateOne) SetStartingRoomId(v int) *CharacterUpdateOne {
	_u.mutation.ResetStartingRoomId()
	_u.mutation.SetStartingRoomId(v)
	return _u
}

// SetNillableStartingRoomId sets the "startingRoomId" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableStartingRoomId(v *int) *CharacterUpdateOne {
	if v != nil {
		_u.SetStartingRoomId(*v)
	}
	return _u
}

// AddStartingRoomId adds value to the "startingRoomId" field.
func (_u *CharacterUpdateOne) AddStartingRoomId(v int) *CharacterUpdateOne {
	_u.mutation.AddStartingRoomId(v)
	return _u
}

// SetIsAdmin sets the "is_admin" field.
func (_u *CharacterUpdateOne) SetIsAdmin(v bool) *CharacterUpdateOne {
	_u.mutation.SetIsAdmin(v)
	return _u
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableIsAdmin(v *bool) *CharacterUpdateOne {
	if v != nil {
		_u.SetIsAdmin(*v)
	}
	return _u
}

// SetHitpoints sets the "hitpoints" field.
func (_u *CharacterUpdateOne) SetHitpoints(v int) *CharacterUpdateOne {
	_u.mutation.ResetHitpoints()
	_u.mutation.SetHitpoints(v)
	return _u
}

// SetNillableHitpoints sets the "hitpoints" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableHitpoints(v *int) *CharacterUpdateOne {
	if v != nil {
		_u.SetHitpoints(*v)
	}
	return _u
}

// AddHitpoints adds value to the "hitpoints" field.
func (_u *CharacterUpdateOne) AddHitpoints(v int) *CharacterUpdateOne {
	_u.mutation.AddHitpoints(v)
	return _u
}

// SetMaxHitpoints sets the "max_hitpoints" field.
func (_u *CharacterUpdateOne) SetMaxHitpoints(v int) *CharacterUpdateOne {
	_u.mutation.ResetMaxHitpoints()
	_u.mutation.SetMaxHitpoints(v)
	return _u
}

// SetNillableMaxHitpoints sets the "max_hitpoints" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableMaxHitpoints(v *int) *CharacterUpdateOne {
	if v != nil {
		_u.SetMaxHitpoints(*v)
	}
	return _u
}

// AddMaxHitpoints adds value to the "max_hitpoints" field.
func (_u *CharacterUpdateOne) AddMaxHitpoints(v int) *CharacterUpdateOne {
	_u.mutation.AddMaxHitpoints(v)
	return _u
}

// SetStamina sets the "stamina" field.
func (_u *CharacterUpdateOne) SetStamina(v int) *CharacterUpdateOne {
	_u.mutation.ResetStamina()
	_u.mutation.SetStamina(v)
	return _u
}

// SetNillableStamina sets the "stamina" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableStamina(v *int) *CharacterUpdateOne {
	if v != nil {
		_u.SetStamina(*v)
	}
	return _u
}

// AddStamina adds value to the "stamina" field.
func (_u *CharacterUpdateOne) AddStamina(v int) *CharacterUpdateOne {
	_u.mutation.AddStamina(v)
	return _u
}

// SetMaxStamina sets the "max_stamina" field.
func (_u *CharacterUpdateOne) SetMaxStamina(v int) *CharacterUpdateOne {
	_u.mutation.ResetMaxStamina()
	_u.mutation.SetMaxStamina(v)
	return _u
}

// SetNillableMaxStamina sets the "max_stamina" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableMaxStamina(v *int) *CharacterUpdateOne {
	if v != nil {
		_u.SetMaxStamina(*v)
	}
	return _u
}

// AddMaxStamina adds value to the "max_stamina" field.
func (_u *CharacterUpdateOne) AddMaxStamina(v int) *CharacterUpdateOne {
	_u.mutation.AddMaxStamina(v)
	return _u
}

// SetMana sets the "mana" field.
func (_u *CharacterUpdateOne) SetMana(v int) *CharacterUpdateOne {
	_u.mutation.ResetMana()
	_u.mutation.SetMana(v)
	return _u
}

// SetNillableMana sets the "mana" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableMana(v *int) *CharacterUpdateOne {
	if v != nil {
		_u.SetMana(*v)
	}
	return _u
}

// AddMana adds value to the "mana" field.
func (_u *CharacterUpdateOne) AddMana(v int) *CharacterUpdateOne {
	_u.mutation.AddMana(v)
	return _u
}

// SetMaxMana sets the "max_mana" field.
func (_u *CharacterUpdateOne) SetMaxMana(v int) *CharacterUpdateOne {
	_u.mutation.ResetMaxMana()
	_u.mutation.SetMaxMana(v)
	return _u
}

// SetNillableMaxMana sets the "max_mana" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableMaxMana(v *int) *CharacterUpdateOne {
	if v != nil {
		_u.SetMaxMana(*v)
	}
	return _u
}

// AddMaxMana adds value to the "max_mana" field.
func (_u *CharacterUpdateOne) AddMaxMana(v int) *CharacterUpdateOne {
	_u.mutation.AddMaxMana(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *CharacterUpdateOne) SetUserID(id int) *CharacterUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableUserID(id *int) *CharacterUpdateOne {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CharacterUpdateOne) SetUser(v *User) *CharacterUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetRoomID sets the "room" edge to the Room entity by ID.
func (_u *CharacterUpdateOne) SetRoomID(id int) *CharacterUpdateOne {
	_u.mutation.SetRoomID(id)
	return _u
}

// SetRoom sets the "room" edge to the Room entity.
func (_u *CharacterUpdateOne) SetRoom(v *Room) *CharacterUpdateOne {
	return _u.SetRoomID(v.ID)
}

// Mutation returns the CharacterMutation object of the builder.
func (_u *CharacterUpdateOne) Mutation() *CharacterMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CharacterUpdateOne) ClearUser() *CharacterUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearRoom clears the "room" edge to the Room entity.
func (_u *CharacterUpdateOne) ClearRoom() *CharacterUpdateOne {
	_u.mutation.ClearRoom()
	return _u
}

// Where appends a list predicates to the CharacterUpdate builder.
func (_u *CharacterUpdateOne) Where(ps ...predicate.Character) *CharacterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CharacterUpdateOne) Select(field string, fields ...string) *CharacterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Character entity.
func (_u *CharacterUpdateOne) Save(ctx context.Context) (*Character, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CharacterUpdateOne) SaveX(ctx context.Context) *Character {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CharacterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CharacterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CharacterUpdateOne) check() error {
	if _u.mutation.RoomCleared() && len(_u.mutation.RoomIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "Character.room"`)
	}
	return nil
}

func (_u *CharacterUpdateOne) sqlSave(ctx context.Context) (_node *Character, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(character.Table, character.Columns, sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "Character.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, character.FieldID)
		for _, f := range fields {
			if !character.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != character.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(character.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(character.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(character.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.IsNPC(); ok {
		_spec.SetField(character.FieldIsNPC, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartingRoomId(); ok {
		_spec.SetField(character.FieldStartingRoomId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartingRoomId(); ok {
		_spec.AddField(character.FieldStartingRoomId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsAdmin(); ok {
		_spec.SetField(character.FieldIsAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Hitpoints(); ok {
		_spec.SetField(character.FieldHitpoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHitpoints(); ok {
		_spec.AddField(character.FieldHitpoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxHitpoints(); ok {
		_spec.SetField(character.FieldMaxHitpoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxHitpoints(); ok {
		_spec.AddField(character.FieldMaxHitpoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Stamina(); ok {
		_spec.SetField(character.FieldStamina, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStamina(); ok {
		_spec.AddField(character.FieldStamina, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxStamina(); ok {
		_spec.SetField(character.FieldMaxStamina, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxStamina(); ok {
		_spec.AddField(character.FieldMaxStamina, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Mana(); ok {
		_spec.SetField(character.FieldMana, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMana(); ok {
		_spec.AddField(character.FieldMana, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxMana(); ok {
		_spec.SetField(character.FieldMaxMana, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxMana(); ok {
		_spec.AddField(character.FieldMaxMana, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   character.UserTable,
			Columns: []string{character.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   character.UserTable,
			Columns: []string{character.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   character.RoomTable,
			Columns: []string{character.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   character.RoomTable,
			Columns: []string{character.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Character{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{character.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
