// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"herbst-server/db/character"
	"herbst-server/db/characterchannel"
	"herbst-server/db/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CharacterChannelQuery is the builder for querying CharacterChannel entities.
type CharacterChannelQuery struct {
	config
	ctx           *QueryContext
	order         []characterchannel.OrderOption
	inters        []Interceptor
	predicates    []predicate.CharacterChannel
	withCharacter *CharacterQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CharacterChannelQuery builder.
func (_q *CharacterChannelQuery) Where(ps ...predicate.CharacterChannel) *CharacterChannelQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CharacterChannelQuery) Limit(limit int) *CharacterChannelQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CharacterChannelQuery) Offset(offset int) *CharacterChannelQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CharacterChannelQuery) Unique(unique bool) *CharacterChannelQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CharacterChannelQuery) Order(o ...characterchannel.OrderOption) *CharacterChannelQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCharacter chains the current query on the "character" edge.
func (_q *CharacterChannelQuery) QueryCharacter() *CharacterQuery {
	query := (&CharacterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(characterchannel.Table, characterchannel.FieldID, selector),
			sqlgraph.To(character.Table, character.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, characterchannel.CharacterTable, characterchannel.CharacterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CharacterChannel entity from the query.
// Returns a *NotFoundError when no CharacterChannel was found.
func (_q *CharacterChannelQuery) First(ctx context.Context) (*CharacterChannel, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{characterchannel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CharacterChannelQuery) FirstX(ctx context.Context) *CharacterChannel {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CharacterChannel ID from the query.
// Returns a *NotFoundError when no CharacterChannel ID was found.
func (_q *CharacterChannelQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{characterchannel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CharacterChannelQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CharacterChannel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CharacterChannel entity is found.
// Returns a *NotFoundError when no CharacterChannel entities are found.
func (_q *CharacterChannelQuery) Only(ctx context.Context) (*CharacterChannel, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{characterchannel.Label}
	default:
		return nil, &NotSingularError{characterchannel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CharacterChannelQuery) OnlyX(ctx context.Context) *CharacterChannel {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CharacterChannel ID in the query.
// Returns a *NotSingularError when more than one CharacterChannel ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CharacterChannelQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{characterchannel.Label}
	default:
		err = &NotSingularError{characterchannel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CharacterChannelQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CharacterChannels.
func (_q *CharacterChannelQuery) All(ctx context.Context) ([]*CharacterChannel, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CharacterChannel, *CharacterChannelQuery]()
	return withInterceptors[[]*CharacterChannel](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CharacterChannelQuery) AllX(ctx context.Context) []*CharacterChannel {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CharacterChannel IDs.
func (_q *CharacterChannelQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(characterchannel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CharacterChannelQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CharacterChannelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CharacterChannelQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CharacterChannelQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CharacterChannelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CharacterChannelQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CharacterChannelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CharacterChannelQuery) Clone() *CharacterChannelQuery {
	if _q == nil {
		return nil
	}
	return &CharacterChannelQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]characterchannel.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.CharacterChannel{}, _q.predicates...),
		withCharacter: _q.withCharacter.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCharacter tells the query-builder to eager-load the nodes that are connected to
// the "character" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CharacterChannelQuery) WithCharacter(opts ...func(*CharacterQuery)) *CharacterChannelQuery {
	query := (&CharacterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCharacter = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ChatEnabled bool `json:"chatEnabled,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CharacterChannel.Query().
//		GroupBy(characterchannel.FieldChatEnabled).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (_q *CharacterChannelQuery) GroupBy(field string, fields ...string) *CharacterChannelGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CharacterChannelGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = characterchannel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ChatEnabled bool `json:"chatEnabled,omitempty"`
//	}
//
//	client.CharacterChannel.Query().
//		Select(characterchannel.FieldChatEnabled).
//		Scan(ctx, &v)
func (_q *CharacterChannelQuery) Select(fields ...string) *CharacterChannelSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CharacterChannelSelect{CharacterChannelQuery: _q}
	sbuild.label = characterchannel.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CharacterChannelSelect configured with the given aggregations.
func (_q *CharacterChannelQuery) Aggregate(fns ...AggregateFunc) *CharacterChannelSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CharacterChannelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !characterchannel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CharacterChannelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CharacterChannel, error) {
	var (
		nodes       = []*CharacterChannel{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withCharacter != nil,
		}
	)
	if _q.withCharacter != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, characterchannel.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CharacterChannel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CharacterChannel{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCharacter; query != nil {
		if err := _q.loadCharacter(ctx, query, nodes, nil,
			func(n *CharacterChannel, e *Character) { n.Edges.Character = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CharacterChannelQuery) loadCharacter(ctx context.Context, query *CharacterQuery, nodes []*CharacterChannel, init func(*CharacterChannel), assign func(*CharacterChannel, *Character)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CharacterChannel)
	for i := range nodes {
		if nodes[i].character_channel_settings == nil {
			continue
		}
		fk := *nodes[i].character_channel_settings
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(character.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "character_channel_settings" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CharacterChannelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CharacterChannelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(characterchannel.Table, characterchannel.Columns, sqlgraph.NewFieldSpec(characterchannel.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, characterchannel.FieldID)
		for i := range fields {
			if fields[i] != characterchannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CharacterChannelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(characterchannel.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = characterchannel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CharacterChannelGroupBy is the group-by builder for CharacterChannel entities.
type CharacterChannelGroupBy struct {
	selector
	build *CharacterChannelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CharacterChannelGroupBy) Aggregate(fns ...AggregateFunc) *CharacterChannelGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CharacterChannelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CharacterChannelQuery, *CharacterChannelGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CharacterChannelGroupBy) sqlScan(ctx context.Context, root *CharacterChannelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CharacterChannelSelect is the builder for selecting fields of CharacterChannel entities.
type CharacterChannelSelect struct {
	*CharacterChannelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CharacterChannelSelect) Aggregate(fns ...AggregateFunc) *CharacterChannelSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CharacterChannelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CharacterChannelQuery, *CharacterChannelSelect](ctx, _s.CharacterChannelQuery, _s, _s.inters, v)
}

func (_s *CharacterChannelSelect) sqlScan(ctx context.Context, root *CharacterChannelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
