// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"herbst-server/db/character"
	"herbst-server/db/characterclasshistory"
	"herbst-server/db/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CharacterClassHistoryUpdate is the builder for updating CharacterClassHistory entities.
type CharacterClassHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *CharacterClassHistoryMutation
}

// Where appends a list predicates to the CharacterClassHistoryUpdate builder.
func (_u *CharacterClassHistoryUpdate) Where(ps ...predicate.CharacterClassHistory) *CharacterClassHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *CharacterClassHistoryUpdate) SetCharacterID(v int) *CharacterClassHistoryUpdate {
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *CharacterClassHistoryUpdate) SetNillableCharacterID(v *int) *CharacterClassHistoryUpdate {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// SetFactionID sets the "faction_id" field.
func (_u *CharacterClassHistoryUpdate) SetFactionID(v int) *CharacterClassHistoryUpdate {
	_u.mutation.ResetFactionID()
	_u.mutation.SetFactionID(v)
	return _u
}

// SetNillableFactionID sets the "faction_id" field if the given value is not nil.
func (_u *CharacterClassHistoryUpdate) SetNillableFactionID(v *int) *CharacterClassHistoryUpdate {
	if v != nil {
		_u.SetFactionID(*v)
	}
	return _u
}

// AddFactionID adds value to the "faction_id" field.
func (_u *CharacterClassHistoryUpdate) AddFactionID(v int) *CharacterClassHistoryUpdate {
	_u.mutation.AddFactionID(v)
	return _u
}

// SetFactionName sets the "faction_name" field.
func (_u *CharacterClassHistoryUpdate) SetFactionName(v string) *CharacterClassHistoryUpdate {
	_u.mutation.SetFactionName(v)
	return _u
}

// SetNillableFactionName sets the "faction_name" field if the given value is not nil.
func (_u *CharacterClassHistoryUpdate) SetNillableFactionName(v *string) *CharacterClassHistoryUpdate {
	if v != nil {
		_u.SetFactionName(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *CharacterClassHistoryUpdate) SetJoinedAt(v time.Time) *CharacterClassHistoryUpdate {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *CharacterClassHistoryUpdate) SetNillableJoinedAt(v *time.Time) *CharacterClassHistoryUpdate {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetLeftAt sets the "left_at" field.
func (_u *CharacterClassHistoryUpdate) SetLeftAt(v time.Time) *CharacterClassHistoryUpdate {
	_u.mutation.SetLeftAt(v)
	return _u
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (_u *CharacterClassHistoryUpdate) SetNillableLeftAt(v *time.Time) *CharacterClassHistoryUpdate {
	if v != nil {
		_u.SetLeftAt(*v)
	}
	return _u
}

// ClearLeftAt clears the value of the "left_at" field.
func (_u *CharacterClassHistoryUpdate) ClearLeftAt() *CharacterClassHistoryUpdate {
	_u.mutation.ClearLeftAt()
	return _u
}

// SetReason sets the "reason" field.
func (_u *CharacterClassHistoryUpdate) SetReason(v string) *CharacterClassHistoryUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *CharacterClassHistoryUpdate) SetNillableReason(v *string) *CharacterClassHistoryUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *CharacterClassHistoryUpdate) ClearReason() *CharacterClassHistoryUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetCharacter sets the "character" edge to the Character entity.
func (_u *CharacterClassHistoryUpdate) SetCharacter(v *Character) *CharacterClassHistoryUpdate {
	return _u.SetCharacterID(v.ID)
}

// Mutation returns the CharacterClassHistoryMutation object of the builder.
func (_u *CharacterClassHistoryUpdate) Mutation() *CharacterClassHistoryMutation {
	return _u.mutation
}

// ClearCharacter clears the "character" edge to the Character entity.
func (_u *CharacterClassHistoryUpdate) ClearCharacter() *CharacterClassHistoryUpdate {
	_u.mutation.ClearCharacter()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CharacterClassHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CharacterClassHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CharacterClassHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CharacterClassHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CharacterClassHistoryUpdate) check() error {
	if _u.mutation.CharacterCleared() && len(_u.mutation.CharacterIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "CharacterClassHistory.character"`)
	}
	return nil
}

func (_u *CharacterClassHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(characterclasshistory.Table, characterclasshistory.Columns, sqlgraph.NewFieldSpec(characterclasshistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FactionID(); ok {
		_spec.SetField(characterclasshistory.FieldFactionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFactionID(); ok {
		_spec.AddField(characterclasshistory.FieldFactionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FactionName(); ok {
		_spec.SetField(characterclasshistory.FieldFactionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(characterclasshistory.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeftAt(); ok {
		_spec.SetField(characterclasshistory.FieldLeftAt, field.TypeTime, value)
	}
	if _u.mutation.LeftAtCleared() {
		_spec.ClearField(characterclasshistory.FieldLeftAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(characterclasshistory.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(characterclasshistory.FieldReason, field.TypeString)
	}
	if _u.mutation.CharacterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   characterclasshistory.CharacterTable,
			Columns: []string{characterclasshistory.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   characterclasshistory.CharacterTable,
			Columns: []string{characterclasshistory.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{characterclasshistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CharacterClassHistoryUpdateOne is the builder for updating a single CharacterClassHistory entity.
type CharacterClassHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CharacterClassHistoryMutation
}

// SetCharacterID sets the "character_id" field.
func (_u *CharacterClassHistoryUpdateOne) SetCharacterID(v int) *CharacterClassHistoryUpdateOne {
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *CharacterClassHistoryUpdateOne) SetNillableCharacterID(v *int) *CharacterClassHistoryUpdateOne {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// SetFactionID sets the "faction_id" field.
func (_u *CharacterClassHistoryUpdateOne) SetFactionID(v int) *CharacterClassHistoryUpdateOne {
	_u.mutation.ResetFactionID()
	_u.mutation.SetFactionID(v)
	return _u
}

// SetNillableFactionID sets the "faction_id" field if the given value is not nil.
func (_u *CharacterClassHistoryUpdateOne) SetNillableFactionID(v *int) *CharacterClassHistoryUpdateOne {
	if v != nil {
		_u.SetFactionID(*v)
	}
	return _u
}

// AddFactionID adds value to the "faction_id" field.
func (_u *CharacterClassHistoryUpdateOne) AddFactionID(v int) *CharacterClassHistoryUpdateOne {
	_u.mutation.AddFactionID(v)
	return _u
}

// SetFactionName sets the "faction_name" field.
func (_u *CharacterClassHistoryUpdateOne) SetFactionName(v string) *CharacterClassHistoryUpdateOne {
	_u.mutation.SetFactionName(v)
	return _u
}

// SetNillableFactionName sets the "faction_name" field if the given value is not nil.
func (_u *CharacterClassHistoryUpdateOne) SetNillableFactionName(v *string) *CharacterClassHistoryUpdateOne {
	if v != nil {
		_u.SetFactionName(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *CharacterClassHistoryUpdateOne) SetJoinedAt(v time.Time) *CharacterClassHistoryUpdateOne {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *CharacterClassHistoryUpdateOne) SetNillableJoinedAt(v *time.Time) *CharacterClassHistoryUpdateOne {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetLeftAt sets the "left_at" field.
func (_u *CharacterClassHistoryUpdateOne) SetLeftAt(v time.Time) *CharacterClassHistoryUpdateOne {
	_u.mutation.SetLeftAt(v)
	return _u
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (_u *CharacterClassHistoryUpdateOne) SetNillableLeftAt(v *time.Time) *CharacterClassHistoryUpdateOne {
	if v != nil {
		_u.SetLeftAt(*v)
	}
	return _u
}

// ClearLeftAt clears the value of the "left_at" field.
func (_u *CharacterClassHistoryUpdateOne) ClearLeftAt() *CharacterClassHistoryUpdateOne {
	_u.mutation.ClearLeftAt()
	return _u
}

// SetReason sets the "reason" field.
func (_u *CharacterClassHistoryUpdateOne) SetReason(v string) *CharacterClassHistoryUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *CharacterClassHistoryUpdateOne) SetNillableReason(v *string) *CharacterClassHistoryUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *CharacterClassHistoryUpdateOne) ClearReason() *CharacterClassHistoryUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetCharacter sets the "character" edge to the Character entity.
func (_u *CharacterClassHistoryUpdateOne) SetCharacter(v *Character) *CharacterClassHistoryUpdateOne {
	return _u.SetCharacterID(v.ID)
}

// Mutation returns the CharacterClassHistoryMutation object of the builder.
func (_u *CharacterClassHistoryUpdateOne) Mutation() *CharacterClassHistoryMutation {
	return _u.mutation
}

// ClearCharacter clears the "character" edge to the Character entity.
func (_u *CharacterClassHistoryUpdateOne) ClearCharacter() *CharacterClassHistoryUpdateOne {
	_u.mutation.ClearCharacter()
	return _u
}

// Where appends a list predicates to the CharacterClassHistoryUpdate builder.
func (_u *CharacterClassHistoryUpdateOne) Where(ps ...predicate.CharacterClassHistory) *CharacterClassHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CharacterClassHistoryUpdateOne) Select(field string, fields ...string) *CharacterClassHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CharacterClassHistory entity.
func (_u *CharacterClassHistoryUpdateOne) Save(ctx context.Context) (*CharacterClassHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CharacterClassHistoryUpdateOne) SaveX(ctx context.Context) *CharacterClassHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CharacterClassHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CharacterClassHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CharacterClassHistoryUpdateOne) check() error {
	if _u.mutation.CharacterCleared() && len(_u.mutation.CharacterIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "CharacterClassHistory.character"`)
	}
	return nil
}

func (_u *CharacterClassHistoryUpdateOne) sqlSave(ctx context.Context) (_node *CharacterClassHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(characterclasshistory.Table, characterclasshistory.Columns, sqlgraph.NewFieldSpec(characterclasshistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "CharacterClassHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, characterclasshistory.FieldID)
		for _, f := range fields {
			if !characterclasshistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != characterclasshistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FactionID(); ok {
		_spec.SetField(characterclasshistory.FieldFactionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFactionID(); ok {
		_spec.AddField(characterclasshistory.FieldFactionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FactionName(); ok {
		_spec.SetField(characterclasshistory.FieldFactionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(characterclasshistory.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeftAt(); ok {
		_spec.SetField(characterclasshistory.FieldLeftAt, field.TypeTime, value)
	}
	if _u.mutation.LeftAtCleared() {
		_spec.ClearField(characterclasshistory.FieldLeftAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(characterclasshistory.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(characterclasshistory.FieldReason, field.TypeString)
	}
	if _u.mutation.CharacterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   characterclasshistory.CharacterTable,
			Columns: []string{characterclasshistory.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   characterclasshistory.CharacterTable,
			Columns: []string{characterclasshistory.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CharacterClassHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{characterclasshistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
