// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"herbst-server/db/character"
	"herbst-server/db/characterignore"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CharacterIgnoreCreate is the builder for creating a CharacterIgnore entity.
type CharacterIgnoreCreate struct {
	config
	mutation *CharacterIgnoreMutation
	hooks    []Hook
}

// SetIgnoredCharacterId sets the "ignoredCharacterId" field.
func (_c *CharacterIgnoreCreate) SetIgnoredCharacterId(v int) *CharacterIgnoreCreate {
	_c.mutation.SetIgnoredCharacterId(v)
	return _c
}

// SetIgnoredAt sets the "ignoredAt" field.
func (_c *CharacterIgnoreCreate) SetIgnoredAt(v time.Time) *CharacterIgnoreCreate {
	_c.mutation.SetIgnoredAt(v)
	return _c
}

// SetNillableIgnoredAt sets the "ignoredAt" field if the given value is not nil.
func (_c *CharacterIgnoreCreate) SetNillableIgnoredAt(v *time.Time) *CharacterIgnoreCreate {
	if v != nil {
		_c.SetIgnoredAt(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *CharacterIgnoreCreate) SetReason(v string) *CharacterIgnoreCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *CharacterIgnoreCreate) SetNillableReason(v *string) *CharacterIgnoreCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetIgnorerID sets the "ignorer" edge to the Character entity by ID.
func (_c *CharacterIgnoreCreate) SetIgnorerID(id int) *CharacterIgnoreCreate {
	_c.mutation.SetIgnorerID(id)
	return _c
}

// SetNillableIgnorerID sets the "ignorer" edge to the Character entity by ID if the given value is not nil.
func (_c *CharacterIgnoreCreate) SetNillableIgnorerID(id *int) *CharacterIgnoreCreate {
	if id != nil {
		_c = _c.SetIgnorerID(*id)
	}
	return _c
}

// SetIgnorer sets the "ignorer" edge to the Character entity.
func (_c *CharacterIgnoreCreate) SetIgnorer(v *Character) *CharacterIgnoreCreate {
	return _c.SetIgnorerID(v.ID)
}

// Mutation returns the CharacterIgnoreMutation object of the builder.
func (_c *CharacterIgnoreCreate) Mutation() *CharacterIgnoreMutation {
	return _c.mutation
}

// Save creates the CharacterIgnore in the database.
func (_c *CharacterIgnoreCreate) Save(ctx context.Context) (*CharacterIgnore, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CharacterIgnoreCreate) SaveX(ctx context.Context) *CharacterIgnore {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CharacterIgnoreCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CharacterIgnoreCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CharacterIgnoreCreate) defaults() {
	if _, ok := _c.mutation.IgnoredAt(); !ok {
		v := characterignore.DefaultIgnoredAt()
		_c.mutation.SetIgnoredAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CharacterIgnoreCreate) check() error {
	if _, ok := _c.mutation.IgnoredCharacterId(); !ok {
		return &ValidationError{Name: "ignoredCharacterId", err: errors.New(`db: missing required field "CharacterIgnore.ignoredCharacterId"`)}
	}
	if _, ok := _c.mutation.IgnoredAt(); !ok {
		return &ValidationError{Name: "ignoredAt", err: errors.New(`db: missing required field "CharacterIgnore.ignoredAt"`)}
	}
	return nil
}

func (_c *CharacterIgnoreCreate) sqlSave(ctx context.Context) (*CharacterIgnore, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CharacterIgnoreCreate) createSpec() (*CharacterIgnore, *sqlgraph.CreateSpec) {
	var (
		_node = &CharacterIgnore{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(characterignore.Table, sqlgraph.NewFieldSpec(characterignore.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.IgnoredCharacterId(); ok {
		_spec.SetField(characterignore.FieldIgnoredCharacterId, field.TypeInt, value)
		_node.IgnoredCharacterId = value
	}
	if value, ok := _c.mutation.IgnoredAt(); ok {
		_spec.SetField(characterignore.FieldIgnoredAt, field.TypeTime, value)
		_node.IgnoredAt = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(characterignore.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if nodes := _c.mutation.IgnorerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   characterignore.IgnorerTable,
			Columns: []string{characterignore.IgnorerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.character_ignoring = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CharacterIgnoreCreateBulk is the builder for creating many CharacterIgnore entities in bulk.
type CharacterIgnoreCreateBulk struct {
	config
	err      error
	builders []*CharacterIgnoreCreate
}

// Save creates the CharacterIgnore entities in the database.
func (_c *CharacterIgnoreCreateBulk) Save(ctx context.Context) ([]*CharacterIgnore, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CharacterIgnore, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CharacterIgnoreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CharacterIgnoreCreateBulk) SaveX(ctx context.Context) []*CharacterIgnore {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CharacterIgnoreCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CharacterIgnoreCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
