// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"herbst-server/db/availabletalent"
	"herbst-server/db/character"
	"herbst-server/db/characterskill"
	"herbst-server/db/charactertalent"
	"herbst-server/db/room"
	"herbst-server/db/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CharacterCreate is the builder for creating a Character entity.
type CharacterCreate struct {
	config
	mutation *CharacterMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CharacterCreate) SetName(v string) *CharacterCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPassword sets the "password" field.
func (_c *CharacterCreate) SetPassword(v string) *CharacterCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_c *CharacterCreate) SetNillablePassword(v *string) *CharacterCreate {
	if v != nil {
		_c.SetPassword(*v)
	}
	return _c
}

// SetIsNPC sets the "isNPC" field.
func (_c *CharacterCreate) SetIsNPC(v bool) *CharacterCreate {
	_c.mutation.SetIsNPC(v)
	return _c
}

// SetNillableIsNPC sets the "isNPC" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableIsNPC(v *bool) *CharacterCreate {
	if v != nil {
		_c.SetIsNPC(*v)
	}
	return _c
}

// SetCurrentRoomId sets the "currentRoomId" field.
func (_c *CharacterCreate) SetCurrentRoomId(v int) *CharacterCreate {
	_c.mutation.SetCurrentRoomId(v)
	return _c
}

// SetStartingRoomId sets the "startingRoomId" field.
func (_c *CharacterCreate) SetStartingRoomId(v int) *CharacterCreate {
	_c.mutation.SetStartingRoomId(v)
	return _c
}

// SetIsAdmin sets the "is_admin" field.
func (_c *CharacterCreate) SetIsAdmin(v bool) *CharacterCreate {
	_c.mutation.SetIsAdmin(v)
	return _c
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableIsAdmin(v *bool) *CharacterCreate {
	if v != nil {
		_c.SetIsAdmin(*v)
	}
	return _c
}

// SetHitpoints sets the "hitpoints" field.
func (_c *CharacterCreate) SetHitpoints(v int) *CharacterCreate {
	_c.mutation.SetHitpoints(v)
	return _c
}

// SetNillableHitpoints sets the "hitpoints" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableHitpoints(v *int) *CharacterCreate {
	if v != nil {
		_c.SetHitpoints(*v)
	}
	return _c
}

// SetMaxHitpoints sets the "max_hitpoints" field.
func (_c *CharacterCreate) SetMaxHitpoints(v int) *CharacterCreate {
	_c.mutation.SetMaxHitpoints(v)
	return _c
}

// SetNillableMaxHitpoints sets the "max_hitpoints" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableMaxHitpoints(v *int) *CharacterCreate {
	if v != nil {
		_c.SetMaxHitpoints(*v)
	}
	return _c
}

// SetStamina sets the "stamina" field.
func (_c *CharacterCreate) SetStamina(v int) *CharacterCreate {
	_c.mutation.SetStamina(v)
	return _c
}

// SetNillableStamina sets the "stamina" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableStamina(v *int) *CharacterCreate {
	if v != nil {
		_c.SetStamina(*v)
	}
	return _c
}

// SetMaxStamina sets the "max_stamina" field.
func (_c *CharacterCreate) SetMaxStamina(v int) *CharacterCreate {
	_c.mutation.SetMaxStamina(v)
	return _c
}

// SetNillableMaxStamina sets the "max_stamina" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableMaxStamina(v *int) *CharacterCreate {
	if v != nil {
		_c.SetMaxStamina(*v)
	}
	return _c
}

// SetMana sets the "mana" field.
func (_c *CharacterCreate) SetMana(v int) *CharacterCreate {
	_c.mutation.SetMana(v)
	return _c
}

// SetNillableMana sets the "mana" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableMana(v *int) *CharacterCreate {
	if v != nil {
		_c.SetMana(*v)
	}
	return _c
}

// SetMaxMana sets the "max_mana" field.
func (_c *CharacterCreate) SetMaxMana(v int) *CharacterCreate {
	_c.mutation.SetMaxMana(v)
	return _c
}

// SetNillableMaxMana sets the "max_mana" field if the given value is not nil.
func (_c *CharacterCreate) SetNillableMaxMana(v *int) *CharacterCreate {
	if v != nil {
		_c.SetMaxMana(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *CharacterCreate) SetUserID(id int) *CharacterCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *CharacterCreate) SetNillableUserID(id *int) *CharacterCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CharacterCreate) SetUser(v *User) *CharacterCreate {
	return _c.SetUserID(v.ID)
}

// SetRoomID sets the "room" edge to the Room entity by ID.
func (_c *CharacterCreate) SetRoomID(id int) *CharacterCreate {
	_c.mutation.SetRoomID(id)
	return _c
}

// SetRoom sets the "room" edge to the Room entity.
func (_c *CharacterCreate) SetRoom(v *Room) *CharacterCreate {
	return _c.SetRoomID(v.ID)
}

// AddSkillIDs adds the "skills" edge to the CharacterSkill entity by IDs.
func (_c *CharacterCreate) AddSkillIDs(ids ...int) *CharacterCreate {
	_c.mutation.AddSkillIDs(ids...)
	return _c
}

// AddSkills adds the "skills" edges to the CharacterSkill entity.
func (_c *CharacterCreate) AddSkills(v ...*CharacterSkill) *CharacterCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSkillIDs(ids...)
}

// AddTalentIDs adds the "talents" edge to the CharacterTalent entity by IDs.
func (_c *CharacterCreate) AddTalentIDs(ids ...int) *CharacterCreate {
	_c.mutation.AddTalentIDs(ids...)
	return _c
}

// AddTalents adds the "talents" edges to the CharacterTalent entity.
func (_c *CharacterCreate) AddTalents(v ...*CharacterTalent) *CharacterCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTalentIDs(ids...)
}

// AddAvailableTalentIDs adds the "available_talents" edge to the AvailableTalent entity by IDs.
func (_c *CharacterCreate) AddAvailableTalentIDs(ids ...int) *CharacterCreate {
	_c.mutation.AddAvailableTalentIDs(ids...)
	return _c
}

// AddAvailableTalents adds the "available_talents" edges to the AvailableTalent entity.
func (_c *CharacterCreate) AddAvailableTalents(v ...*AvailableTalent) *CharacterCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAvailableTalentIDs(ids...)
}

// Mutation returns the CharacterMutation object of the builder.
func (_c *CharacterCreate) Mutation() *CharacterMutation {
	return _c.mutation
}

// Save creates the Character in the database.
func (_c *CharacterCreate) Save(ctx context.Context) (*Character, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CharacterCreate) SaveX(ctx context.Context) *Character {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CharacterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CharacterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CharacterCreate) defaults() {
	if _, ok := _c.mutation.IsNPC(); !ok {
		v := character.DefaultIsNPC
		_c.mutation.SetIsNPC(v)
	}
	if _, ok := _c.mutation.IsAdmin(); !ok {
		v := character.DefaultIsAdmin
		_c.mutation.SetIsAdmin(v)
	}
	if _, ok := _c.mutation.Hitpoints(); !ok {
		v := character.DefaultHitpoints
		_c.mutation.SetHitpoints(v)
	}
	if _, ok := _c.mutation.MaxHitpoints(); !ok {
		v := character.DefaultMaxHitpoints
		_c.mutation.SetMaxHitpoints(v)
	}
	if _, ok := _c.mutation.Stamina(); !ok {
		v := character.DefaultStamina
		_c.mutation.SetStamina(v)
	}
	if _, ok := _c.mutation.MaxStamina(); !ok {
		v := character.DefaultMaxStamina
		_c.mutation.SetMaxStamina(v)
	}
	if _, ok := _c.mutation.Mana(); !ok {
		v := character.DefaultMana
		_c.mutation.SetMana(v)
	}
	if _, ok := _c.mutation.MaxMana(); !ok {
		v := character.DefaultMaxMana
		_c.mutation.SetMaxMana(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CharacterCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`db: missing required field "Character.name"`)}
	}
	if _, ok := _c.mutation.IsNPC(); !ok {
		return &ValidationError{Name: "isNPC", err: errors.New(`db: missing required field "Character.isNPC"`)}
	}
	if _, ok := _c.mutation.CurrentRoomId(); !ok {
		return &ValidationError{Name: "currentRoomId", err: errors.New(`db: missing required field "Character.currentRoomId"`)}
	}
	if _, ok := _c.mutation.StartingRoomId(); !ok {
		return &ValidationError{Name: "startingRoomId", err: errors.New(`db: missing required field "Character.startingRoomId"`)}
	}
	if _, ok := _c.mutation.IsAdmin(); !ok {
		return &ValidationError{Name: "is_admin", err: errors.New(`db: missing required field "Character.is_admin"`)}
	}
	if _, ok := _c.mutation.Hitpoints(); !ok {
		return &ValidationError{Name: "hitpoints", err: errors.New(`db: missing required field "Character.hitpoints"`)}
	}
	if _, ok := _c.mutation.MaxHitpoints(); !ok {
		return &ValidationError{Name: "max_hitpoints", err: errors.New(`db: missing required field "Character.max_hitpoints"`)}
	}
	if _, ok := _c.mutation.Stamina(); !ok {
		return &ValidationError{Name: "stamina", err: errors.New(`db: missing required field "Character.stamina"`)}
	}
	if _, ok := _c.mutation.MaxStamina(); !ok {
		return &ValidationError{Name: "max_stamina", err: errors.New(`db: missing required field "Character.max_stamina"`)}
	}
	if _, ok := _c.mutation.Mana(); !ok {
		return &ValidationError{Name: "mana", err: errors.New(`db: missing required field "Character.mana"`)}
	}
	if _, ok := _c.mutation.MaxMana(); !ok {
		return &ValidationError{Name: "max_mana", err: errors.New(`db: missing required field "Character.max_mana"`)}
	}
	if len(_c.mutation.RoomIDs()) == 0 {
		return &ValidationError{Name: "room", err: errors.New(`db: missing required edge "Character.room"`)}
	}
	return nil
}

func (_c *CharacterCreate) sqlSave(ctx context.Context) (*Character, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CharacterCreate) createSpec() (*Character, *sqlgraph.CreateSpec) {
	var (
		_node = &Character{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(character.Table, sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(character.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(character.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.IsNPC(); ok {
		_spec.SetField(character.FieldIsNPC, field.TypeBool, value)
		_node.IsNPC = value
	}
	if value, ok := _c.mutation.StartingRoomId(); ok {
		_spec.SetField(character.FieldStartingRoomId, field.TypeInt, value)
		_node.StartingRoomId = value
	}
	if value, ok := _c.mutation.IsAdmin(); ok {
		_spec.SetField(character.FieldIsAdmin, field.TypeBool, value)
		_node.IsAdmin = value
	}
	if value, ok := _c.mutation.Hitpoints(); ok {
		_spec.SetField(character.FieldHitpoints, field.TypeInt, value)
		_node.Hitpoints = value
	}
	if value, ok := _c.mutation.MaxHitpoints(); ok {
		_spec.SetField(character.FieldMaxHitpoints, field.TypeInt, value)
		_node.MaxHitpoints = value
	}
	if value, ok := _c.mutation.Stamina(); ok {
		_spec.SetField(character.FieldStamina, field.TypeInt, value)
		_node.Stamina = value
	}
	if value, ok := _c.mutation.MaxStamina(); ok {
		_spec.SetField(character.FieldMaxStamina, field.TypeInt, value)
		_node.MaxStamina = value
	}
	if value, ok := _c.mutation.Mana(); ok {
		_spec.SetField(character.FieldMana, field.TypeInt, value)
		_node.Mana = value
	}
	if value, ok := _c.mutation.MaxMana(); ok {
		_spec.SetField(character.FieldMaxMana, field.TypeInt, value)
		_node.MaxMana = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   character.UserTable,
			Columns: []string{character.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_characters = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   character.RoomTable,
			Columns: []string{character.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CurrentRoomId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.SkillsTable,
			Columns: []string{character.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(characterskill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TalentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.TalentsTable,
			Columns: []string{character.TalentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(charactertalent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AvailableTalentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   character.AvailableTalentsTable,
			Columns: []string{character.AvailableTalentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(availabletalent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CharacterCreateBulk is the builder for creating many Character entities in bulk.
type CharacterCreateBulk struct {
	config
	err      error
	builders []*CharacterCreate
}

// Save creates the Character entities in the database.
func (_c *CharacterCreateBulk) Save(ctx context.Context) ([]*Character, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Character, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CharacterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CharacterCreateBulk) SaveX(ctx context.Context) []*Character {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CharacterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CharacterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
