// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"herbst-server/db/characterignore"
	"herbst-server/db/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CharacterIgnoreDelete is the builder for deleting a CharacterIgnore entity.
type CharacterIgnoreDelete struct {
	config
	hooks    []Hook
	mutation *CharacterIgnoreMutation
}

// Where appends a list predicates to the CharacterIgnoreDelete builder.
func (_d *CharacterIgnoreDelete) Where(ps ...predicate.CharacterIgnore) *CharacterIgnoreDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CharacterIgnoreDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CharacterIgnoreDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CharacterIgnoreDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(characterignore.Table, sqlgraph.NewFieldSpec(characterignore.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CharacterIgnoreDeleteOne is the builder for deleting a single CharacterIgnore entity.
type CharacterIgnoreDeleteOne struct {
	_d *CharacterIgnoreDelete
}

// Where appends a list predicates to the CharacterIgnoreDelete builder.
func (_d *CharacterIgnoreDeleteOne) Where(ps ...predicate.CharacterIgnore) *CharacterIgnoreDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CharacterIgnoreDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{characterignore.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CharacterIgnoreDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
