// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"herbst-server/db/character"
	"herbst-server/db/characterignore"
	"herbst-server/db/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CharacterIgnoreUpdate is the builder for updating CharacterIgnore entities.
type CharacterIgnoreUpdate struct {
	config
	hooks    []Hook
	mutation *CharacterIgnoreMutation
}

// Where appends a list predicates to the CharacterIgnoreUpdate builder.
func (_u *CharacterIgnoreUpdate) Where(ps ...predicate.CharacterIgnore) *CharacterIgnoreUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIgnoredCharacterId sets the "ignoredCharacterId" field.
func (_u *CharacterIgnoreUpdate) SetIgnoredCharacterId(v int) *CharacterIgnoreUpdate {
	_u.mutation.ResetIgnoredCharacterId()
	_u.mutation.SetIgnoredCharacterId(v)
	return _u
}

// SetNillableIgnoredCharacterId sets the "ignoredCharacterId" field if the given value is not nil.
func (_u *CharacterIgnoreUpdate) SetNillableIgnoredCharacterId(v *int) *CharacterIgnoreUpdate {
	if v != nil {
		_u.SetIgnoredCharacterId(*v)
	}
	return _u
}

// AddIgnoredCharacterId adds value to the "ignoredCharacterId" field.
func (_u *CharacterIgnoreUpdate) AddIgnoredCharacterId(v int) *CharacterIgnoreUpdate {
	_u.mutation.AddIgnoredCharacterId(v)
	return _u
}

// SetIgnoredAt sets the "ignoredAt" field.
func (_u *CharacterIgnoreUpdate) SetIgnoredAt(v time.Time) *CharacterIgnoreUpdate {
	_u.mutation.SetIgnoredAt(v)
	return _u
}

// SetNillableIgnoredAt sets the "ignoredAt" field if the given value is not nil.
func (_u *CharacterIgnoreUpdate) SetNillableIgnoredAt(v *time.Time) *CharacterIgnoreUpdate {
	if v != nil {
		_u.SetIgnoredAt(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *CharacterIgnoreUpdate) SetReason(v string) *CharacterIgnoreUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *CharacterIgnoreUpdate) SetNillableReason(v *string) *CharacterIgnoreUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *CharacterIgnoreUpdate) ClearReason() *CharacterIgnoreUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetIgnorerID sets the "ignorer" edge to the Character entity by ID.
func (_u *CharacterIgnoreUpdate) SetIgnorerID(id int) *CharacterIgnoreUpdate {
	_u.mutation.SetIgnorerID(id)
	return _u
}

// SetNillableIgnorerID sets the "ignorer" edge to the Character entity by ID if the given value is not nil.
func (_u *CharacterIgnoreUpdate) SetNillableIgnorerID(id *int) *CharacterIgnoreUpdate {
	if id != nil {
		_u = _u.SetIgnorerID(*id)
	}
	return _u
}

// SetIgnorer sets the "ignorer" edge to the Character entity.
func (_u *CharacterIgnoreUpdate) SetIgnorer(v *Character) *CharacterIgnoreUpdate {
	return _u.SetIgnorerID(v.ID)
}

// Mutation returns the CharacterIgnoreMutation object of the builder.
func (_u *CharacterIgnoreUpdate) Mutation() *CharacterIgnoreMutation {
	return _u.mutation
}

// ClearIgnorer clears the "ignorer" edge to the Character entity.
func (_u *CharacterIgnoreUpdate) ClearIgnorer() *CharacterIgnoreUpdate {
	_u.mutation.ClearIgnorer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CharacterIgnoreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CharacterIgnoreUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CharacterIgnoreUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CharacterIgnoreUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CharacterIgnoreUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(characterignore.Table, characterignore.Columns, sqlgraph.NewFieldSpec(characterignore.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IgnoredCharacterId(); ok {
		_spec.SetField(characterignore.FieldIgnoredCharacterId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIgnoredCharacterId(); ok {
		_spec.AddField(characterignore.FieldIgnoredCharacterId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IgnoredAt(); ok {
		_spec.SetField(characterignore.FieldIgnoredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(characterignore.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(characterignore.FieldReason, field.TypeString)
	}
	if _u.mutation.IgnorerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   characterignore.IgnorerTable,
			Columns: []string{characterignore.IgnorerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IgnorerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   characterignore.IgnorerTable,
			Columns: []string{characterignore.IgnorerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{characterignore.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CharacterIgnoreUpdateOne is the builder for updating a single CharacterIgnore entity.
type CharacterIgnoreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CharacterIgnoreMutation
}

// SetIgnoredCharacterId sets the "ignoredCharacterId" field.
func (_u *CharacterIgnoreUpdateOne) SetIgnoredCharacterId(v int) *CharacterIgnoreUpdateOne {
	_u.mutation.ResetIgnoredCharacterId()
	_u.mutation.SetIgnoredCharacterId(v)
	return _u
}

// SetNillableIgnoredCharacterId sets the "ignoredCharacterId" field if the given value is not nil.
func (_u *CharacterIgnoreUpdateOne) SetNillableIgnoredCharacterId(v *int) *CharacterIgnoreUpdateOne {
	if v != nil {
		_u.SetIgnoredCharacterId(*v)
	}
	return _u
}

// AddIgnoredCharacterId adds value to the "ignoredCharacterId" field.
func (_u *CharacterIgnoreUpdateOne) AddIgnoredCharacterId(v int) *CharacterIgnoreUpdateOne {
	_u.mutation.AddIgnoredCharacterId(v)
	return _u
}

// SetIgnoredAt sets the "ignoredAt" field.
func (_u *CharacterIgnoreUpdateOne) SetIgnoredAt(v time.Time) *CharacterIgnoreUpdateOne {
	_u.mutation.SetIgnoredAt(v)
	return _u
}

// SetNillableIgnoredAt sets the "ignoredAt" field if the given value is not nil.
func (_u *CharacterIgnoreUpdateOne) SetNillableIgnoredAt(v *time.Time) *CharacterIgnoreUpdateOne {
	if v != nil {
		_u.SetIgnoredAt(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *CharacterIgnoreUpdateOne) SetReason(v string) *CharacterIgnoreUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *CharacterIgnoreUpdateOne) SetNillableReason(v *string) *CharacterIgnoreUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *CharacterIgnoreUpdateOne) ClearReason() *CharacterIgnoreUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetIgnorerID sets the "ignorer" edge to the Character entity by ID.
func (_u *CharacterIgnoreUpdateOne) SetIgnorerID(id int) *CharacterIgnoreUpdateOne {
	_u.mutation.SetIgnorerID(id)
	return _u
}

// SetNillableIgnorerID sets the "ignorer" edge to the Character entity by ID if the given value is not nil.
func (_u *CharacterIgnoreUpdateOne) SetNillableIgnorerID(id *int) *CharacterIgnoreUpdateOne {
	if id != nil {
		_u = _u.SetIgnorerID(*id)
	}
	return _u
}

// SetIgnorer sets the "ignorer" edge to the Character entity.
func (_u *CharacterIgnoreUpdateOne) SetIgnorer(v *Character) *CharacterIgnoreUpdateOne {
	return _u.SetIgnorerID(v.ID)
}

// Mutation returns the CharacterIgnoreMutation object of the builder.
func (_u *CharacterIgnoreUpdateOne) Mutation() *CharacterIgnoreMutation {
	return _u.mutation
}

// ClearIgnorer clears the "ignorer" edge to the Character entity.
func (_u *CharacterIgnoreUpdateOne) ClearIgnorer() *CharacterIgnoreUpdateOne {
	_u.mutation.ClearIgnorer()
	return _u
}

// Where appends a list predicates to the CharacterIgnoreUpdate builder.
func (_u *CharacterIgnoreUpdateOne) Where(ps ...predicate.CharacterIgnore) *CharacterIgnoreUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CharacterIgnoreUpdateOne) Select(field string, fields ...string) *CharacterIgnoreUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CharacterIgnore entity.
func (_u *CharacterIgnoreUpdateOne) Save(ctx context.Context) (*CharacterIgnore, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CharacterIgnoreUpdateOne) SaveX(ctx context.Context) *CharacterIgnore {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CharacterIgnoreUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CharacterIgnoreUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CharacterIgnoreUpdateOne) sqlSave(ctx context.Context) (_node *CharacterIgnore, err error) {
	_spec := sqlgraph.NewUpdateSpec(characterignore.Table, characterignore.Columns, sqlgraph.NewFieldSpec(characterignore.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "CharacterIgnore.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, characterignore.FieldID)
		for _, f := range fields {
			if !characterignore.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != characterignore.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IgnoredCharacterId(); ok {
		_spec.SetField(characterignore.FieldIgnoredCharacterId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIgnoredCharacterId(); ok {
		_spec.AddField(characterignore.FieldIgnoredCharacterId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IgnoredAt(); ok {
		_spec.SetField(characterignore.FieldIgnoredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(characterignore.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(characterignore.FieldReason, field.TypeString)
	}
	if _u.mutation.IgnorerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   characterignore.IgnorerTable,
			Columns: []string{characterignore.IgnorerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IgnorerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   characterignore.IgnorerTable,
			Columns: []string{characterignore.IgnorerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CharacterIgnore{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{characterignore.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
