// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"herbst-server/db/characterchannel"
	"herbst-server/db/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CharacterChannelDelete is the builder for deleting a CharacterChannel entity.
type CharacterChannelDelete struct {
	config
	hooks    []Hook
	mutation *CharacterChannelMutation
}

// Where appends a list predicates to the CharacterChannelDelete builder.
func (_d *CharacterChannelDelete) Where(ps ...predicate.CharacterChannel) *CharacterChannelDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CharacterChannelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CharacterChannelDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CharacterChannelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(characterchannel.Table, sqlgraph.NewFieldSpec(characterchannel.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CharacterChannelDeleteOne is the builder for deleting a single CharacterChannel entity.
type CharacterChannelDeleteOne struct {
	_d *CharacterChannelDelete
}

// Where appends a list predicates to the CharacterChannelDelete builder.
func (_d *CharacterChannelDeleteOne) Where(ps ...predicate.CharacterChannel) *CharacterChannelDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CharacterChannelDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{characterchannel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CharacterChannelDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
