// Code generated by ent, DO NOT EDIT.

package db

import (
	"encoding/json"
	"fmt"
	"herbst-server/db/equipment"
	"herbst-server/db/equipmenttemplate"
	"herbst-server/db/room"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Equipment is the model entity for the Equipment schema.
type Equipment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Slot holds the value of the "slot" field.
	Slot string `json:"slot,omitempty"`
	// Level holds the value of the "level" field.
	Level int `json:"level,omitempty"`
	// Weight holds the value of the "weight" field.
	Weight int `json:"weight,omitempty"`
	// IsEquipped holds the value of the "isEquipped" field.
	IsEquipped bool `json:"isEquipped,omitempty"`
	// Cannot be picked up if true
	IsImmovable bool `json:"isImmovable,omitempty"`
	// Custom display color (e.g., gold for immovable items)
	Color string `json:"color,omitempty"`
	// Shown in room list
	IsVisible bool `json:"isVisible,omitempty"`
	// weapon|armor|consumable|quest|misc|container|potion
	ItemType string `json:"itemType,omitempty"`
	// FK to equipment_template
	EquipmentTemplateID int `json:"equipment_template_id,omitempty"`
	// Character ID that owns this item
	OwnerId *int `json:"ownerId,omitempty"`
	// heal|damage|dot|buff_armor|buff_dodge|buff_crit|debuff
	EffectType string `json:"effect_type,omitempty"`
	// Effect magnitude
	EffectValue int `json:"effect_value,omitempty"`
	// Duration in ticks (0 = instant)
	EffectDuration int `json:"effect_duration,omitempty"`
	// DEPRECATED: Use effect_type=heal and effect_value instead
	Healing int `json:"healing,omitempty"`
	// DEPRECATED: Use effect_type instead
	Effect string `json:"effect,omitempty"`
	// Can hold items if true
	IsContainer bool `json:"isContainer,omitempty"`
	// Max items container can hold
	ContainerCapacity int `json:"containerCapacity,omitempty"`
	// Requires key to open
	IsLocked bool `json:"isLocked,omitempty"`
	// ID of key item needed to unlock
	KeyItemID string `json:"keyItemID,omitempty"`
	// JSON array of contained item IDs
	ContainedItems string `json:"containedItems,omitempty"`
	// JSON: {type: examine|perception_check|use_item|event, target, minLevel}
	RevealCondition string `json:"revealCondition,omitempty"`
	// Detailed description shown with examine command
	ExamineDesc string `json:"examineDesc,omitempty"`
	// Details revealed based on examine skill
	HiddenDetails []map[string]interface{} `json:"hiddenDetails,omitempty"`
	// Examine skill required to reveal hidden details
	HiddenThreshold int `json:"hiddenThreshold,omitempty"`
	// When this item expires and is auto-deleted. nil = never rots.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	// Stack size for consumable/ingredient items
	Quantity int `json:"quantity,omitempty"`
	// Flat AC bonus when equipped
	ArmorRating int `json:"armor_rating,omitempty"`
	// light|cloth|heavy or empty
	ArmorType string `json:"armor_type,omitempty"`
	// Passive stat bonuses when equipped
	Stats map[string]int `json:"stats,omitempty"`
	// common|uncommon|rare|epic|legendary
	Rarity string `json:"rarity,omitempty"`
	// Which skill governs this item
	SkillRequirement string `json:"skill_requirement,omitempty"`
	// Min skill level for full effect
	SkillRequirementLevel int `json:"skill_requirement_level,omitempty"`
	// Number of dice (0 = not a weapon)
	DamageDiceCount int `json:"damage_dice_count,omitempty"`
	// Sides per die
	DamageDiceSides int `json:"damage_dice_sides,omitempty"`
	// Flat damage modifier
	DamageBonus int `json:"damage_bonus,omitempty"`
	// slashing|piercing|bludgeoning|fire|etc.
	DamageType string `json:"damage_type,omitempty"`
	// sword|axe|spear|knife|martial|staff|pipe
	WeaponType string `json:"weapon_type,omitempty"`
	// Occupies both hand slots
	IsTwoHanded bool `json:"is_two_handed,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EquipmentQuery when eager-loading is set.
	Edges          EquipmentEdges `json:"edges"`
	room_equipment *int
	selectValues   sql.SelectValues
}

// EquipmentEdges holds the relations/edges for other nodes in the graph.
type EquipmentEdges struct {
	// Room holds the value of the room edge.
	Room *Room `json:"room,omitempty"`
	// EquipmentTemplate holds the value of the equipmentTemplate edge.
	EquipmentTemplate *EquipmentTemplate `json:"equipmentTemplate,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RoomOrErr returns the Room value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EquipmentEdges) RoomOrErr() (*Room, error) {
	if e.Room != nil {
		return e.Room, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: room.Label}
	}
	return nil, &NotLoadedError{edge: "room"}
}

// EquipmentTemplateOrErr returns the EquipmentTemplate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EquipmentEdges) EquipmentTemplateOrErr() (*EquipmentTemplate, error) {
	if e.EquipmentTemplate != nil {
		return e.EquipmentTemplate, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: equipmenttemplate.Label}
	}
	return nil, &NotLoadedError{edge: "equipmentTemplate"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Equipment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case equipment.FieldHiddenDetails, equipment.FieldStats:
			values[i] = new([]byte)
		case equipment.FieldIsEquipped, equipment.FieldIsImmovable, equipment.FieldIsVisible, equipment.FieldIsContainer, equipment.FieldIsLocked, equipment.FieldIsTwoHanded:
			values[i] = new(sql.NullBool)
		case equipment.FieldID, equipment.FieldLevel, equipment.FieldWeight, equipment.FieldEquipmentTemplateID, equipment.FieldOwnerId, equipment.FieldEffectValue, equipment.FieldEffectDuration, equipment.FieldHealing, equipment.FieldContainerCapacity, equipment.FieldHiddenThreshold, equipment.FieldQuantity, equipment.FieldArmorRating, equipment.FieldSkillRequirementLevel, equipment.FieldDamageDiceCount, equipment.FieldDamageDiceSides, equipment.FieldDamageBonus:
			values[i] = new(sql.NullInt64)
		case equipment.FieldName, equipment.FieldDescription, equipment.FieldSlot, equipment.FieldColor, equipment.FieldItemType, equipment.FieldEffectType, equipment.FieldEffect, equipment.FieldKeyItemID, equipment.FieldContainedItems, equipment.FieldRevealCondition, equipment.FieldExamineDesc, equipment.FieldArmorType, equipment.FieldRarity, equipment.FieldSkillRequirement, equipment.FieldDamageType, equipment.FieldWeaponType:
			values[i] = new(sql.NullString)
		case equipment.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case equipment.ForeignKeys[0]: // room_equipment
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Equipment fields.
func (_m *Equipment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case equipment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case equipment.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case equipment.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case equipment.FieldSlot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slot", values[i])
			} else if value.Valid {
				_m.Slot = value.String
			}
		case equipment.FieldLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = int(value.Int64)
			}
		case equipment.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case equipment.FieldIsEquipped:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isEquipped", values[i])
			} else if value.Valid {
				_m.IsEquipped = value.Bool
			}
		case equipment.FieldIsImmovable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isImmovable", values[i])
			} else if value.Valid {
				_m.IsImmovable = value.Bool
			}
		case equipment.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = value.String
			}
		case equipment.FieldIsVisible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isVisible", values[i])
			} else if value.Valid {
				_m.IsVisible = value.Bool
			}
		case equipment.FieldItemType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field itemType", values[i])
			} else if value.Valid {
				_m.ItemType = value.String
			}
		case equipment.FieldEquipmentTemplateID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field equipment_template_id", values[i])
			} else if value.Valid {
				_m.EquipmentTemplateID = int(value.Int64)
			}
		case equipment.FieldOwnerId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ownerId", values[i])
			} else if value.Valid {
				_m.OwnerId = new(int)
				*_m.OwnerId = int(value.Int64)
			}
		case equipment.FieldEffectType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field effect_type", values[i])
			} else if value.Valid {
				_m.EffectType = value.String
			}
		case equipment.FieldEffectValue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field effect_value", values[i])
			} else if value.Valid {
				_m.EffectValue = int(value.Int64)
			}
		case equipment.FieldEffectDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field effect_duration", values[i])
			} else if value.Valid {
				_m.EffectDuration = int(value.Int64)
			}
		case equipment.FieldHealing:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field healing", values[i])
			} else if value.Valid {
				_m.Healing = int(value.Int64)
			}
		case equipment.FieldEffect:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field effect", values[i])
			} else if value.Valid {
				_m.Effect = value.String
			}
		case equipment.FieldIsContainer:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isContainer", values[i])
			} else if value.Valid {
				_m.IsContainer = value.Bool
			}
		case equipment.FieldContainerCapacity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field containerCapacity", values[i])
			} else if value.Valid {
				_m.ContainerCapacity = int(value.Int64)
			}
		case equipment.FieldIsLocked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isLocked", values[i])
			} else if value.Valid {
				_m.IsLocked = value.Bool
			}
		case equipment.FieldKeyItemID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field keyItemID", values[i])
			} else if value.Valid {
				_m.KeyItemID = value.String
			}
		case equipment.FieldContainedItems:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field containedItems", values[i])
			} else if value.Valid {
				_m.ContainedItems = value.String
			}
		case equipment.FieldRevealCondition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revealCondition", values[i])
			} else if value.Valid {
				_m.RevealCondition = value.String
			}
		case equipment.FieldExamineDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field examineDesc", values[i])
			} else if value.Valid {
				_m.ExamineDesc = value.String
			}
		case equipment.FieldHiddenDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field hiddenDetails", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.HiddenDetails); err != nil {
					return fmt.Errorf("unmarshal field hiddenDetails: %w", err)
				}
			}
		case equipment.FieldHiddenThreshold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hiddenThreshold", values[i])
			} else if value.Valid {
				_m.HiddenThreshold = int(value.Int64)
			}
		case equipment.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiresAt", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case equipment.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = int(value.Int64)
			}
		case equipment.FieldArmorRating:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field armor_rating", values[i])
			} else if value.Valid {
				_m.ArmorRating = int(value.Int64)
			}
		case equipment.FieldArmorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field armor_type", values[i])
			} else if value.Valid {
				_m.ArmorType = value.String
			}
		case equipment.FieldStats:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field stats", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Stats); err != nil {
					return fmt.Errorf("unmarshal field stats: %w", err)
				}
			}
		case equipment.FieldRarity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rarity", values[i])
			} else if value.Valid {
				_m.Rarity = value.String
			}
		case equipment.FieldSkillRequirement:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skill_requirement", values[i])
			} else if value.Valid {
				_m.SkillRequirement = value.String
			}
		case equipment.FieldSkillRequirementLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field skill_requirement_level", values[i])
			} else if value.Valid {
				_m.SkillRequirementLevel = int(value.Int64)
			}
		case equipment.FieldDamageDiceCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field damage_dice_count", values[i])
			} else if value.Valid {
				_m.DamageDiceCount = int(value.Int64)
			}
		case equipment.FieldDamageDiceSides:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field damage_dice_sides", values[i])
			} else if value.Valid {
				_m.DamageDiceSides = int(value.Int64)
			}
		case equipment.FieldDamageBonus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field damage_bonus", values[i])
			} else if value.Valid {
				_m.DamageBonus = int(value.Int64)
			}
		case equipment.FieldDamageType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field damage_type", values[i])
			} else if value.Valid {
				_m.DamageType = value.String
			}
		case equipment.FieldWeaponType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field weapon_type", values[i])
			} else if value.Valid {
				_m.WeaponType = value.String
			}
		case equipment.FieldIsTwoHanded:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_two_handed", values[i])
			} else if value.Valid {
				_m.IsTwoHanded = value.Bool
			}
		case equipment.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field room_equipment", value)
			} else if value.Valid {
				_m.room_equipment = new(int)
				*_m.room_equipment = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Equipment.
// This includes values selected through modifiers, order, etc.
func (_m *Equipment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoom queries the "room" edge of the Equipment entity.
func (_m *Equipment) QueryRoom() *RoomQuery {
	return NewEquipmentClient(_m.config).QueryRoom(_m)
}

// QueryEquipmentTemplate queries the "equipmentTemplate" edge of the Equipment entity.
func (_m *Equipment) QueryEquipmentTemplate() *EquipmentTemplateQuery {
	return NewEquipmentClient(_m.config).QueryEquipmentTemplate(_m)
}

// Update returns a builder for updating this Equipment.
// Note that you need to call Equipment.Unwrap() before calling this method if this Equipment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Equipment) Update() *EquipmentUpdateOne {
	return NewEquipmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Equipment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Equipment) Unwrap() *Equipment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: Equipment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Equipment) String() string {
	var builder strings.Builder
	builder.WriteString("Equipment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("slot=")
	builder.WriteString(_m.Slot)
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", _m.Level))
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("isEquipped=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsEquipped))
	builder.WriteString(", ")
	builder.WriteString("isImmovable=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsImmovable))
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(_m.Color)
	builder.WriteString(", ")
	builder.WriteString("isVisible=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsVisible))
	builder.WriteString(", ")
	builder.WriteString("itemType=")
	builder.WriteString(_m.ItemType)
	builder.WriteString(", ")
	builder.WriteString("equipment_template_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EquipmentTemplateID))
	builder.WriteString(", ")
	if v := _m.OwnerId; v != nil {
		builder.WriteString("ownerId=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("effect_type=")
	builder.WriteString(_m.EffectType)
	builder.WriteString(", ")
	builder.WriteString("effect_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.EffectValue))
	builder.WriteString(", ")
	builder.WriteString("effect_duration=")
	builder.WriteString(fmt.Sprintf("%v", _m.EffectDuration))
	builder.WriteString(", ")
	builder.WriteString("healing=")
	builder.WriteString(fmt.Sprintf("%v", _m.Healing))
	builder.WriteString(", ")
	builder.WriteString("effect=")
	builder.WriteString(_m.Effect)
	builder.WriteString(", ")
	builder.WriteString("isContainer=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsContainer))
	builder.WriteString(", ")
	builder.WriteString("containerCapacity=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContainerCapacity))
	builder.WriteString(", ")
	builder.WriteString("isLocked=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsLocked))
	builder.WriteString(", ")
	builder.WriteString("keyItemID=")
	builder.WriteString(_m.KeyItemID)
	builder.WriteString(", ")
	builder.WriteString("containedItems=")
	builder.WriteString(_m.ContainedItems)
	builder.WriteString(", ")
	builder.WriteString("revealCondition=")
	builder.WriteString(_m.RevealCondition)
	builder.WriteString(", ")
	builder.WriteString("examineDesc=")
	builder.WriteString(_m.ExamineDesc)
	builder.WriteString(", ")
	builder.WriteString("hiddenDetails=")
	builder.WriteString(fmt.Sprintf("%v", _m.HiddenDetails))
	builder.WriteString(", ")
	builder.WriteString("hiddenThreshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.HiddenThreshold))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expiresAt=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("armor_rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.ArmorRating))
	builder.WriteString(", ")
	builder.WriteString("armor_type=")
	builder.WriteString(_m.ArmorType)
	builder.WriteString(", ")
	builder.WriteString("stats=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stats))
	builder.WriteString(", ")
	builder.WriteString("rarity=")
	builder.WriteString(_m.Rarity)
	builder.WriteString(", ")
	builder.WriteString("skill_requirement=")
	builder.WriteString(_m.SkillRequirement)
	builder.WriteString(", ")
	builder.WriteString("skill_requirement_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkillRequirementLevel))
	builder.WriteString(", ")
	builder.WriteString("damage_dice_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DamageDiceCount))
	builder.WriteString(", ")
	builder.WriteString("damage_dice_sides=")
	builder.WriteString(fmt.Sprintf("%v", _m.DamageDiceSides))
	builder.WriteString(", ")
	builder.WriteString("damage_bonus=")
	builder.WriteString(fmt.Sprintf("%v", _m.DamageBonus))
	builder.WriteString(", ")
	builder.WriteString("damage_type=")
	builder.WriteString(_m.DamageType)
	builder.WriteString(", ")
	builder.WriteString("weapon_type=")
	builder.WriteString(_m.WeaponType)
	builder.WriteString(", ")
	builder.WriteString("is_two_handed=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsTwoHanded))
	builder.WriteByte(')')
	return builder.String()
}

// EquipmentSlice is a parsable slice of Equipment.
type EquipmentSlice []*Equipment
