// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"herbst-server/db/faction"
	"herbst-server/db/factionrequiredtag"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// FactionRequiredTag is the model entity for the FactionRequiredTag schema.
type FactionRequiredTag struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Tag the character must have to pledge to this faction
	RequiredTag string `json:"required_tag,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FactionRequiredTagQuery when eager-loading is set.
	Edges                 FactionRequiredTagEdges `json:"edges"`
	faction_required_tags *int
	selectValues          sql.SelectValues
}

// FactionRequiredTagEdges holds the relations/edges for other nodes in the graph.
type FactionRequiredTagEdges struct {
	// Faction holds the value of the faction edge.
	Faction *Faction `json:"faction,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FactionOrErr returns the Faction value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FactionRequiredTagEdges) FactionOrErr() (*Faction, error) {
	if e.Faction != nil {
		return e.Faction, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: faction.Label}
	}
	return nil, &NotLoadedError{edge: "faction"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FactionRequiredTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case factionrequiredtag.FieldID:
			values[i] = new(sql.NullInt64)
		case factionrequiredtag.FieldRequiredTag:
			values[i] = new(sql.NullString)
		case factionrequiredtag.ForeignKeys[0]: // faction_required_tags
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FactionRequiredTag fields.
func (_m *FactionRequiredTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case factionrequiredtag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case factionrequiredtag.FieldRequiredTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field required_tag", values[i])
			} else if value.Valid {
				_m.RequiredTag = value.String
			}
		case factionrequiredtag.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field faction_required_tags", value)
			} else if value.Valid {
				_m.faction_required_tags = new(int)
				*_m.faction_required_tags = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FactionRequiredTag.
// This includes values selected through modifiers, order, etc.
func (_m *FactionRequiredTag) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFaction queries the "faction" edge of the FactionRequiredTag entity.
func (_m *FactionRequiredTag) QueryFaction() *FactionQuery {
	return NewFactionRequiredTagClient(_m.config).QueryFaction(_m)
}

// Update returns a builder for updating this FactionRequiredTag.
// Note that you need to call FactionRequiredTag.Unwrap() before calling this method if this FactionRequiredTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FactionRequiredTag) Update() *FactionRequiredTagUpdateOne {
	return NewFactionRequiredTagClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FactionRequiredTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FactionRequiredTag) Unwrap() *FactionRequiredTag {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: FactionRequiredTag is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FactionRequiredTag) String() string {
	var builder strings.Builder
	builder.WriteString("FactionRequiredTag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("required_tag=")
	builder.WriteString(_m.RequiredTag)
	builder.WriteByte(')')
	return builder.String()
}

// FactionRequiredTags is a parsable slice of FactionRequiredTag.
type FactionRequiredTags []*FactionRequiredTag
