// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"herbst-server/db/faction"
	"herbst-server/db/factionrequiredtag"
	"herbst-server/db/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FactionRequiredTagQuery is the builder for querying FactionRequiredTag entities.
type FactionRequiredTagQuery struct {
	config
	ctx         *QueryContext
	order       []factionrequiredtag.OrderOption
	inters      []Interceptor
	predicates  []predicate.FactionRequiredTag
	withFaction *FactionQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FactionRequiredTagQuery builder.
func (_q *FactionRequiredTagQuery) Where(ps ...predicate.FactionRequiredTag) *FactionRequiredTagQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *FactionRequiredTagQuery) Limit(limit int) *FactionRequiredTagQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *FactionRequiredTagQuery) Offset(offset int) *FactionRequiredTagQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *FactionRequiredTagQuery) Unique(unique bool) *FactionRequiredTagQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *FactionRequiredTagQuery) Order(o ...factionrequiredtag.OrderOption) *FactionRequiredTagQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryFaction chains the current query on the "faction" edge.
func (_q *FactionRequiredTagQuery) QueryFaction() *FactionQuery {
	query := (&FactionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(factionrequiredtag.Table, factionrequiredtag.FieldID, selector),
			sqlgraph.To(faction.Table, faction.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, factionrequiredtag.FactionTable, factionrequiredtag.FactionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FactionRequiredTag entity from the query.
// Returns a *NotFoundError when no FactionRequiredTag was found.
func (_q *FactionRequiredTagQuery) First(ctx context.Context) (*FactionRequiredTag, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{factionrequiredtag.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *FactionRequiredTagQuery) FirstX(ctx context.Context) *FactionRequiredTag {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FactionRequiredTag ID from the query.
// Returns a *NotFoundError when no FactionRequiredTag ID was found.
func (_q *FactionRequiredTagQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{factionrequiredtag.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *FactionRequiredTagQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FactionRequiredTag entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FactionRequiredTag entity is found.
// Returns a *NotFoundError when no FactionRequiredTag entities are found.
func (_q *FactionRequiredTagQuery) Only(ctx context.Context) (*FactionRequiredTag, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{factionrequiredtag.Label}
	default:
		return nil, &NotSingularError{factionrequiredtag.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *FactionRequiredTagQuery) OnlyX(ctx context.Context) *FactionRequiredTag {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FactionRequiredTag ID in the query.
// Returns a *NotSingularError when more than one FactionRequiredTag ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *FactionRequiredTagQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{factionrequiredtag.Label}
	default:
		err = &NotSingularError{factionrequiredtag.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *FactionRequiredTagQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FactionRequiredTags.
func (_q *FactionRequiredTagQuery) All(ctx context.Context) ([]*FactionRequiredTag, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FactionRequiredTag, *FactionRequiredTagQuery]()
	return withInterceptors[[]*FactionRequiredTag](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *FactionRequiredTagQuery) AllX(ctx context.Context) []*FactionRequiredTag {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FactionRequiredTag IDs.
func (_q *FactionRequiredTagQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(factionrequiredtag.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *FactionRequiredTagQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *FactionRequiredTagQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*FactionRequiredTagQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *FactionRequiredTagQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *FactionRequiredTagQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *FactionRequiredTagQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FactionRequiredTagQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *FactionRequiredTagQuery) Clone() *FactionRequiredTagQuery {
	if _q == nil {
		return nil
	}
	return &FactionRequiredTagQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]factionrequiredtag.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.FactionRequiredTag{}, _q.predicates...),
		withFaction: _q.withFaction.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithFaction tells the query-builder to eager-load the nodes that are connected to
// the "faction" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FactionRequiredTagQuery) WithFaction(opts ...func(*FactionQuery)) *FactionRequiredTagQuery {
	query := (&FactionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFaction = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RequiredTag string `json:"required_tag,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FactionRequiredTag.Query().
//		GroupBy(factionrequiredtag.FieldRequiredTag).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (_q *FactionRequiredTagQuery) GroupBy(field string, fields ...string) *FactionRequiredTagGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FactionRequiredTagGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = factionrequiredtag.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RequiredTag string `json:"required_tag,omitempty"`
//	}
//
//	client.FactionRequiredTag.Query().
//		Select(factionrequiredtag.FieldRequiredTag).
//		Scan(ctx, &v)
func (_q *FactionRequiredTagQuery) Select(fields ...string) *FactionRequiredTagSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &FactionRequiredTagSelect{FactionRequiredTagQuery: _q}
	sbuild.label = factionrequiredtag.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FactionRequiredTagSelect configured with the given aggregations.
func (_q *FactionRequiredTagQuery) Aggregate(fns ...AggregateFunc) *FactionRequiredTagSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *FactionRequiredTagQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !factionrequiredtag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *FactionRequiredTagQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FactionRequiredTag, error) {
	var (
		nodes       = []*FactionRequiredTag{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withFaction != nil,
		}
	)
	if _q.withFaction != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, factionrequiredtag.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FactionRequiredTag).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FactionRequiredTag{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withFaction; query != nil {
		if err := _q.loadFaction(ctx, query, nodes, nil,
			func(n *FactionRequiredTag, e *Faction) { n.Edges.Faction = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *FactionRequiredTagQuery) loadFaction(ctx context.Context, query *FactionQuery, nodes []*FactionRequiredTag, init func(*FactionRequiredTag), assign func(*FactionRequiredTag, *Faction)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FactionRequiredTag)
	for i := range nodes {
		if nodes[i].faction_required_tags == nil {
			continue
		}
		fk := *nodes[i].faction_required_tags
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(faction.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "faction_required_tags" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *FactionRequiredTagQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *FactionRequiredTagQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(factionrequiredtag.Table, factionrequiredtag.Columns, sqlgraph.NewFieldSpec(factionrequiredtag.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, factionrequiredtag.FieldID)
		for i := range fields {
			if fields[i] != factionrequiredtag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *FactionRequiredTagQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(factionrequiredtag.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = factionrequiredtag.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FactionRequiredTagGroupBy is the group-by builder for FactionRequiredTag entities.
type FactionRequiredTagGroupBy struct {
	selector
	build *FactionRequiredTagQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *FactionRequiredTagGroupBy) Aggregate(fns ...AggregateFunc) *FactionRequiredTagGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *FactionRequiredTagGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FactionRequiredTagQuery, *FactionRequiredTagGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *FactionRequiredTagGroupBy) sqlScan(ctx context.Context, root *FactionRequiredTagQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FactionRequiredTagSelect is the builder for selecting fields of FactionRequiredTag entities.
type FactionRequiredTagSelect struct {
	*FactionRequiredTagQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *FactionRequiredTagSelect) Aggregate(fns ...AggregateFunc) *FactionRequiredTagSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *FactionRequiredTagSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FactionRequiredTagQuery, *FactionRequiredTagSelect](ctx, _s.FactionRequiredTagQuery, _s, _s.inters, v)
}

func (_s *FactionRequiredTagSelect) sqlScan(ctx context.Context, root *FactionRequiredTagQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
