// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"herbst-server/db/character"
	"herbst-server/db/predicate"
	"herbst-server/db/quest"
	"herbst-server/db/questprogress"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestProgressQuery is the builder for querying QuestProgress entities.
type QuestProgressQuery struct {
	config
	ctx           *QueryContext
	order         []questprogress.OrderOption
	inters        []Interceptor
	predicates    []predicate.QuestProgress
	withCharacter *CharacterQuery
	withQuest     *QuestQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuestProgressQuery builder.
func (_q *QuestProgressQuery) Where(ps ...predicate.QuestProgress) *QuestProgressQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *QuestProgressQuery) Limit(limit int) *QuestProgressQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *QuestProgressQuery) Offset(offset int) *QuestProgressQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *QuestProgressQuery) Unique(unique bool) *QuestProgressQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *QuestProgressQuery) Order(o ...questprogress.OrderOption) *QuestProgressQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCharacter chains the current query on the "character" edge.
func (_q *QuestProgressQuery) QueryCharacter() *CharacterQuery {
	query := (&CharacterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(questprogress.Table, questprogress.FieldID, selector),
			sqlgraph.To(character.Table, character.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, questprogress.CharacterTable, questprogress.CharacterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryQuest chains the current query on the "quest" edge.
func (_q *QuestProgressQuery) QueryQuest() *QuestQuery {
	query := (&QuestClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(questprogress.Table, questprogress.FieldID, selector),
			sqlgraph.To(quest.Table, quest.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, questprogress.QuestTable, questprogress.QuestColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QuestProgress entity from the query.
// Returns a *NotFoundError when no QuestProgress was found.
func (_q *QuestProgressQuery) First(ctx context.Context) (*QuestProgress, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{questprogress.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *QuestProgressQuery) FirstX(ctx context.Context) *QuestProgress {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QuestProgress ID from the query.
// Returns a *NotFoundError when no QuestProgress ID was found.
func (_q *QuestProgressQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{questprogress.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *QuestProgressQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QuestProgress entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QuestProgress entity is found.
// Returns a *NotFoundError when no QuestProgress entities are found.
func (_q *QuestProgressQuery) Only(ctx context.Context) (*QuestProgress, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{questprogress.Label}
	default:
		return nil, &NotSingularError{questprogress.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *QuestProgressQuery) OnlyX(ctx context.Context) *QuestProgress {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QuestProgress ID in the query.
// Returns a *NotSingularError when more than one QuestProgress ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *QuestProgressQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{questprogress.Label}
	default:
		err = &NotSingularError{questprogress.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *QuestProgressQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QuestProgresses.
func (_q *QuestProgressQuery) All(ctx context.Context) ([]*QuestProgress, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QuestProgress, *QuestProgressQuery]()
	return withInterceptors[[]*QuestProgress](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *QuestProgressQuery) AllX(ctx context.Context) []*QuestProgress {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QuestProgress IDs.
func (_q *QuestProgressQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(questprogress.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *QuestProgressQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *QuestProgressQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*QuestProgressQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *QuestProgressQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *QuestProgressQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *QuestProgressQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuestProgressQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *QuestProgressQuery) Clone() *QuestProgressQuery {
	if _q == nil {
		return nil
	}
	return &QuestProgressQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]questprogress.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.QuestProgress{}, _q.predicates...),
		withCharacter: _q.withCharacter.Clone(),
		withQuest:     _q.withQuest.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCharacter tells the query-builder to eager-load the nodes that are connected to
// the "character" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuestProgressQuery) WithCharacter(opts ...func(*CharacterQuery)) *QuestProgressQuery {
	query := (&CharacterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCharacter = query
	return _q
}

// WithQuest tells the query-builder to eager-load the nodes that are connected to
// the "quest" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuestProgressQuery) WithQuest(opts ...func(*QuestQuery)) *QuestProgressQuery {
	query := (&QuestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withQuest = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status questprogress.Status `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QuestProgress.Query().
//		GroupBy(questprogress.FieldStatus).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (_q *QuestProgressQuery) GroupBy(field string, fields ...string) *QuestProgressGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QuestProgressGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = questprogress.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status questprogress.Status `json:"status,omitempty"`
//	}
//
//	client.QuestProgress.Query().
//		Select(questprogress.FieldStatus).
//		Scan(ctx, &v)
func (_q *QuestProgressQuery) Select(fields ...string) *QuestProgressSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &QuestProgressSelect{QuestProgressQuery: _q}
	sbuild.label = questprogress.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QuestProgressSelect configured with the given aggregations.
func (_q *QuestProgressQuery) Aggregate(fns ...AggregateFunc) *QuestProgressSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *QuestProgressQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !questprogress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *QuestProgressQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QuestProgress, error) {
	var (
		nodes       = []*QuestProgress{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withCharacter != nil,
			_q.withQuest != nil,
		}
	)
	if _q.withCharacter != nil || _q.withQuest != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, questprogress.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QuestProgress).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QuestProgress{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCharacter; query != nil {
		if err := _q.loadCharacter(ctx, query, nodes, nil,
			func(n *QuestProgress, e *Character) { n.Edges.Character = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withQuest; query != nil {
		if err := _q.loadQuest(ctx, query, nodes, nil,
			func(n *QuestProgress, e *Quest) { n.Edges.Quest = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *QuestProgressQuery) loadCharacter(ctx context.Context, query *CharacterQuery, nodes []*QuestProgress, init func(*QuestProgress), assign func(*QuestProgress, *Character)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*QuestProgress)
	for i := range nodes {
		if nodes[i].character_quest_progress == nil {
			continue
		}
		fk := *nodes[i].character_quest_progress
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(character.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "character_quest_progress" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *QuestProgressQuery) loadQuest(ctx context.Context, query *QuestQuery, nodes []*QuestProgress, init func(*QuestProgress), assign func(*QuestProgress, *Quest)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*QuestProgress)
	for i := range nodes {
		if nodes[i].quest_progress == nil {
			continue
		}
		fk := *nodes[i].quest_progress
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(quest.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "quest_progress" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *QuestProgressQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *QuestProgressQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(questprogress.Table, questprogress.Columns, sqlgraph.NewFieldSpec(questprogress.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, questprogress.FieldID)
		for i := range fields {
			if fields[i] != questprogress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *QuestProgressQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(questprogress.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = questprogress.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QuestProgressGroupBy is the group-by builder for QuestProgress entities.
type QuestProgressGroupBy struct {
	selector
	build *QuestProgressQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *QuestProgressGroupBy) Aggregate(fns ...AggregateFunc) *QuestProgressGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *QuestProgressGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuestProgressQuery, *QuestProgressGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *QuestProgressGroupBy) sqlScan(ctx context.Context, root *QuestProgressQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QuestProgressSelect is the builder for selecting fields of QuestProgress entities.
type QuestProgressSelect struct {
	*QuestProgressQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *QuestProgressSelect) Aggregate(fns ...AggregateFunc) *QuestProgressSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *QuestProgressSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuestProgressQuery, *QuestProgressSelect](ctx, _s.QuestProgressQuery, _s, _s.inters, v)
}

func (_s *QuestProgressSelect) sqlScan(ctx context.Context, root *QuestProgressQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
