// Code generated by ent, DO NOT EDIT.

package db

import (
	"herbst-server/db/ability"
	"herbst-server/db/abilityeffect"
	"herbst-server/db/achievement"
	"herbst-server/db/activeeffect"
	"herbst-server/db/applog"
	"herbst-server/db/character"
	"herbst-server/db/charactercompetency"
	"herbst-server/db/characterfaction"
	"herbst-server/db/charactertag"
	"herbst-server/db/competencycategory"
	"herbst-server/db/competencylevelthreshold"
	"herbst-server/db/damagelog"
	"herbst-server/db/effect"
	"herbst-server/db/effecthook"
	"herbst-server/db/equipment"
	"herbst-server/db/equipmenttemplate"
	"herbst-server/db/factioncategory"
	"herbst-server/db/npctemplate"
	"herbst-server/db/race"
	"herbst-server/db/room"
	"herbst-server/db/schema"
	"herbst-server/db/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	abilityFields := schema.Ability{}.Fields()
	_ = abilityFields
	// abilityDescCost is the schema descriptor for cost field.
	abilityDescCost := abilityFields[3].Descriptor()
	// ability.DefaultCost holds the default value on creation for the cost field.
	ability.DefaultCost = abilityDescCost.Default.(int)
	// abilityDescCooldown is the schema descriptor for cooldown field.
	abilityDescCooldown := abilityFields[4].Descriptor()
	// ability.DefaultCooldown holds the default value on creation for the cooldown field.
	ability.DefaultCooldown = abilityDescCooldown.Default.(int)
	// abilityDescEffectType is the schema descriptor for effect_type field.
	abilityDescEffectType := abilityFields[6].Descriptor()
	// ability.DefaultEffectType holds the default value on creation for the effect_type field.
	ability.DefaultEffectType = abilityDescEffectType.Default.(string)
	// abilityDescEffectValue is the schema descriptor for effect_value field.
	abilityDescEffectValue := abilityFields[7].Descriptor()
	// ability.DefaultEffectValue holds the default value on creation for the effect_value field.
	ability.DefaultEffectValue = abilityDescEffectValue.Default.(int)
	// abilityDescEffectDuration is the schema descriptor for effect_duration field.
	abilityDescEffectDuration := abilityFields[8].Descriptor()
	// ability.DefaultEffectDuration holds the default value on creation for the effect_duration field.
	ability.DefaultEffectDuration = abilityDescEffectDuration.Default.(int)
	// abilityDescScalingPercentPerPoint is the schema descriptor for scaling_percent_per_point field.
	abilityDescScalingPercentPerPoint := abilityFields[10].Descriptor()
	// ability.DefaultScalingPercentPerPoint holds the default value on creation for the scaling_percent_per_point field.
	ability.DefaultScalingPercentPerPoint = abilityDescScalingPercentPerPoint.Default.(float64)
	// abilityDescManaCost is the schema descriptor for mana_cost field.
	abilityDescManaCost := abilityFields[11].Descriptor()
	// ability.DefaultManaCost holds the default value on creation for the mana_cost field.
	ability.DefaultManaCost = abilityDescManaCost.Default.(int)
	// abilityDescStaminaCost is the schema descriptor for stamina_cost field.
	abilityDescStaminaCost := abilityFields[12].Descriptor()
	// ability.DefaultStaminaCost holds the default value on creation for the stamina_cost field.
	ability.DefaultStaminaCost = abilityDescStaminaCost.Default.(int)
	// abilityDescHpCost is the schema descriptor for hp_cost field.
	abilityDescHpCost := abilityFields[13].Descriptor()
	// ability.DefaultHpCost holds the default value on creation for the hp_cost field.
	ability.DefaultHpCost = abilityDescHpCost.Default.(int)
	// abilityDescAbilityClass is the schema descriptor for ability_class field.
	abilityDescAbilityClass := abilityFields[16].Descriptor()
	// ability.DefaultAbilityClass holds the default value on creation for the ability_class field.
	ability.DefaultAbilityClass = abilityDescAbilityClass.Default.(string)
	// abilityDescProcChance is the schema descriptor for proc_chance field.
	abilityDescProcChance := abilityFields[17].Descriptor()
	// ability.DefaultProcChance holds the default value on creation for the proc_chance field.
	ability.DefaultProcChance = abilityDescProcChance.Default.(float64)
	// abilityDescCooldownSeconds is the schema descriptor for cooldown_seconds field.
	abilityDescCooldownSeconds := abilityFields[19].Descriptor()
	// ability.DefaultCooldownSeconds holds the default value on creation for the cooldown_seconds field.
	ability.DefaultCooldownSeconds = abilityDescCooldownSeconds.Default.(int)
	abilityeffectFields := schema.AbilityEffect{}.Fields()
	_ = abilityeffectFields
	// abilityeffectDescDamageSubtype is the schema descriptor for damage_subtype field.
	abilityeffectDescDamageSubtype := abilityeffectFields[1].Descriptor()
	// abilityeffect.DefaultDamageSubtype holds the default value on creation for the damage_subtype field.
	abilityeffect.DefaultDamageSubtype = abilityeffectDescDamageSubtype.Default.(string)
	// abilityeffectDescTarget is the schema descriptor for target field.
	abilityeffectDescTarget := abilityeffectFields[2].Descriptor()
	// abilityeffect.DefaultTarget holds the default value on creation for the target field.
	abilityeffect.DefaultTarget = abilityeffectDescTarget.Default.(string)
	// abilityeffectDescValue is the schema descriptor for value field.
	abilityeffectDescValue := abilityeffectFields[3].Descriptor()
	// abilityeffect.DefaultValue holds the default value on creation for the value field.
	abilityeffect.DefaultValue = abilityeffectDescValue.Default.(int)
	// abilityeffectDescDuration is the schema descriptor for duration field.
	abilityeffectDescDuration := abilityeffectFields[4].Descriptor()
	// abilityeffect.DefaultDuration holds the default value on creation for the duration field.
	abilityeffect.DefaultDuration = abilityeffectDescDuration.Default.(int)
	// abilityeffectDescScalingRatio is the schema descriptor for scaling_ratio field.
	abilityeffectDescScalingRatio := abilityeffectFields[6].Descriptor()
	// abilityeffect.DefaultScalingRatio holds the default value on creation for the scaling_ratio field.
	abilityeffect.DefaultScalingRatio = abilityeffectDescScalingRatio.Default.(float64)
	// abilityeffectDescSortOrder is the schema descriptor for sort_order field.
	abilityeffectDescSortOrder := abilityeffectFields[7].Descriptor()
	// abilityeffect.DefaultSortOrder holds the default value on creation for the sort_order field.
	abilityeffect.DefaultSortOrder = abilityeffectDescSortOrder.Default.(int)
	achievementFields := schema.Achievement{}.Fields()
	_ = achievementFields
	// achievementDescDescription is the schema descriptor for description field.
	achievementDescDescription := achievementFields[1].Descriptor()
	// achievement.DefaultDescription holds the default value on creation for the description field.
	achievement.DefaultDescription = achievementDescDescription.Default.(string)
	// achievementDescXpReward is the schema descriptor for xp_reward field.
	achievementDescXpReward := achievementFields[3].Descriptor()
	// achievement.DefaultXpReward holds the default value on creation for the xp_reward field.
	achievement.DefaultXpReward = achievementDescXpReward.Default.(int)
	activeeffectFields := schema.ActiveEffect{}.Fields()
	_ = activeeffectFields
	// activeeffectDescAppliedByID is the schema descriptor for applied_by_id field.
	activeeffectDescAppliedByID := activeeffectFields[2].Descriptor()
	// activeeffect.DefaultAppliedByID holds the default value on creation for the applied_by_id field.
	activeeffect.DefaultAppliedByID = activeeffectDescAppliedByID.Default.(int)
	// activeeffectDescStackCount is the schema descriptor for stack_count field.
	activeeffectDescStackCount := activeeffectFields[3].Descriptor()
	// activeeffect.DefaultStackCount holds the default value on creation for the stack_count field.
	activeeffect.DefaultStackCount = activeeffectDescStackCount.Default.(int)
	// activeeffectDescStartedAt is the schema descriptor for started_at field.
	activeeffectDescStartedAt := activeeffectFields[4].Descriptor()
	// activeeffect.DefaultStartedAt holds the default value on creation for the started_at field.
	activeeffect.DefaultStartedAt = activeeffectDescStartedAt.Default.(func() time.Time)
	// activeeffectDescIsActive is the schema descriptor for is_active field.
	activeeffectDescIsActive := activeeffectFields[6].Descriptor()
	// activeeffect.DefaultIsActive holds the default value on creation for the is_active field.
	activeeffect.DefaultIsActive = activeeffectDescIsActive.Default.(bool)
	applogFields := schema.AppLog{}.Fields()
	_ = applogFields
	// applogDescCreatedAt is the schema descriptor for created_at field.
	applogDescCreatedAt := applogFields[8].Descriptor()
	// applog.DefaultCreatedAt holds the default value on creation for the created_at field.
	applog.DefaultCreatedAt = applogDescCreatedAt.Default.(func() time.Time)
	characterFields := schema.Character{}.Fields()
	_ = characterFields
	// characterDescIsNPC is the schema descriptor for isNPC field.
	characterDescIsNPC := characterFields[2].Descriptor()
	// character.DefaultIsNPC holds the default value on creation for the isNPC field.
	character.DefaultIsNPC = characterDescIsNPC.Default.(bool)
	// characterDescRespawnRoomId is the schema descriptor for respawnRoomId field.
	characterDescRespawnRoomId := characterFields[5].Descriptor()
	// character.DefaultRespawnRoomId holds the default value on creation for the respawnRoomId field.
	character.DefaultRespawnRoomId = characterDescRespawnRoomId.Default.(int)
	// characterDescIsAdmin is the schema descriptor for is_admin field.
	characterDescIsAdmin := characterFields[6].Descriptor()
	// character.DefaultIsAdmin holds the default value on creation for the is_admin field.
	character.DefaultIsAdmin = characterDescIsAdmin.Default.(bool)
	// characterDescIsImmortal is the schema descriptor for is_immortal field.
	characterDescIsImmortal := characterFields[7].Descriptor()
	// character.DefaultIsImmortal holds the default value on creation for the is_immortal field.
	character.DefaultIsImmortal = characterDescIsImmortal.Default.(bool)
	// characterDescIsTest is the schema descriptor for is_test field.
	characterDescIsTest := characterFields[8].Descriptor()
	// character.DefaultIsTest holds the default value on creation for the is_test field.
	character.DefaultIsTest = characterDescIsTest.Default.(bool)
	// characterDescIsInstance is the schema descriptor for is_instance field.
	characterDescIsInstance := characterFields[9].Descriptor()
	// character.DefaultIsInstance holds the default value on creation for the is_instance field.
	character.DefaultIsInstance = characterDescIsInstance.Default.(bool)
	// characterDescInstanceNumber is the schema descriptor for instance_number field.
	characterDescInstanceNumber := characterFields[10].Descriptor()
	// character.DefaultInstanceNumber holds the default value on creation for the instance_number field.
	character.DefaultInstanceNumber = characterDescInstanceNumber.Default.(int)
	// characterDescNpcSkillCooldown is the schema descriptor for npc_skill_cooldown field.
	characterDescNpcSkillCooldown := characterFields[13].Descriptor()
	// character.DefaultNpcSkillCooldown holds the default value on creation for the npc_skill_cooldown field.
	character.DefaultNpcSkillCooldown = characterDescNpcSkillCooldown.Default.(int)
	// characterDescHitpoints is the schema descriptor for hitpoints field.
	characterDescHitpoints := characterFields[14].Descriptor()
	// character.DefaultHitpoints holds the default value on creation for the hitpoints field.
	character.DefaultHitpoints = characterDescHitpoints.Default.(int)
	// characterDescMaxHitpoints is the schema descriptor for max_hitpoints field.
	characterDescMaxHitpoints := characterFields[15].Descriptor()
	// character.DefaultMaxHitpoints holds the default value on creation for the max_hitpoints field.
	character.DefaultMaxHitpoints = characterDescMaxHitpoints.Default.(int)
	// characterDescStamina is the schema descriptor for stamina field.
	characterDescStamina := characterFields[16].Descriptor()
	// character.DefaultStamina holds the default value on creation for the stamina field.
	character.DefaultStamina = characterDescStamina.Default.(int)
	// characterDescMaxStamina is the schema descriptor for max_stamina field.
	characterDescMaxStamina := characterFields[17].Descriptor()
	// character.DefaultMaxStamina holds the default value on creation for the max_stamina field.
	character.DefaultMaxStamina = characterDescMaxStamina.Default.(int)
	// characterDescMana is the schema descriptor for mana field.
	characterDescMana := characterFields[18].Descriptor()
	// character.DefaultMana holds the default value on creation for the mana field.
	character.DefaultMana = characterDescMana.Default.(int)
	// characterDescMaxMana is the schema descriptor for max_mana field.
	characterDescMaxMana := characterFields[19].Descriptor()
	// character.DefaultMaxMana holds the default value on creation for the max_mana field.
	character.DefaultMaxMana = characterDescMaxMana.Default.(int)
	// characterDescRace is the schema descriptor for race field.
	characterDescRace := characterFields[20].Descriptor()
	// character.DefaultRace holds the default value on creation for the race field.
	character.DefaultRace = characterDescRace.Default.(string)
	// characterDescClass is the schema descriptor for class field.
	characterDescClass := characterFields[21].Descriptor()
	// character.DefaultClass holds the default value on creation for the class field.
	character.DefaultClass = characterDescClass.Default.(string)
	// characterDescLevel is the schema descriptor for level field.
	characterDescLevel := characterFields[23].Descriptor()
	// character.DefaultLevel holds the default value on creation for the level field.
	character.DefaultLevel = characterDescLevel.Default.(int)
	// characterDescXp is the schema descriptor for xp field.
	characterDescXp := characterFields[24].Descriptor()
	// character.DefaultXp holds the default value on creation for the xp field.
	character.DefaultXp = characterDescXp.Default.(int)
	// characterDescConstitution is the schema descriptor for constitution field.
	characterDescConstitution := characterFields[27].Descriptor()
	// character.DefaultConstitution holds the default value on creation for the constitution field.
	character.DefaultConstitution = characterDescConstitution.Default.(int)
	// characterDescStrength is the schema descriptor for strength field.
	characterDescStrength := characterFields[30].Descriptor()
	// character.DefaultStrength holds the default value on creation for the strength field.
	character.DefaultStrength = characterDescStrength.Default.(int)
	// characterDescDexterity is the schema descriptor for dexterity field.
	characterDescDexterity := characterFields[31].Descriptor()
	// character.DefaultDexterity holds the default value on creation for the dexterity field.
	character.DefaultDexterity = characterDescDexterity.Default.(int)
	// characterDescIntelligence is the schema descriptor for intelligence field.
	characterDescIntelligence := characterFields[32].Descriptor()
	// character.DefaultIntelligence holds the default value on creation for the intelligence field.
	character.DefaultIntelligence = characterDescIntelligence.Default.(int)
	// characterDescWisdom is the schema descriptor for wisdom field.
	characterDescWisdom := characterFields[33].Descriptor()
	// character.DefaultWisdom holds the default value on creation for the wisdom field.
	character.DefaultWisdom = characterDescWisdom.Default.(int)
	// characterDescSkillBlades is the schema descriptor for skill_blades field.
	characterDescSkillBlades := characterFields[34].Descriptor()
	// character.DefaultSkillBlades holds the default value on creation for the skill_blades field.
	character.DefaultSkillBlades = characterDescSkillBlades.Default.(int)
	// characterDescSkillStaves is the schema descriptor for skill_staves field.
	characterDescSkillStaves := characterFields[35].Descriptor()
	// character.DefaultSkillStaves holds the default value on creation for the skill_staves field.
	character.DefaultSkillStaves = characterDescSkillStaves.Default.(int)
	// characterDescSkillKnives is the schema descriptor for skill_knives field.
	characterDescSkillKnives := characterFields[36].Descriptor()
	// character.DefaultSkillKnives holds the default value on creation for the skill_knives field.
	character.DefaultSkillKnives = characterDescSkillKnives.Default.(int)
	// characterDescSkillMartial is the schema descriptor for skill_martial field.
	characterDescSkillMartial := characterFields[37].Descriptor()
	// character.DefaultSkillMartial holds the default value on creation for the skill_martial field.
	character.DefaultSkillMartial = characterDescSkillMartial.Default.(int)
	// characterDescSkillBrawling is the schema descriptor for skill_brawling field.
	characterDescSkillBrawling := characterFields[38].Descriptor()
	// character.DefaultSkillBrawling holds the default value on creation for the skill_brawling field.
	character.DefaultSkillBrawling = characterDescSkillBrawling.Default.(int)
	// characterDescSkillTech is the schema descriptor for skill_tech field.
	characterDescSkillTech := characterFields[39].Descriptor()
	// character.DefaultSkillTech holds the default value on creation for the skill_tech field.
	character.DefaultSkillTech = characterDescSkillTech.Default.(int)
	// characterDescSkillLightArmor is the schema descriptor for skill_light_armor field.
	characterDescSkillLightArmor := characterFields[40].Descriptor()
	// character.DefaultSkillLightArmor holds the default value on creation for the skill_light_armor field.
	character.DefaultSkillLightArmor = characterDescSkillLightArmor.Default.(int)
	// characterDescSkillClothArmor is the schema descriptor for skill_cloth_armor field.
	characterDescSkillClothArmor := characterFields[41].Descriptor()
	// character.DefaultSkillClothArmor holds the default value on creation for the skill_cloth_armor field.
	character.DefaultSkillClothArmor = characterDescSkillClothArmor.Default.(int)
	// characterDescSkillHeavyArmor is the schema descriptor for skill_heavy_armor field.
	characterDescSkillHeavyArmor := characterFields[42].Descriptor()
	// character.DefaultSkillHeavyArmor holds the default value on creation for the skill_heavy_armor field.
	character.DefaultSkillHeavyArmor = characterDescSkillHeavyArmor.Default.(int)
	charactercompetencyFields := schema.CharacterCompetency{}.Fields()
	_ = charactercompetencyFields
	// charactercompetencyDescXp is the schema descriptor for xp field.
	charactercompetencyDescXp := charactercompetencyFields[0].Descriptor()
	// charactercompetency.DefaultXp holds the default value on creation for the xp field.
	charactercompetency.DefaultXp = charactercompetencyDescXp.Default.(int)
	// charactercompetencyDescLevel is the schema descriptor for level field.
	charactercompetencyDescLevel := charactercompetencyFields[1].Descriptor()
	// charactercompetency.DefaultLevel holds the default value on creation for the level field.
	charactercompetency.DefaultLevel = charactercompetencyDescLevel.Default.(int)
	characterfactionFields := schema.CharacterFaction{}.Fields()
	_ = characterfactionFields
	// characterfactionDescReputation is the schema descriptor for reputation field.
	characterfactionDescReputation := characterfactionFields[0].Descriptor()
	// characterfaction.DefaultReputation holds the default value on creation for the reputation field.
	characterfaction.DefaultReputation = characterfactionDescReputation.Default.(int)
	// characterfactionDescStatus is the schema descriptor for status field.
	characterfactionDescStatus := characterfactionFields[1].Descriptor()
	// characterfaction.DefaultStatus holds the default value on creation for the status field.
	characterfaction.DefaultStatus = characterfactionDescStatus.Default.(string)
	// characterfactionDescJoinedAt is the schema descriptor for joined_at field.
	characterfactionDescJoinedAt := characterfactionFields[2].Descriptor()
	// characterfaction.DefaultJoinedAt holds the default value on creation for the joined_at field.
	characterfaction.DefaultJoinedAt = characterfactionDescJoinedAt.Default.(func() time.Time)
	charactertagFields := schema.CharacterTag{}.Fields()
	_ = charactertagFields
	// charactertagDescSource is the schema descriptor for source field.
	charactertagDescSource := charactertagFields[1].Descriptor()
	// charactertag.DefaultSource holds the default value on creation for the source field.
	charactertag.DefaultSource = charactertagDescSource.Default.(string)
	// charactertagDescEarnedAt is the schema descriptor for earned_at field.
	charactertagDescEarnedAt := charactertagFields[2].Descriptor()
	// charactertag.DefaultEarnedAt holds the default value on creation for the earned_at field.
	charactertag.DefaultEarnedAt = charactertagDescEarnedAt.Default.(func() time.Time)
	competencycategoryFields := schema.CompetencyCategory{}.Fields()
	_ = competencycategoryFields
	// competencycategoryDescXpMultiplier is the schema descriptor for xp_multiplier field.
	competencycategoryDescXpMultiplier := competencycategoryFields[2].Descriptor()
	// competencycategory.DefaultXpMultiplier holds the default value on creation for the xp_multiplier field.
	competencycategory.DefaultXpMultiplier = competencycategoryDescXpMultiplier.Default.(float64)
	competencylevelthresholdFields := schema.CompetencyLevelThreshold{}.Fields()
	_ = competencylevelthresholdFields
	// competencylevelthresholdDescDamageMultiplier is the schema descriptor for damage_multiplier field.
	competencylevelthresholdDescDamageMultiplier := competencylevelthresholdFields[3].Descriptor()
	// competencylevelthreshold.DefaultDamageMultiplier holds the default value on creation for the damage_multiplier field.
	competencylevelthreshold.DefaultDamageMultiplier = competencylevelthresholdDescDamageMultiplier.Default.(float64)
	// competencylevelthresholdDescDefenseMultiplier is the schema descriptor for defense_multiplier field.
	competencylevelthresholdDescDefenseMultiplier := competencylevelthresholdFields[4].Descriptor()
	// competencylevelthreshold.DefaultDefenseMultiplier holds the default value on creation for the defense_multiplier field.
	competencylevelthreshold.DefaultDefenseMultiplier = competencylevelthresholdDescDefenseMultiplier.Default.(float64)
	damagelogFields := schema.DamageLog{}.Fields()
	_ = damagelogFields
	// damagelogDescCreatedAt is the schema descriptor for created_at field.
	damagelogDescCreatedAt := damagelogFields[3].Descriptor()
	// damagelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	damagelog.DefaultCreatedAt = damagelogDescCreatedAt.Default.(func() time.Time)
	effectFields := schema.Effect{}.Fields()
	_ = effectFields
	// effectDescDescription is the schema descriptor for description field.
	effectDescDescription := effectFields[1].Descriptor()
	// effect.DefaultDescription holds the default value on creation for the description field.
	effect.DefaultDescription = effectDescDescription.Default.(string)
	// effectDescParameters is the schema descriptor for parameters field.
	effectDescParameters := effectFields[3].Descriptor()
	// effect.DefaultParameters holds the default value on creation for the parameters field.
	effect.DefaultParameters = effectDescParameters.Default.(map[string]interface{})
	// effectDescStackMode is the schema descriptor for stack_mode field.
	effectDescStackMode := effectFields[4].Descriptor()
	// effect.DefaultStackMode holds the default value on creation for the stack_mode field.
	effect.DefaultStackMode = effectDescStackMode.Default.(string)
	// effectDescStackLimit is the schema descriptor for stack_limit field.
	effectDescStackLimit := effectFields[5].Descriptor()
	// effect.DefaultStackLimit holds the default value on creation for the stack_limit field.
	effect.DefaultStackLimit = effectDescStackLimit.Default.(int)
	// effectDescIsPermanent is the schema descriptor for is_permanent field.
	effectDescIsPermanent := effectFields[6].Descriptor()
	// effect.DefaultIsPermanent holds the default value on creation for the is_permanent field.
	effect.DefaultIsPermanent = effectDescIsPermanent.Default.(bool)
	// effectDescDurationSecs is the schema descriptor for duration_secs field.
	effectDescDurationSecs := effectFields[7].Descriptor()
	// effect.DefaultDurationSecs holds the default value on creation for the duration_secs field.
	effect.DefaultDurationSecs = effectDescDurationSecs.Default.(int)
	// effectDescMessages is the schema descriptor for messages field.
	effectDescMessages := effectFields[8].Descriptor()
	// effect.DefaultMessages holds the default value on creation for the messages field.
	effect.DefaultMessages = effectDescMessages.Default.(map[string]string)
	effecthookFields := schema.EffectHook{}.Fields()
	_ = effecthookFields
	// effecthookDescTarget is the schema descriptor for target field.
	effecthookDescTarget := effecthookFields[2].Descriptor()
	// effecthook.DefaultTarget holds the default value on creation for the target field.
	effecthook.DefaultTarget = effecthookDescTarget.Default.(string)
	// effecthookDescEnabled is the schema descriptor for enabled field.
	effecthookDescEnabled := effecthookFields[4].Descriptor()
	// effecthook.DefaultEnabled holds the default value on creation for the enabled field.
	effecthook.DefaultEnabled = effecthookDescEnabled.Default.(bool)
	equipmentFields := schema.Equipment{}.Fields()
	_ = equipmentFields
	// equipmentDescLevel is the schema descriptor for level field.
	equipmentDescLevel := equipmentFields[3].Descriptor()
	// equipment.DefaultLevel holds the default value on creation for the level field.
	equipment.DefaultLevel = equipmentDescLevel.Default.(int)
	// equipmentDescWeight is the schema descriptor for weight field.
	equipmentDescWeight := equipmentFields[4].Descriptor()
	// equipment.DefaultWeight holds the default value on creation for the weight field.
	equipment.DefaultWeight = equipmentDescWeight.Default.(int)
	// equipmentDescIsEquipped is the schema descriptor for isEquipped field.
	equipmentDescIsEquipped := equipmentFields[5].Descriptor()
	// equipment.DefaultIsEquipped holds the default value on creation for the isEquipped field.
	equipment.DefaultIsEquipped = equipmentDescIsEquipped.Default.(bool)
	// equipmentDescIsImmovable is the schema descriptor for isImmovable field.
	equipmentDescIsImmovable := equipmentFields[6].Descriptor()
	// equipment.DefaultIsImmovable holds the default value on creation for the isImmovable field.
	equipment.DefaultIsImmovable = equipmentDescIsImmovable.Default.(bool)
	// equipmentDescColor is the schema descriptor for color field.
	equipmentDescColor := equipmentFields[7].Descriptor()
	// equipment.DefaultColor holds the default value on creation for the color field.
	equipment.DefaultColor = equipmentDescColor.Default.(string)
	// equipmentDescIsVisible is the schema descriptor for isVisible field.
	equipmentDescIsVisible := equipmentFields[8].Descriptor()
	// equipment.DefaultIsVisible holds the default value on creation for the isVisible field.
	equipment.DefaultIsVisible = equipmentDescIsVisible.Default.(bool)
	// equipmentDescItemType is the schema descriptor for itemType field.
	equipmentDescItemType := equipmentFields[9].Descriptor()
	// equipment.DefaultItemType holds the default value on creation for the itemType field.
	equipment.DefaultItemType = equipmentDescItemType.Default.(string)
	// equipmentDescEffectType is the schema descriptor for effect_type field.
	equipmentDescEffectType := equipmentFields[12].Descriptor()
	// equipment.DefaultEffectType holds the default value on creation for the effect_type field.
	equipment.DefaultEffectType = equipmentDescEffectType.Default.(string)
	// equipmentDescEffectValue is the schema descriptor for effect_value field.
	equipmentDescEffectValue := equipmentFields[13].Descriptor()
	// equipment.DefaultEffectValue holds the default value on creation for the effect_value field.
	equipment.DefaultEffectValue = equipmentDescEffectValue.Default.(int)
	// equipmentDescEffectDuration is the schema descriptor for effect_duration field.
	equipmentDescEffectDuration := equipmentFields[14].Descriptor()
	// equipment.DefaultEffectDuration holds the default value on creation for the effect_duration field.
	equipment.DefaultEffectDuration = equipmentDescEffectDuration.Default.(int)
	// equipmentDescHealing is the schema descriptor for healing field.
	equipmentDescHealing := equipmentFields[15].Descriptor()
	// equipment.DefaultHealing holds the default value on creation for the healing field.
	equipment.DefaultHealing = equipmentDescHealing.Default.(int)
	// equipmentDescEffect is the schema descriptor for effect field.
	equipmentDescEffect := equipmentFields[16].Descriptor()
	// equipment.DefaultEffect holds the default value on creation for the effect field.
	equipment.DefaultEffect = equipmentDescEffect.Default.(string)
	// equipmentDescIsContainer is the schema descriptor for isContainer field.
	equipmentDescIsContainer := equipmentFields[17].Descriptor()
	// equipment.DefaultIsContainer holds the default value on creation for the isContainer field.
	equipment.DefaultIsContainer = equipmentDescIsContainer.Default.(bool)
	// equipmentDescContainerCapacity is the schema descriptor for containerCapacity field.
	equipmentDescContainerCapacity := equipmentFields[18].Descriptor()
	// equipment.DefaultContainerCapacity holds the default value on creation for the containerCapacity field.
	equipment.DefaultContainerCapacity = equipmentDescContainerCapacity.Default.(int)
	// equipmentDescIsLocked is the schema descriptor for isLocked field.
	equipmentDescIsLocked := equipmentFields[19].Descriptor()
	// equipment.DefaultIsLocked holds the default value on creation for the isLocked field.
	equipment.DefaultIsLocked = equipmentDescIsLocked.Default.(bool)
	// equipmentDescContainedItems is the schema descriptor for containedItems field.
	equipmentDescContainedItems := equipmentFields[21].Descriptor()
	// equipment.DefaultContainedItems holds the default value on creation for the containedItems field.
	equipment.DefaultContainedItems = equipmentDescContainedItems.Default.(string)
	// equipmentDescRevealCondition is the schema descriptor for revealCondition field.
	equipmentDescRevealCondition := equipmentFields[22].Descriptor()
	// equipment.DefaultRevealCondition holds the default value on creation for the revealCondition field.
	equipment.DefaultRevealCondition = equipmentDescRevealCondition.Default.(string)
	// equipmentDescArmorRating is the schema descriptor for armor_rating field.
	equipmentDescArmorRating := equipmentFields[24].Descriptor()
	// equipment.DefaultArmorRating holds the default value on creation for the armor_rating field.
	equipment.DefaultArmorRating = equipmentDescArmorRating.Default.(int)
	// equipmentDescArmorType is the schema descriptor for armor_type field.
	equipmentDescArmorType := equipmentFields[25].Descriptor()
	// equipment.DefaultArmorType holds the default value on creation for the armor_type field.
	equipment.DefaultArmorType = equipmentDescArmorType.Default.(string)
	// equipmentDescStats is the schema descriptor for stats field.
	equipmentDescStats := equipmentFields[26].Descriptor()
	// equipment.DefaultStats holds the default value on creation for the stats field.
	equipment.DefaultStats = equipmentDescStats.Default.(map[string]int)
	// equipmentDescRarity is the schema descriptor for rarity field.
	equipmentDescRarity := equipmentFields[27].Descriptor()
	// equipment.DefaultRarity holds the default value on creation for the rarity field.
	equipment.DefaultRarity = equipmentDescRarity.Default.(string)
	// equipmentDescSkillRequirement is the schema descriptor for skill_requirement field.
	equipmentDescSkillRequirement := equipmentFields[28].Descriptor()
	// equipment.DefaultSkillRequirement holds the default value on creation for the skill_requirement field.
	equipment.DefaultSkillRequirement = equipmentDescSkillRequirement.Default.(string)
	// equipmentDescSkillRequirementLevel is the schema descriptor for skill_requirement_level field.
	equipmentDescSkillRequirementLevel := equipmentFields[29].Descriptor()
	// equipment.DefaultSkillRequirementLevel holds the default value on creation for the skill_requirement_level field.
	equipment.DefaultSkillRequirementLevel = equipmentDescSkillRequirementLevel.Default.(int)
	// equipmentDescDamageDiceCount is the schema descriptor for damage_dice_count field.
	equipmentDescDamageDiceCount := equipmentFields[30].Descriptor()
	// equipment.DefaultDamageDiceCount holds the default value on creation for the damage_dice_count field.
	equipment.DefaultDamageDiceCount = equipmentDescDamageDiceCount.Default.(int)
	// equipmentDescDamageDiceSides is the schema descriptor for damage_dice_sides field.
	equipmentDescDamageDiceSides := equipmentFields[31].Descriptor()
	// equipment.DefaultDamageDiceSides holds the default value on creation for the damage_dice_sides field.
	equipment.DefaultDamageDiceSides = equipmentDescDamageDiceSides.Default.(int)
	// equipmentDescDamageBonus is the schema descriptor for damage_bonus field.
	equipmentDescDamageBonus := equipmentFields[32].Descriptor()
	// equipment.DefaultDamageBonus holds the default value on creation for the damage_bonus field.
	equipment.DefaultDamageBonus = equipmentDescDamageBonus.Default.(int)
	// equipmentDescDamageType is the schema descriptor for damage_type field.
	equipmentDescDamageType := equipmentFields[33].Descriptor()
	// equipment.DefaultDamageType holds the default value on creation for the damage_type field.
	equipment.DefaultDamageType = equipmentDescDamageType.Default.(string)
	// equipmentDescWeaponType is the schema descriptor for weapon_type field.
	equipmentDescWeaponType := equipmentFields[34].Descriptor()
	// equipment.DefaultWeaponType holds the default value on creation for the weapon_type field.
	equipment.DefaultWeaponType = equipmentDescWeaponType.Default.(string)
	// equipmentDescIsTwoHanded is the schema descriptor for is_two_handed field.
	equipmentDescIsTwoHanded := equipmentFields[35].Descriptor()
	// equipment.DefaultIsTwoHanded holds the default value on creation for the is_two_handed field.
	equipment.DefaultIsTwoHanded = equipmentDescIsTwoHanded.Default.(bool)
	equipmenttemplateFields := schema.EquipmentTemplate{}.Fields()
	_ = equipmenttemplateFields
	// equipmenttemplateDescLevel is the schema descriptor for level field.
	equipmenttemplateDescLevel := equipmenttemplateFields[4].Descriptor()
	// equipmenttemplate.DefaultLevel holds the default value on creation for the level field.
	equipmenttemplate.DefaultLevel = equipmenttemplateDescLevel.Default.(int)
	// equipmenttemplateDescWeight is the schema descriptor for weight field.
	equipmenttemplateDescWeight := equipmenttemplateFields[5].Descriptor()
	// equipmenttemplate.DefaultWeight holds the default value on creation for the weight field.
	equipmenttemplate.DefaultWeight = equipmenttemplateDescWeight.Default.(int)
	// equipmenttemplateDescItemType is the schema descriptor for item_type field.
	equipmenttemplateDescItemType := equipmenttemplateFields[6].Descriptor()
	// equipmenttemplate.DefaultItemType holds the default value on creation for the item_type field.
	equipmenttemplate.DefaultItemType = equipmenttemplateDescItemType.Default.(string)
	// equipmenttemplateDescColor is the schema descriptor for color field.
	equipmenttemplateDescColor := equipmenttemplateFields[8].Descriptor()
	// equipmenttemplate.DefaultColor holds the default value on creation for the color field.
	equipmenttemplate.DefaultColor = equipmenttemplateDescColor.Default.(string)
	// equipmenttemplateDescIsVisible is the schema descriptor for is_visible field.
	equipmenttemplateDescIsVisible := equipmenttemplateFields[9].Descriptor()
	// equipmenttemplate.DefaultIsVisible holds the default value on creation for the is_visible field.
	equipmenttemplate.DefaultIsVisible = equipmenttemplateDescIsVisible.Default.(bool)
	// equipmenttemplateDescIsImmovable is the schema descriptor for is_immovable field.
	equipmenttemplateDescIsImmovable := equipmenttemplateFields[10].Descriptor()
	// equipmenttemplate.DefaultIsImmovable holds the default value on creation for the is_immovable field.
	equipmenttemplate.DefaultIsImmovable = equipmenttemplateDescIsImmovable.Default.(bool)
	// equipmenttemplateDescEffectType is the schema descriptor for effect_type field.
	equipmenttemplateDescEffectType := equipmenttemplateFields[11].Descriptor()
	// equipmenttemplate.DefaultEffectType holds the default value on creation for the effect_type field.
	equipmenttemplate.DefaultEffectType = equipmenttemplateDescEffectType.Default.(string)
	// equipmenttemplateDescEffectValue is the schema descriptor for effect_value field.
	equipmenttemplateDescEffectValue := equipmenttemplateFields[12].Descriptor()
	// equipmenttemplate.DefaultEffectValue holds the default value on creation for the effect_value field.
	equipmenttemplate.DefaultEffectValue = equipmenttemplateDescEffectValue.Default.(int)
	// equipmenttemplateDescEffectDuration is the schema descriptor for effect_duration field.
	equipmenttemplateDescEffectDuration := equipmenttemplateFields[13].Descriptor()
	// equipmenttemplate.DefaultEffectDuration holds the default value on creation for the effect_duration field.
	equipmenttemplate.DefaultEffectDuration = equipmenttemplateDescEffectDuration.Default.(int)
	// equipmenttemplateDescIsContainer is the schema descriptor for is_container field.
	equipmenttemplateDescIsContainer := equipmenttemplateFields[14].Descriptor()
	// equipmenttemplate.DefaultIsContainer holds the default value on creation for the is_container field.
	equipmenttemplate.DefaultIsContainer = equipmenttemplateDescIsContainer.Default.(bool)
	// equipmenttemplateDescContainerCapacity is the schema descriptor for container_capacity field.
	equipmenttemplateDescContainerCapacity := equipmenttemplateFields[15].Descriptor()
	// equipmenttemplate.DefaultContainerCapacity holds the default value on creation for the container_capacity field.
	equipmenttemplate.DefaultContainerCapacity = equipmenttemplateDescContainerCapacity.Default.(int)
	// equipmenttemplateDescIsLocked is the schema descriptor for is_locked field.
	equipmenttemplateDescIsLocked := equipmenttemplateFields[16].Descriptor()
	// equipmenttemplate.DefaultIsLocked holds the default value on creation for the is_locked field.
	equipmenttemplate.DefaultIsLocked = equipmenttemplateDescIsLocked.Default.(bool)
	// equipmenttemplateDescRevealCondition is the schema descriptor for reveal_condition field.
	equipmenttemplateDescRevealCondition := equipmenttemplateFields[18].Descriptor()
	// equipmenttemplate.DefaultRevealCondition holds the default value on creation for the reveal_condition field.
	equipmenttemplate.DefaultRevealCondition = equipmenttemplateDescRevealCondition.Default.(string)
	// equipmenttemplateDescArmorRating is the schema descriptor for armor_rating field.
	equipmenttemplateDescArmorRating := equipmenttemplateFields[20].Descriptor()
	// equipmenttemplate.DefaultArmorRating holds the default value on creation for the armor_rating field.
	equipmenttemplate.DefaultArmorRating = equipmenttemplateDescArmorRating.Default.(int)
	// equipmenttemplateDescArmorType is the schema descriptor for armor_type field.
	equipmenttemplateDescArmorType := equipmenttemplateFields[21].Descriptor()
	// equipmenttemplate.DefaultArmorType holds the default value on creation for the armor_type field.
	equipmenttemplate.DefaultArmorType = equipmenttemplateDescArmorType.Default.(string)
	// equipmenttemplateDescRarity is the schema descriptor for rarity field.
	equipmenttemplateDescRarity := equipmenttemplateFields[22].Descriptor()
	// equipmenttemplate.DefaultRarity holds the default value on creation for the rarity field.
	equipmenttemplate.DefaultRarity = equipmenttemplateDescRarity.Default.(string)
	// equipmenttemplateDescSkillRequirement is the schema descriptor for skill_requirement field.
	equipmenttemplateDescSkillRequirement := equipmenttemplateFields[23].Descriptor()
	// equipmenttemplate.DefaultSkillRequirement holds the default value on creation for the skill_requirement field.
	equipmenttemplate.DefaultSkillRequirement = equipmenttemplateDescSkillRequirement.Default.(string)
	// equipmenttemplateDescSkillRequirementLevel is the schema descriptor for skill_requirement_level field.
	equipmenttemplateDescSkillRequirementLevel := equipmenttemplateFields[24].Descriptor()
	// equipmenttemplate.DefaultSkillRequirementLevel holds the default value on creation for the skill_requirement_level field.
	equipmenttemplate.DefaultSkillRequirementLevel = equipmenttemplateDescSkillRequirementLevel.Default.(int)
	// equipmenttemplateDescDamageDiceCount is the schema descriptor for damage_dice_count field.
	equipmenttemplateDescDamageDiceCount := equipmenttemplateFields[25].Descriptor()
	// equipmenttemplate.DefaultDamageDiceCount holds the default value on creation for the damage_dice_count field.
	equipmenttemplate.DefaultDamageDiceCount = equipmenttemplateDescDamageDiceCount.Default.(int)
	// equipmenttemplateDescDamageDiceSides is the schema descriptor for damage_dice_sides field.
	equipmenttemplateDescDamageDiceSides := equipmenttemplateFields[26].Descriptor()
	// equipmenttemplate.DefaultDamageDiceSides holds the default value on creation for the damage_dice_sides field.
	equipmenttemplate.DefaultDamageDiceSides = equipmenttemplateDescDamageDiceSides.Default.(int)
	// equipmenttemplateDescDamageBonus is the schema descriptor for damage_bonus field.
	equipmenttemplateDescDamageBonus := equipmenttemplateFields[27].Descriptor()
	// equipmenttemplate.DefaultDamageBonus holds the default value on creation for the damage_bonus field.
	equipmenttemplate.DefaultDamageBonus = equipmenttemplateDescDamageBonus.Default.(int)
	// equipmenttemplateDescDamageType is the schema descriptor for damage_type field.
	equipmenttemplateDescDamageType := equipmenttemplateFields[28].Descriptor()
	// equipmenttemplate.DefaultDamageType holds the default value on creation for the damage_type field.
	equipmenttemplate.DefaultDamageType = equipmenttemplateDescDamageType.Default.(string)
	// equipmenttemplateDescWeaponType is the schema descriptor for weapon_type field.
	equipmenttemplateDescWeaponType := equipmenttemplateFields[29].Descriptor()
	// equipmenttemplate.DefaultWeaponType holds the default value on creation for the weapon_type field.
	equipmenttemplate.DefaultWeaponType = equipmenttemplateDescWeaponType.Default.(string)
	// equipmenttemplateDescIsTwoHanded is the schema descriptor for is_two_handed field.
	equipmenttemplateDescIsTwoHanded := equipmenttemplateFields[30].Descriptor()
	// equipmenttemplate.DefaultIsTwoHanded holds the default value on creation for the is_two_handed field.
	equipmenttemplate.DefaultIsTwoHanded = equipmenttemplateDescIsTwoHanded.Default.(bool)
	factioncategoryFields := schema.FactionCategory{}.Fields()
	_ = factioncategoryFields
	// factioncategoryDescMaxMemberships is the schema descriptor for max_memberships field.
	factioncategoryDescMaxMemberships := factioncategoryFields[3].Descriptor()
	// factioncategory.DefaultMaxMemberships holds the default value on creation for the max_memberships field.
	factioncategory.DefaultMaxMemberships = factioncategoryDescMaxMemberships.Default.(int)
	// factioncategoryDescAutoJoin is the schema descriptor for auto_join field.
	factioncategoryDescAutoJoin := factioncategoryFields[4].Descriptor()
	// factioncategory.DefaultAutoJoin holds the default value on creation for the auto_join field.
	factioncategory.DefaultAutoJoin = factioncategoryDescAutoJoin.Default.(bool)
	npctemplateFields := schema.NPCTemplate{}.Fields()
	_ = npctemplateFields
	// npctemplateDescLevel is the schema descriptor for level field.
	npctemplateDescLevel := npctemplateFields[5].Descriptor()
	// npctemplate.DefaultLevel holds the default value on creation for the level field.
	npctemplate.DefaultLevel = npctemplateDescLevel.Default.(int)
	// npctemplateDescXpValue is the schema descriptor for xp_value field.
	npctemplateDescXpValue := npctemplateFields[6].Descriptor()
	// npctemplate.DefaultXpValue holds the default value on creation for the xp_value field.
	npctemplate.DefaultXpValue = npctemplateDescXpValue.Default.(int)
	// npctemplateDescRespawnCooldown is the schema descriptor for respawn_cooldown field.
	npctemplateDescRespawnCooldown := npctemplateFields[11].Descriptor()
	// npctemplate.DefaultRespawnCooldown holds the default value on creation for the respawn_cooldown field.
	npctemplate.DefaultRespawnCooldown = npctemplateDescRespawnCooldown.Default.(int)
	raceFields := schema.Race{}.Fields()
	_ = raceFields
	// raceDescEquipmentSlots is the schema descriptor for equipment_slots field.
	raceDescEquipmentSlots := raceFields[5].Descriptor()
	// race.DefaultEquipmentSlots holds the default value on creation for the equipment_slots field.
	race.DefaultEquipmentSlots = raceDescEquipmentSlots.Default.([]string)
	// raceDescIsPlayable is the schema descriptor for is_playable field.
	raceDescIsPlayable := raceFields[6].Descriptor()
	// race.DefaultIsPlayable holds the default value on creation for the is_playable field.
	race.DefaultIsPlayable = raceDescIsPlayable.Default.(bool)
	roomFields := schema.Room{}.Fields()
	_ = roomFields
	// roomDescIsStartingRoom is the schema descriptor for isStartingRoom field.
	roomDescIsStartingRoom := roomFields[2].Descriptor()
	// room.DefaultIsStartingRoom holds the default value on creation for the isStartingRoom field.
	room.DefaultIsStartingRoom = roomDescIsStartingRoom.Default.(bool)
	// roomDescIsRootRoom is the schema descriptor for isRootRoom field.
	roomDescIsRootRoom := roomFields[3].Descriptor()
	// room.DefaultIsRootRoom holds the default value on creation for the isRootRoom field.
	room.DefaultIsRootRoom = roomDescIsRootRoom.Default.(bool)
	// roomDescPosX is the schema descriptor for posX field.
	roomDescPosX := roomFields[6].Descriptor()
	// room.DefaultPosX holds the default value on creation for the posX field.
	room.DefaultPosX = roomDescPosX.Default.(int)
	// roomDescPosY is the schema descriptor for posY field.
	roomDescPosY := roomFields[7].Descriptor()
	// room.DefaultPosY holds the default value on creation for the posY field.
	room.DefaultPosY = roomDescPosY.Default.(int)
	// roomDescPosZ is the schema descriptor for posZ field.
	roomDescPosZ := roomFields[8].Descriptor()
	// room.DefaultPosZ holds the default value on creation for the posZ field.
	room.DefaultPosZ = roomDescPosZ.Default.(int)
	// roomDescVersion is the schema descriptor for version field.
	roomDescVersion := roomFields[9].Descriptor()
	// room.DefaultVersion holds the default value on creation for the version field.
	room.DefaultVersion = roomDescVersion.Default.(int)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[2].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
	// userDescGodMode is the schema descriptor for god_mode field.
	userDescGodMode := userFields[3].Descriptor()
	// user.DefaultGodMode holds the default value on creation for the god_mode field.
	user.DefaultGodMode = userDescGodMode.Default.(bool)
}
