// Code generated by ent, DO NOT EDIT.

package db

import (
	"encoding/json"
	"fmt"
	"herbst-server/db/skill"
	"herbst-server/db/world"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Skill is the model entity for the Skill schema.
type Skill struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// World this skill belongs to
	WorldID int `json:"world_id,omitempty"`
	// Machine name e.g., 'blades', 'heavy_armor'
	Name string `json:"name,omitempty"`
	// Human-readable name e.g., 'Blades', 'Heavy Armor'
	DisplayName string `json:"display_name,omitempty"`
	// Description of the skill
	Description string `json:"description,omitempty"`
	// Category: weapon, armor, craft, magic, etc.
	Category string `json:"category,omitempty"`
	// Parent skill for tree structure (nullable)
	ParentSkillID *int `json:"parent_skill_id,omitempty"`
	// Maximum level cap for this skill
	MaxLevel int `json:"max_level,omitempty"`
	// XP curve mode: 'percentage' or 'hand_coded'
	XpCurveMode string `json:"xp_curve_mode,omitempty"`
	// XP curve config: {percentage: 50} or {thresholds: [0, 1000, 2500, ...]}
	XpCurveData map[string]interface{} `json:"xp_curve_data,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SkillQuery when eager-loading is set.
	Edges        SkillEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SkillEdges holds the relations/edges for other nodes in the graph.
type SkillEdges struct {
	// World holds the value of the world edge.
	World *World `json:"world,omitempty"`
	// CharacterSkills holds the value of the character_skills edge.
	CharacterSkills []*CharacterSkill `json:"character_skills,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *Skill `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*Skill `json:"children,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// WorldOrErr returns the World value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SkillEdges) WorldOrErr() (*World, error) {
	if e.World != nil {
		return e.World, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: world.Label}
	}
	return nil, &NotLoadedError{edge: "world"}
}

// CharacterSkillsOrErr returns the CharacterSkills value or an error if the edge
// was not loaded in eager-loading.
func (e SkillEdges) CharacterSkillsOrErr() ([]*CharacterSkill, error) {
	if e.loadedTypes[1] {
		return e.CharacterSkills, nil
	}
	return nil, &NotLoadedError{edge: "character_skills"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SkillEdges) ParentOrErr() (*Skill, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: skill.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e SkillEdges) ChildrenOrErr() ([]*Skill, error) {
	if e.loadedTypes[3] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Skill) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case skill.FieldXpCurveData:
			values[i] = new([]byte)
		case skill.FieldID, skill.FieldWorldID, skill.FieldParentSkillID, skill.FieldMaxLevel:
			values[i] = new(sql.NullInt64)
		case skill.FieldName, skill.FieldDisplayName, skill.FieldDescription, skill.FieldCategory, skill.FieldXpCurveMode:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Skill fields.
func (_m *Skill) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case skill.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case skill.FieldWorldID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field world_id", values[i])
			} else if value.Valid {
				_m.WorldID = int(value.Int64)
			}
		case skill.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case skill.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case skill.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case skill.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case skill.FieldParentSkillID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_skill_id", values[i])
			} else if value.Valid {
				_m.ParentSkillID = new(int)
				*_m.ParentSkillID = int(value.Int64)
			}
		case skill.FieldMaxLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_level", values[i])
			} else if value.Valid {
				_m.MaxLevel = int(value.Int64)
			}
		case skill.FieldXpCurveMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field xp_curve_mode", values[i])
			} else if value.Valid {
				_m.XpCurveMode = value.String
			}
		case skill.FieldXpCurveData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field xp_curve_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.XpCurveData); err != nil {
					return fmt.Errorf("unmarshal field xp_curve_data: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Skill.
// This includes values selected through modifiers, order, etc.
func (_m *Skill) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorld queries the "world" edge of the Skill entity.
func (_m *Skill) QueryWorld() *WorldQuery {
	return NewSkillClient(_m.config).QueryWorld(_m)
}

// QueryCharacterSkills queries the "character_skills" edge of the Skill entity.
func (_m *Skill) QueryCharacterSkills() *CharacterSkillQuery {
	return NewSkillClient(_m.config).QueryCharacterSkills(_m)
}

// QueryParent queries the "parent" edge of the Skill entity.
func (_m *Skill) QueryParent() *SkillQuery {
	return NewSkillClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the Skill entity.
func (_m *Skill) QueryChildren() *SkillQuery {
	return NewSkillClient(_m.config).QueryChildren(_m)
}

// Update returns a builder for updating this Skill.
// Note that you need to call Skill.Unwrap() before calling this method if this Skill
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Skill) Update() *SkillUpdateOne {
	return NewSkillClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Skill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Skill) Unwrap() *Skill {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: Skill is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Skill) String() string {
	var builder strings.Builder
	builder.WriteString("Skill(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("world_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorldID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	if v := _m.ParentSkillID; v != nil {
		builder.WriteString("parent_skill_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("max_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxLevel))
	builder.WriteString(", ")
	builder.WriteString("xp_curve_mode=")
	builder.WriteString(_m.XpCurveMode)
	builder.WriteString(", ")
	builder.WriteString("xp_curve_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.XpCurveData))
	builder.WriteByte(')')
	return builder.String()
}

// Skills is a parsable slice of Skill.
type Skills []*Skill
