// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"herbst-server/db/predicate"
	"herbst-server/db/systemlog"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SystemLogUpdate is the builder for updating SystemLog entities.
type SystemLogUpdate struct {
	config
	hooks    []Hook
	mutation *SystemLogMutation
}

// Where appends a list predicates to the SystemLogUpdate builder.
func (_u *SystemLogUpdate) Where(ps ...predicate.SystemLog) *SystemLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAction sets the "action" field.
func (_u *SystemLogUpdate) SetAction(v string) *SystemLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SystemLogUpdate) SetNillableAction(v *string) *SystemLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *SystemLogUpdate) SetCharacterID(v int) *SystemLogUpdate {
	_u.mutation.ResetCharacterID()
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *SystemLogUpdate) SetNillableCharacterID(v *int) *SystemLogUpdate {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// AddCharacterID adds value to the "character_id" field.
func (_u *SystemLogUpdate) AddCharacterID(v int) *SystemLogUpdate {
	_u.mutation.AddCharacterID(v)
	return _u
}

// ClearCharacterID clears the value of the "character_id" field.
func (_u *SystemLogUpdate) ClearCharacterID() *SystemLogUpdate {
	_u.mutation.ClearCharacterID()
	return _u
}

// SetDetails sets the "details" field.
func (_u *SystemLogUpdate) SetDetails(v string) *SystemLogUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *SystemLogUpdate) SetNillableDetails(v *string) *SystemLogUpdate {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *SystemLogUpdate) ClearDetails() *SystemLogUpdate {
	_u.mutation.ClearDetails()
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *SystemLogUpdate) SetTimestamp(v time.Time) *SystemLogUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *SystemLogUpdate) SetNillableTimestamp(v *time.Time) *SystemLogUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// Mutation returns the SystemLogMutation object of the builder.
func (_u *SystemLogUpdate) Mutation() *SystemLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SystemLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(systemlog.Table, systemlog.Columns, sqlgraph.NewFieldSpec(systemlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(systemlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.CharacterID(); ok {
		_spec.SetField(systemlog.FieldCharacterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCharacterID(); ok {
		_spec.AddField(systemlog.FieldCharacterID, field.TypeInt, value)
	}
	if _u.mutation.CharacterIDCleared() {
		_spec.ClearField(systemlog.FieldCharacterID, field.TypeInt)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(systemlog.FieldDetails, field.TypeString, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(systemlog.FieldDetails, field.TypeString)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(systemlog.FieldTimestamp, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemLogUpdateOne is the builder for updating a single SystemLog entity.
type SystemLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemLogMutation
}

// SetAction sets the "action" field.
func (_u *SystemLogUpdateOne) SetAction(v string) *SystemLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SystemLogUpdateOne) SetNillableAction(v *string) *SystemLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *SystemLogUpdateOne) SetCharacterID(v int) *SystemLogUpdateOne {
	_u.mutation.ResetCharacterID()
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *SystemLogUpdateOne) SetNillableCharacterID(v *int) *SystemLogUpdateOne {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// AddCharacterID adds value to the "character_id" field.
func (_u *SystemLogUpdateOne) AddCharacterID(v int) *SystemLogUpdateOne {
	_u.mutation.AddCharacterID(v)
	return _u
}

// ClearCharacterID clears the value of the "character_id" field.
func (_u *SystemLogUpdateOne) ClearCharacterID() *SystemLogUpdateOne {
	_u.mutation.ClearCharacterID()
	return _u
}

// SetDetails sets the "details" field.
func (_u *SystemLogUpdateOne) SetDetails(v string) *SystemLogUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *SystemLogUpdateOne) SetNillableDetails(v *string) *SystemLogUpdateOne {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *SystemLogUpdateOne) ClearDetails() *SystemLogUpdateOne {
	_u.mutation.ClearDetails()
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *SystemLogUpdateOne) SetTimestamp(v time.Time) *SystemLogUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *SystemLogUpdateOne) SetNillableTimestamp(v *time.Time) *SystemLogUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// Mutation returns the SystemLogMutation object of the builder.
func (_u *SystemLogUpdateOne) Mutation() *SystemLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the SystemLogUpdate builder.
func (_u *SystemLogUpdateOne) Where(ps ...predicate.SystemLog) *SystemLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemLogUpdateOne) Select(field string, fields ...string) *SystemLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemLog entity.
func (_u *SystemLogUpdateOne) Save(ctx context.Context) (*SystemLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemLogUpdateOne) SaveX(ctx context.Context) *SystemLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SystemLogUpdateOne) sqlSave(ctx context.Context) (_node *SystemLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(systemlog.Table, systemlog.Columns, sqlgraph.NewFieldSpec(systemlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "SystemLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemlog.FieldID)
		for _, f := range fields {
			if !systemlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != systemlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(systemlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.CharacterID(); ok {
		_spec.SetField(systemlog.FieldCharacterID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCharacterID(); ok {
		_spec.AddField(systemlog.FieldCharacterID, field.TypeInt, value)
	}
	if _u.mutation.CharacterIDCleared() {
		_spec.ClearField(systemlog.FieldCharacterID, field.TypeInt)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(systemlog.FieldDetails, field.TypeString, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(systemlog.FieldDetails, field.TypeString)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(systemlog.FieldTimestamp, field.TypeTime, value)
	}
	_node = &SystemLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
