// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"herbst-server/db/availabletalent"
	"herbst-server/db/charactertalent"
	"herbst-server/db/talent"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TalentCreate is the builder for creating a Talent entity.
type TalentCreate struct {
	config
	mutation *TalentMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TalentCreate) SetName(v string) *TalentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TalentCreate) SetDescription(v string) *TalentCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetRequirements sets the "requirements" field.
func (_c *TalentCreate) SetRequirements(v string) *TalentCreate {
	_c.mutation.SetRequirements(v)
	return _c
}

// SetNillableRequirements sets the "requirements" field if the given value is not nil.
func (_c *TalentCreate) SetNillableRequirements(v *string) *TalentCreate {
	if v != nil {
		_c.SetRequirements(*v)
	}
	return _c
}

// SetEffectType sets the "effect_type" field.
func (_c *TalentCreate) SetEffectType(v string) *TalentCreate {
	_c.mutation.SetEffectType(v)
	return _c
}

// SetNillableEffectType sets the "effect_type" field if the given value is not nil.
func (_c *TalentCreate) SetNillableEffectType(v *string) *TalentCreate {
	if v != nil {
		_c.SetEffectType(*v)
	}
	return _c
}

// SetEffectValue sets the "effect_value" field.
func (_c *TalentCreate) SetEffectValue(v int) *TalentCreate {
	_c.mutation.SetEffectValue(v)
	return _c
}

// SetNillableEffectValue sets the "effect_value" field if the given value is not nil.
func (_c *TalentCreate) SetNillableEffectValue(v *int) *TalentCreate {
	if v != nil {
		_c.SetEffectValue(*v)
	}
	return _c
}

// SetEffectDuration sets the "effect_duration" field.
func (_c *TalentCreate) SetEffectDuration(v int) *TalentCreate {
	_c.mutation.SetEffectDuration(v)
	return _c
}

// SetNillableEffectDuration sets the "effect_duration" field if the given value is not nil.
func (_c *TalentCreate) SetNillableEffectDuration(v *int) *TalentCreate {
	if v != nil {
		_c.SetEffectDuration(*v)
	}
	return _c
}

// SetCooldown sets the "cooldown" field.
func (_c *TalentCreate) SetCooldown(v int) *TalentCreate {
	_c.mutation.SetCooldown(v)
	return _c
}

// SetNillableCooldown sets the "cooldown" field if the given value is not nil.
func (_c *TalentCreate) SetNillableCooldown(v *int) *TalentCreate {
	if v != nil {
		_c.SetCooldown(*v)
	}
	return _c
}

// SetManaCost sets the "mana_cost" field.
func (_c *TalentCreate) SetManaCost(v int) *TalentCreate {
	_c.mutation.SetManaCost(v)
	return _c
}

// SetNillableManaCost sets the "mana_cost" field if the given value is not nil.
func (_c *TalentCreate) SetNillableManaCost(v *int) *TalentCreate {
	if v != nil {
		_c.SetManaCost(*v)
	}
	return _c
}

// SetStaminaCost sets the "stamina_cost" field.
func (_c *TalentCreate) SetStaminaCost(v int) *TalentCreate {
	_c.mutation.SetStaminaCost(v)
	return _c
}

// SetNillableStaminaCost sets the "stamina_cost" field if the given value is not nil.
func (_c *TalentCreate) SetNillableStaminaCost(v *int) *TalentCreate {
	if v != nil {
		_c.SetStaminaCost(*v)
	}
	return _c
}

// AddCharacterIDs adds the "characters" edge to the CharacterTalent entity by IDs.
func (_c *TalentCreate) AddCharacterIDs(ids ...int) *TalentCreate {
	_c.mutation.AddCharacterIDs(ids...)
	return _c
}

// AddCharacters adds the "characters" edges to the CharacterTalent entity.
func (_c *TalentCreate) AddCharacters(v ...*CharacterTalent) *TalentCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCharacterIDs(ids...)
}

// AddAvailableToCharacterIDs adds the "available_to_characters" edge to the AvailableTalent entity by IDs.
func (_c *TalentCreate) AddAvailableToCharacterIDs(ids ...int) *TalentCreate {
	_c.mutation.AddAvailableToCharacterIDs(ids...)
	return _c
}

// AddAvailableToCharacters adds the "available_to_characters" edges to the AvailableTalent entity.
func (_c *TalentCreate) AddAvailableToCharacters(v ...*AvailableTalent) *TalentCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAvailableToCharacterIDs(ids...)
}

// Mutation returns the TalentMutation object of the builder.
func (_c *TalentCreate) Mutation() *TalentMutation {
	return _c.mutation
}

// Save creates the Talent in the database.
func (_c *TalentCreate) Save(ctx context.Context) (*Talent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TalentCreate) SaveX(ctx context.Context) *Talent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TalentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TalentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TalentCreate) defaults() {
	if _, ok := _c.mutation.EffectType(); !ok {
		v := talent.DefaultEffectType
		_c.mutation.SetEffectType(v)
	}
	if _, ok := _c.mutation.EffectValue(); !ok {
		v := talent.DefaultEffectValue
		_c.mutation.SetEffectValue(v)
	}
	if _, ok := _c.mutation.EffectDuration(); !ok {
		v := talent.DefaultEffectDuration
		_c.mutation.SetEffectDuration(v)
	}
	if _, ok := _c.mutation.Cooldown(); !ok {
		v := talent.DefaultCooldown
		_c.mutation.SetCooldown(v)
	}
	if _, ok := _c.mutation.ManaCost(); !ok {
		v := talent.DefaultManaCost
		_c.mutation.SetManaCost(v)
	}
	if _, ok := _c.mutation.StaminaCost(); !ok {
		v := talent.DefaultStaminaCost
		_c.mutation.SetStaminaCost(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TalentCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`db: missing required field "Talent.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`db: missing required field "Talent.description"`)}
	}
	if _, ok := _c.mutation.EffectType(); !ok {
		return &ValidationError{Name: "effect_type", err: errors.New(`db: missing required field "Talent.effect_type"`)}
	}
	if _, ok := _c.mutation.EffectValue(); !ok {
		return &ValidationError{Name: "effect_value", err: errors.New(`db: missing required field "Talent.effect_value"`)}
	}
	if _, ok := _c.mutation.EffectDuration(); !ok {
		return &ValidationError{Name: "effect_duration", err: errors.New(`db: missing required field "Talent.effect_duration"`)}
	}
	if _, ok := _c.mutation.Cooldown(); !ok {
		return &ValidationError{Name: "cooldown", err: errors.New(`db: missing required field "Talent.cooldown"`)}
	}
	if _, ok := _c.mutation.ManaCost(); !ok {
		return &ValidationError{Name: "mana_cost", err: errors.New(`db: missing required field "Talent.mana_cost"`)}
	}
	if _, ok := _c.mutation.StaminaCost(); !ok {
		return &ValidationError{Name: "stamina_cost", err: errors.New(`db: missing required field "Talent.stamina_cost"`)}
	}
	return nil
}

func (_c *TalentCreate) sqlSave(ctx context.Context) (*Talent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TalentCreate) createSpec() (*Talent, *sqlgraph.CreateSpec) {
	var (
		_node = &Talent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(talent.Table, sqlgraph.NewFieldSpec(talent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(talent.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(talent.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Requirements(); ok {
		_spec.SetField(talent.FieldRequirements, field.TypeString, value)
		_node.Requirements = value
	}
	if value, ok := _c.mutation.EffectType(); ok {
		_spec.SetField(talent.FieldEffectType, field.TypeString, value)
		_node.EffectType = value
	}
	if value, ok := _c.mutation.EffectValue(); ok {
		_spec.SetField(talent.FieldEffectValue, field.TypeInt, value)
		_node.EffectValue = value
	}
	if value, ok := _c.mutation.EffectDuration(); ok {
		_spec.SetField(talent.FieldEffectDuration, field.TypeInt, value)
		_node.EffectDuration = value
	}
	if value, ok := _c.mutation.Cooldown(); ok {
		_spec.SetField(talent.FieldCooldown, field.TypeInt, value)
		_node.Cooldown = value
	}
	if value, ok := _c.mutation.ManaCost(); ok {
		_spec.SetField(talent.FieldManaCost, field.TypeInt, value)
		_node.ManaCost = value
	}
	if value, ok := _c.mutation.StaminaCost(); ok {
		_spec.SetField(talent.FieldStaminaCost, field.TypeInt, value)
		_node.StaminaCost = value
	}
	if nodes := _c.mutation.CharactersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   talent.CharactersTable,
			Columns: []string{talent.CharactersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(charactertalent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AvailableToCharactersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   talent.AvailableToCharactersTable,
			Columns: []string{talent.AvailableToCharactersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(availabletalent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TalentCreateBulk is the builder for creating many Talent entities in bulk.
type TalentCreateBulk struct {
	config
	err      error
	builders []*TalentCreate
}

// Save creates the Talent entities in the database.
func (_c *TalentCreateBulk) Save(ctx context.Context) ([]*Talent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Talent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TalentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TalentCreateBulk) SaveX(ctx context.Context) []*Talent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TalentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TalentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
