// Code generated by ent, DO NOT EDIT.

package ability

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ability type in the database.
	Label = "ability"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAbilityType holds the string denoting the ability_type field in the database.
	FieldAbilityType = "ability_type"
	// FieldCost holds the string denoting the cost field in the database.
	FieldCost = "cost"
	// FieldCooldown holds the string denoting the cooldown field in the database.
	FieldCooldown = "cooldown"
	// FieldRequirements holds the string denoting the requirements field in the database.
	FieldRequirements = "requirements"
	// FieldManaCost holds the string denoting the mana_cost field in the database.
	FieldManaCost = "mana_cost"
	// FieldStaminaCost holds the string denoting the stamina_cost field in the database.
	FieldStaminaCost = "stamina_cost"
	// FieldHpCost holds the string denoting the hp_cost field in the database.
	FieldHpCost = "hp_cost"
	// EdgeCharacters holds the string denoting the characters edge name in mutations.
	EdgeCharacters = "characters"
	// EdgeEffects holds the string denoting the effects edge name in mutations.
	EdgeEffects = "effects"
	// Table holds the table name of the ability in the database.
	Table = "abilities"
	// CharactersTable is the table that holds the characters relation/edge.
	CharactersTable = "characters"
	// CharactersInverseTable is the table name for the Character entity.
	// It exists in this package in order to avoid circular dependency with the "character" package.
	CharactersInverseTable = "characters"
	// CharactersColumn is the table column denoting the characters relation/edge.
	CharactersColumn = "ability_characters"
	// EffectsTable is the table that holds the effects relation/edge.
	EffectsTable = "ability_effects"
	// EffectsInverseTable is the table name for the AbilityEffect entity.
	// It exists in this package in order to avoid circular dependency with the "abilityeffect" package.
	EffectsInverseTable = "ability_effects"
	// EffectsColumn is the table column denoting the effects relation/edge.
	EffectsColumn = "ability_effects"
)

// Columns holds all SQL columns for ability fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldAbilityType,
	FieldCost,
	FieldCooldown,
	FieldRequirements,
	FieldManaCost,
	FieldStaminaCost,
	FieldHpCost,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Ability queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAbilityType orders the results by the ability_type field.
func ByAbilityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAbilityType, opts...).ToFunc()
}

// ByCost orders the results by the cost field.
func ByCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCost, opts...).ToFunc()
}

// ByCooldown orders the results by the cooldown field.
func ByCooldown(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldown, opts...).ToFunc()
}

// ByRequirements orders the results by the requirements field.
func ByRequirements(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequirements, opts...).ToFunc()
}

// ByManaCost orders the results by the mana_cost field.
func ByManaCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManaCost, opts...).ToFunc()
}

// ByStaminaCost orders the results by the stamina_cost field.
func ByStaminaCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStaminaCost, opts...).ToFunc()
}

// ByHpCost orders the results by the hp_cost field.
func ByHpCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHpCost, opts...).ToFunc()
}

// ByCharactersCount orders the results by characters count.
func ByCharactersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCharactersStep(), opts...)
	}
}

// ByCharacters orders the results by characters terms.
func ByCharacters(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCharactersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEffectsCount orders the results by effects count.
func ByEffectsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEffectsStep(), opts...)
	}
}

// ByEffects orders the results by effects terms.
func ByEffects(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEffectsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCharactersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CharactersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CharactersTable, CharactersColumn),
	)
}
func newEffectsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EffectsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EffectsTable, EffectsColumn),
	)
}
