// Code generated by ent, DO NOT EDIT.

package ability

import (
	"herbst/db/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Ability {
	return predicate.Ability(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Ability {
	return predicate.Ability(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Ability {
	return predicate.Ability(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Ability {
	return predicate.Ability(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Ability {
	return predicate.Ability(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Ability {
	return predicate.Ability(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Ability {
	return predicate.Ability(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldDescription, v))
}

// AbilityType applies equality check predicate on the "ability_type" field. It's identical to AbilityTypeEQ.
func AbilityType(v string) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldAbilityType, v))
}

// Cost applies equality check predicate on the "cost" field. It's identical to CostEQ.
func Cost(v int) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldCost, v))
}

// Cooldown applies equality check predicate on the "cooldown" field. It's identical to CooldownEQ.
func Cooldown(v int) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldCooldown, v))
}

// Requirements applies equality check predicate on the "requirements" field. It's identical to RequirementsEQ.
func Requirements(v string) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldRequirements, v))
}

// ManaCost applies equality check predicate on the "mana_cost" field. It's identical to ManaCostEQ.
func ManaCost(v int) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldManaCost, v))
}

// StaminaCost applies equality check predicate on the "stamina_cost" field. It's identical to StaminaCostEQ.
func StaminaCost(v int) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldStaminaCost, v))
}

// HpCost applies equality check predicate on the "hp_cost" field. It's identical to HpCostEQ.
func HpCost(v int) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldHpCost, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Ability {
	return predicate.Ability(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Ability {
	return predicate.Ability(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Ability {
	return predicate.Ability(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Ability {
	return predicate.Ability(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Ability {
	return predicate.Ability(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Ability {
	return predicate.Ability(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Ability {
	return predicate.Ability(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Ability {
	return predicate.Ability(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Ability {
	return predicate.Ability(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Ability {
	return predicate.Ability(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Ability {
	return predicate.Ability(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Ability {
	return predicate.Ability(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Ability {
	return predicate.Ability(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Ability {
	return predicate.Ability(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Ability {
	return predicate.Ability(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Ability {
	return predicate.Ability(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Ability {
	return predicate.Ability(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Ability {
	return predicate.Ability(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Ability {
	return predicate.Ability(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Ability {
	return predicate.Ability(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Ability {
	return predicate.Ability(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Ability {
	return predicate.Ability(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Ability {
	return predicate.Ability(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Ability {
	return predicate.Ability(sql.FieldContainsFold(FieldDescription, v))
}

// AbilityTypeEQ applies the EQ predicate on the "ability_type" field.
func AbilityTypeEQ(v string) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldAbilityType, v))
}

// AbilityTypeNEQ applies the NEQ predicate on the "ability_type" field.
func AbilityTypeNEQ(v string) predicate.Ability {
	return predicate.Ability(sql.FieldNEQ(FieldAbilityType, v))
}

// AbilityTypeIn applies the In predicate on the "ability_type" field.
func AbilityTypeIn(vs ...string) predicate.Ability {
	return predicate.Ability(sql.FieldIn(FieldAbilityType, vs...))
}

// AbilityTypeNotIn applies the NotIn predicate on the "ability_type" field.
func AbilityTypeNotIn(vs ...string) predicate.Ability {
	return predicate.Ability(sql.FieldNotIn(FieldAbilityType, vs...))
}

// AbilityTypeGT applies the GT predicate on the "ability_type" field.
func AbilityTypeGT(v string) predicate.Ability {
	return predicate.Ability(sql.FieldGT(FieldAbilityType, v))
}

// AbilityTypeGTE applies the GTE predicate on the "ability_type" field.
func AbilityTypeGTE(v string) predicate.Ability {
	return predicate.Ability(sql.FieldGTE(FieldAbilityType, v))
}

// AbilityTypeLT applies the LT predicate on the "ability_type" field.
func AbilityTypeLT(v string) predicate.Ability {
	return predicate.Ability(sql.FieldLT(FieldAbilityType, v))
}

// AbilityTypeLTE applies the LTE predicate on the "ability_type" field.
func AbilityTypeLTE(v string) predicate.Ability {
	return predicate.Ability(sql.FieldLTE(FieldAbilityType, v))
}

// AbilityTypeContains applies the Contains predicate on the "ability_type" field.
func AbilityTypeContains(v string) predicate.Ability {
	return predicate.Ability(sql.FieldContains(FieldAbilityType, v))
}

// AbilityTypeHasPrefix applies the HasPrefix predicate on the "ability_type" field.
func AbilityTypeHasPrefix(v string) predicate.Ability {
	return predicate.Ability(sql.FieldHasPrefix(FieldAbilityType, v))
}

// AbilityTypeHasSuffix applies the HasSuffix predicate on the "ability_type" field.
func AbilityTypeHasSuffix(v string) predicate.Ability {
	return predicate.Ability(sql.FieldHasSuffix(FieldAbilityType, v))
}

// AbilityTypeEqualFold applies the EqualFold predicate on the "ability_type" field.
func AbilityTypeEqualFold(v string) predicate.Ability {
	return predicate.Ability(sql.FieldEqualFold(FieldAbilityType, v))
}

// AbilityTypeContainsFold applies the ContainsFold predicate on the "ability_type" field.
func AbilityTypeContainsFold(v string) predicate.Ability {
	return predicate.Ability(sql.FieldContainsFold(FieldAbilityType, v))
}

// CostEQ applies the EQ predicate on the "cost" field.
func CostEQ(v int) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldCost, v))
}

// CostNEQ applies the NEQ predicate on the "cost" field.
func CostNEQ(v int) predicate.Ability {
	return predicate.Ability(sql.FieldNEQ(FieldCost, v))
}

// CostIn applies the In predicate on the "cost" field.
func CostIn(vs ...int) predicate.Ability {
	return predicate.Ability(sql.FieldIn(FieldCost, vs...))
}

// CostNotIn applies the NotIn predicate on the "cost" field.
func CostNotIn(vs ...int) predicate.Ability {
	return predicate.Ability(sql.FieldNotIn(FieldCost, vs...))
}

// CostGT applies the GT predicate on the "cost" field.
func CostGT(v int) predicate.Ability {
	return predicate.Ability(sql.FieldGT(FieldCost, v))
}

// CostGTE applies the GTE predicate on the "cost" field.
func CostGTE(v int) predicate.Ability {
	return predicate.Ability(sql.FieldGTE(FieldCost, v))
}

// CostLT applies the LT predicate on the "cost" field.
func CostLT(v int) predicate.Ability {
	return predicate.Ability(sql.FieldLT(FieldCost, v))
}

// CostLTE applies the LTE predicate on the "cost" field.
func CostLTE(v int) predicate.Ability {
	return predicate.Ability(sql.FieldLTE(FieldCost, v))
}

// CooldownEQ applies the EQ predicate on the "cooldown" field.
func CooldownEQ(v int) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldCooldown, v))
}

// CooldownNEQ applies the NEQ predicate on the "cooldown" field.
func CooldownNEQ(v int) predicate.Ability {
	return predicate.Ability(sql.FieldNEQ(FieldCooldown, v))
}

// CooldownIn applies the In predicate on the "cooldown" field.
func CooldownIn(vs ...int) predicate.Ability {
	return predicate.Ability(sql.FieldIn(FieldCooldown, vs...))
}

// CooldownNotIn applies the NotIn predicate on the "cooldown" field.
func CooldownNotIn(vs ...int) predicate.Ability {
	return predicate.Ability(sql.FieldNotIn(FieldCooldown, vs...))
}

// CooldownGT applies the GT predicate on the "cooldown" field.
func CooldownGT(v int) predicate.Ability {
	return predicate.Ability(sql.FieldGT(FieldCooldown, v))
}

// CooldownGTE applies the GTE predicate on the "cooldown" field.
func CooldownGTE(v int) predicate.Ability {
	return predicate.Ability(sql.FieldGTE(FieldCooldown, v))
}

// CooldownLT applies the LT predicate on the "cooldown" field.
func CooldownLT(v int) predicate.Ability {
	return predicate.Ability(sql.FieldLT(FieldCooldown, v))
}

// CooldownLTE applies the LTE predicate on the "cooldown" field.
func CooldownLTE(v int) predicate.Ability {
	return predicate.Ability(sql.FieldLTE(FieldCooldown, v))
}

// RequirementsEQ applies the EQ predicate on the "requirements" field.
func RequirementsEQ(v string) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldRequirements, v))
}

// RequirementsNEQ applies the NEQ predicate on the "requirements" field.
func RequirementsNEQ(v string) predicate.Ability {
	return predicate.Ability(sql.FieldNEQ(FieldRequirements, v))
}

// RequirementsIn applies the In predicate on the "requirements" field.
func RequirementsIn(vs ...string) predicate.Ability {
	return predicate.Ability(sql.FieldIn(FieldRequirements, vs...))
}

// RequirementsNotIn applies the NotIn predicate on the "requirements" field.
func RequirementsNotIn(vs ...string) predicate.Ability {
	return predicate.Ability(sql.FieldNotIn(FieldRequirements, vs...))
}

// RequirementsGT applies the GT predicate on the "requirements" field.
func RequirementsGT(v string) predicate.Ability {
	return predicate.Ability(sql.FieldGT(FieldRequirements, v))
}

// RequirementsGTE applies the GTE predicate on the "requirements" field.
func RequirementsGTE(v string) predicate.Ability {
	return predicate.Ability(sql.FieldGTE(FieldRequirements, v))
}

// RequirementsLT applies the LT predicate on the "requirements" field.
func RequirementsLT(v string) predicate.Ability {
	return predicate.Ability(sql.FieldLT(FieldRequirements, v))
}

// RequirementsLTE applies the LTE predicate on the "requirements" field.
func RequirementsLTE(v string) predicate.Ability {
	return predicate.Ability(sql.FieldLTE(FieldRequirements, v))
}

// RequirementsContains applies the Contains predicate on the "requirements" field.
func RequirementsContains(v string) predicate.Ability {
	return predicate.Ability(sql.FieldContains(FieldRequirements, v))
}

// RequirementsHasPrefix applies the HasPrefix predicate on the "requirements" field.
func RequirementsHasPrefix(v string) predicate.Ability {
	return predicate.Ability(sql.FieldHasPrefix(FieldRequirements, v))
}

// RequirementsHasSuffix applies the HasSuffix predicate on the "requirements" field.
func RequirementsHasSuffix(v string) predicate.Ability {
	return predicate.Ability(sql.FieldHasSuffix(FieldRequirements, v))
}

// RequirementsIsNil applies the IsNil predicate on the "requirements" field.
func RequirementsIsNil() predicate.Ability {
	return predicate.Ability(sql.FieldIsNull(FieldRequirements))
}

// RequirementsNotNil applies the NotNil predicate on the "requirements" field.
func RequirementsNotNil() predicate.Ability {
	return predicate.Ability(sql.FieldNotNull(FieldRequirements))
}

// RequirementsEqualFold applies the EqualFold predicate on the "requirements" field.
func RequirementsEqualFold(v string) predicate.Ability {
	return predicate.Ability(sql.FieldEqualFold(FieldRequirements, v))
}

// RequirementsContainsFold applies the ContainsFold predicate on the "requirements" field.
func RequirementsContainsFold(v string) predicate.Ability {
	return predicate.Ability(sql.FieldContainsFold(FieldRequirements, v))
}

// ManaCostEQ applies the EQ predicate on the "mana_cost" field.
func ManaCostEQ(v int) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldManaCost, v))
}

// ManaCostNEQ applies the NEQ predicate on the "mana_cost" field.
func ManaCostNEQ(v int) predicate.Ability {
	return predicate.Ability(sql.FieldNEQ(FieldManaCost, v))
}

// ManaCostIn applies the In predicate on the "mana_cost" field.
func ManaCostIn(vs ...int) predicate.Ability {
	return predicate.Ability(sql.FieldIn(FieldManaCost, vs...))
}

// ManaCostNotIn applies the NotIn predicate on the "mana_cost" field.
func ManaCostNotIn(vs ...int) predicate.Ability {
	return predicate.Ability(sql.FieldNotIn(FieldManaCost, vs...))
}

// ManaCostGT applies the GT predicate on the "mana_cost" field.
func ManaCostGT(v int) predicate.Ability {
	return predicate.Ability(sql.FieldGT(FieldManaCost, v))
}

// ManaCostGTE applies the GTE predicate on the "mana_cost" field.
func ManaCostGTE(v int) predicate.Ability {
	return predicate.Ability(sql.FieldGTE(FieldManaCost, v))
}

// ManaCostLT applies the LT predicate on the "mana_cost" field.
func ManaCostLT(v int) predicate.Ability {
	return predicate.Ability(sql.FieldLT(FieldManaCost, v))
}

// ManaCostLTE applies the LTE predicate on the "mana_cost" field.
func ManaCostLTE(v int) predicate.Ability {
	return predicate.Ability(sql.FieldLTE(FieldManaCost, v))
}

// StaminaCostEQ applies the EQ predicate on the "stamina_cost" field.
func StaminaCostEQ(v int) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldStaminaCost, v))
}

// StaminaCostNEQ applies the NEQ predicate on the "stamina_cost" field.
func StaminaCostNEQ(v int) predicate.Ability {
	return predicate.Ability(sql.FieldNEQ(FieldStaminaCost, v))
}

// StaminaCostIn applies the In predicate on the "stamina_cost" field.
func StaminaCostIn(vs ...int) predicate.Ability {
	return predicate.Ability(sql.FieldIn(FieldStaminaCost, vs...))
}

// StaminaCostNotIn applies the NotIn predicate on the "stamina_cost" field.
func StaminaCostNotIn(vs ...int) predicate.Ability {
	return predicate.Ability(sql.FieldNotIn(FieldStaminaCost, vs...))
}

// StaminaCostGT applies the GT predicate on the "stamina_cost" field.
func StaminaCostGT(v int) predicate.Ability {
	return predicate.Ability(sql.FieldGT(FieldStaminaCost, v))
}

// StaminaCostGTE applies the GTE predicate on the "stamina_cost" field.
func StaminaCostGTE(v int) predicate.Ability {
	return predicate.Ability(sql.FieldGTE(FieldStaminaCost, v))
}

// StaminaCostLT applies the LT predicate on the "stamina_cost" field.
func StaminaCostLT(v int) predicate.Ability {
	return predicate.Ability(sql.FieldLT(FieldStaminaCost, v))
}

// StaminaCostLTE applies the LTE predicate on the "stamina_cost" field.
func StaminaCostLTE(v int) predicate.Ability {
	return predicate.Ability(sql.FieldLTE(FieldStaminaCost, v))
}

// HpCostEQ applies the EQ predicate on the "hp_cost" field.
func HpCostEQ(v int) predicate.Ability {
	return predicate.Ability(sql.FieldEQ(FieldHpCost, v))
}

// HpCostNEQ applies the NEQ predicate on the "hp_cost" field.
func HpCostNEQ(v int) predicate.Ability {
	return predicate.Ability(sql.FieldNEQ(FieldHpCost, v))
}

// HpCostIn applies the In predicate on the "hp_cost" field.
func HpCostIn(vs ...int) predicate.Ability {
	return predicate.Ability(sql.FieldIn(FieldHpCost, vs...))
}

// HpCostNotIn applies the NotIn predicate on the "hp_cost" field.
func HpCostNotIn(vs ...int) predicate.Ability {
	return predicate.Ability(sql.FieldNotIn(FieldHpCost, vs...))
}

// HpCostGT applies the GT predicate on the "hp_cost" field.
func HpCostGT(v int) predicate.Ability {
	return predicate.Ability(sql.FieldGT(FieldHpCost, v))
}

// HpCostGTE applies the GTE predicate on the "hp_cost" field.
func HpCostGTE(v int) predicate.Ability {
	return predicate.Ability(sql.FieldGTE(FieldHpCost, v))
}

// HpCostLT applies the LT predicate on the "hp_cost" field.
func HpCostLT(v int) predicate.Ability {
	return predicate.Ability(sql.FieldLT(FieldHpCost, v))
}

// HpCostLTE applies the LTE predicate on the "hp_cost" field.
func HpCostLTE(v int) predicate.Ability {
	return predicate.Ability(sql.FieldLTE(FieldHpCost, v))
}

// HasCharacters applies the HasEdge predicate on the "characters" edge.
func HasCharacters() predicate.Ability {
	return predicate.Ability(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CharactersTable, CharactersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCharactersWith applies the HasEdge predicate on the "characters" edge with a given conditions (other predicates).
func HasCharactersWith(preds ...predicate.Character) predicate.Ability {
	return predicate.Ability(func(s *sql.Selector) {
		step := newCharactersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEffects applies the HasEdge predicate on the "effects" edge.
func HasEffects() predicate.Ability {
	return predicate.Ability(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EffectsTable, EffectsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEffectsWith applies the HasEdge predicate on the "effects" edge with a given conditions (other predicates).
func HasEffectsWith(preds ...predicate.AbilityEffect) predicate.Ability {
	return predicate.Ability(func(s *sql.Selector) {
		step := newEffectsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ability) predicate.Ability {
	return predicate.Ability(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ability) predicate.Ability {
	return predicate.Ability(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ability) predicate.Ability {
	return predicate.Ability(sql.NotPredicates(p))
}
