// Code generated by ent, DO NOT EDIT.

package charactertag

import (
	"herbst-server/db/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldLTE(FieldID, id))
}

// Tag applies equality check predicate on the "tag" field. It's identical to TagEQ.
func Tag(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldEQ(FieldTag, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldEQ(FieldSource, v))
}

// EarnedAt applies equality check predicate on the "earned_at" field. It's identical to EarnedAtEQ.
func EarnedAt(v time.Time) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldEQ(FieldEarnedAt, v))
}

// TagEQ applies the EQ predicate on the "tag" field.
func TagEQ(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldEQ(FieldTag, v))
}

// TagNEQ applies the NEQ predicate on the "tag" field.
func TagNEQ(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldNEQ(FieldTag, v))
}

// TagIn applies the In predicate on the "tag" field.
func TagIn(vs ...string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldIn(FieldTag, vs...))
}

// TagNotIn applies the NotIn predicate on the "tag" field.
func TagNotIn(vs ...string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldNotIn(FieldTag, vs...))
}

// TagGT applies the GT predicate on the "tag" field.
func TagGT(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldGT(FieldTag, v))
}

// TagGTE applies the GTE predicate on the "tag" field.
func TagGTE(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldGTE(FieldTag, v))
}

// TagLT applies the LT predicate on the "tag" field.
func TagLT(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldLT(FieldTag, v))
}

// TagLTE applies the LTE predicate on the "tag" field.
func TagLTE(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldLTE(FieldTag, v))
}

// TagContains applies the Contains predicate on the "tag" field.
func TagContains(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldContains(FieldTag, v))
}

// TagHasPrefix applies the HasPrefix predicate on the "tag" field.
func TagHasPrefix(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldHasPrefix(FieldTag, v))
}

// TagHasSuffix applies the HasSuffix predicate on the "tag" field.
func TagHasSuffix(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldHasSuffix(FieldTag, v))
}

// TagEqualFold applies the EqualFold predicate on the "tag" field.
func TagEqualFold(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldEqualFold(FieldTag, v))
}

// TagContainsFold applies the ContainsFold predicate on the "tag" field.
func TagContainsFold(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldContainsFold(FieldTag, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldContainsFold(FieldSource, v))
}

// EarnedAtEQ applies the EQ predicate on the "earned_at" field.
func EarnedAtEQ(v time.Time) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldEQ(FieldEarnedAt, v))
}

// EarnedAtNEQ applies the NEQ predicate on the "earned_at" field.
func EarnedAtNEQ(v time.Time) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldNEQ(FieldEarnedAt, v))
}

// EarnedAtIn applies the In predicate on the "earned_at" field.
func EarnedAtIn(vs ...time.Time) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldIn(FieldEarnedAt, vs...))
}

// EarnedAtNotIn applies the NotIn predicate on the "earned_at" field.
func EarnedAtNotIn(vs ...time.Time) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldNotIn(FieldEarnedAt, vs...))
}

// EarnedAtGT applies the GT predicate on the "earned_at" field.
func EarnedAtGT(v time.Time) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldGT(FieldEarnedAt, v))
}

// EarnedAtGTE applies the GTE predicate on the "earned_at" field.
func EarnedAtGTE(v time.Time) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldGTE(FieldEarnedAt, v))
}

// EarnedAtLT applies the LT predicate on the "earned_at" field.
func EarnedAtLT(v time.Time) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldLT(FieldEarnedAt, v))
}

// EarnedAtLTE applies the LTE predicate on the "earned_at" field.
func EarnedAtLTE(v time.Time) predicate.CharacterTag {
	return predicate.CharacterTag(sql.FieldLTE(FieldEarnedAt, v))
}

// HasCharacter applies the HasEdge predicate on the "character" edge.
func HasCharacter() predicate.CharacterTag {
	return predicate.CharacterTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CharacterTable, CharacterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCharacterWith applies the HasEdge predicate on the "character" edge with a given conditions (other predicates).
func HasCharacterWith(preds ...predicate.Character) predicate.CharacterTag {
	return predicate.CharacterTag(func(s *sql.Selector) {
		step := newCharacterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CharacterTag) predicate.CharacterTag {
	return predicate.CharacterTag(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CharacterTag) predicate.CharacterTag {
	return predicate.CharacterTag(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CharacterTag) predicate.CharacterTag {
	return predicate.CharacterTag(sql.NotPredicates(p))
}
