name: Commit Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Commit Lint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}